### ISSUE TITLE
aws-sdk-js produces bad authorization header with binary data

### ISSUE THREAD

**Issue by tmcw** [aws/aws-sdk-js#484] opened 2015-01-28 22:36 UTC
![2015-01-28 at 5 30 pm](https://cloud.githubusercontent.com/assets/32314/5948524/6a5a1bca-a713-11e4-83c8-d62494d504a7.png)

Seeing this with aws-sdk 2.1.8 and both browserify 7.x and 8.x - it looks like [crypto-browserify uses create-hmac](https://github.com/crypto-browserify/createHmac/blob/master/browser.js#L65) which creates a binary buffer with codes greater than what's in ascii, and this triggers a [potential chrome bug](https://code.google.com/p/chromium/issues/detail?id=319694) but I'm not sure sure - it seems more like the digest should be hex encoded.

**Comment by lsegal** [comment] 2015-01-28 23:01
The value should in fact be base64 encoded. In my local tests using the SDK, this value is correctly encoded. Are you building a custom version or are you using a specific build? Also, which browser version is this?

**Comment by tmcw** [comment] 2015-01-28 23:01
I'm using browserify: it looks like the culprit is https://github.com/crypto-browserify/createHmac/pull/4

**Comment by lsegal** [comment] 2015-01-28 23:05
Ah, it looks like we might be using a slightly older crypto-browserify install. That definitely looks like a regression in that library, but I'll keep this open to track it since we depend on that library when we release. Thanks for letting us know!

**Comment by tmcw** [comment] 2015-02-16 19:45
Fixed upstream in createHmac 1.1.3.

**Comment by AdityaManohar** [comment] 2015-02-16 23:12
@tmcw 
Thanks for letting us know! I can confirm that `browserify` does work with `crypto-browserify/createHmac v1.1.3`.

I'm going to close this issue out as the problem seems to be resolved. Feel free to reopen this issue or open another issue if you run into any other problems.

And again, thanks for reporting!

**Closed by AdityaManohar** 2015-02-16 23:12 UTC
Labels: Bug, Third Party
