### ISSUE TITLE
Does this  fully support cognito functions ?

### ISSUE THREAD

**Issue by asanka-x** [aws/aws-sdk-js#664] opened 2015-07-16 05:14 UTC
I am getting an error saying action not found when using cognito developer identity (method name mentioned below)

getOpenIdTokenForDeveloperIdentity

**Comment by lsegal** [comment] 2015-07-16 05:22
Can you provide code that reproduces this along with the version of the SDK you're using and Node.js or browser versions?

**Comment by AdityaManohar** [comment] 2015-07-27 19:55
I'm marking this as closed since there hasn't been any recent correspondence. Feel free to reopen this issue or open another issue if you have other questions.

**Closed by AdityaManohar** 2015-07-27 19:55 UTC
Labels: Feedback Requested, Question
