### ISSUE TITLE
queue missing from SQS HTTP Request's URL PATH

### ISSUE THREAD

**Issue by oldshuren** [aws/aws-sdk-js#496] opened 2015-02-05 22:06 UTC
The Amazon document http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/MakingRequests_MakingQueryRequestsArticle.html says for SQS the queue should be the resource (PATH) of the request URL, for example, 

http://sqs.us-east-1.amazonaws.com/123456789012/queue1?Action=SendMessage&MessageBody=Your%20Message%20Text​&Version=2012-11-05​&AUTHPARAMS

But in the current javascript implementation, the queue is missing from the URL path, but a QueueUrl parameter is used instead, that is the actually request become

http://sqs.us-east-1.amazonaws.com/?QueueUrl=http%3A%2F%2F1sqs.us-est-1.amazonaws.com%2F123456789012%2Fqueue1&Action=SendMessage&MessageBody=Your%20Message%20Text​&Version=2012-11-05​&AUTHPARAMS 

This breaks the Comcast SQS implementation. The CMB CQS  server will return AWS.SimpleQueueService.NonExistentQueue error.

**Comment by oldshuren** [comment] 2015-02-05 22:07
The current javascript implementation is using POST, not GET. But the problem is the same. No queue in the URL PATH, only QueueUrl in parameters.

**Comment by oldshuren** [comment] 2015-02-05 22:12
My solution is add one line in lib/services/sqs.js to set the http request path, but I'm not sure it is the right solution.

```javascript
  buildEndpoint: function buildEndpoint(request) {
    var url = request.httpRequest.params.QueueUrl;
    if (url) {
      request.httpRequest.endpoint = new AWS.Endpoint(url);
     // http request need queue in the url path
      request.httpRequest.path = request.httpRequest.endpoint.path || '/';

      // signature version 4 requires the region name to be set,
      // sqs queue urls contain the region name
      var matches = request.httpRequest.endpoint.host.match(/^sqs\.(.+?)\./);
      if (matches) request.httpRequest.region = matches[1];
    }
  }
```

**Comment by AdityaManohar** [comment] 2015-02-05 22:31
Which version of the SDK are you using? I'm not able to reproduce an error with SDK v2.1.8 and Node.js v0.10.35

```javascript
var AWS = require('aws-sdk');
var sqs = new AWS.SQS();
var params = {
  QueueUrl: 'https://sqs.us-west-2.amazonaws.com/026153618265/aditm-us-west-2',
  MessageBody: 'test'
}
sqs.sendMessage(params, function(err,data){
  if (err) console.log(err);
  else console.log(data);
});
```
Note that the parameters are derived from the [SQS service model](https://github.com/aws/aws-sdk-js/blob/master/apis/sqs-2012-11-05.min.json#L387) and are not hand maintained.

**Comment by oldshuren** [comment] 2015-02-05 22:51
Both npm install aws-sdk and github version have the problem. 

The aws server won't complain, only when you talk to CMB server or use wireshark to capture the packet  you'll see it.

And Java SDK version is correctly set the queue as URL PATH.

**Comment by lsegal** [comment] 2015-02-05 23:24
> This breaks the Comcast SQS implementation.

Can you explain what you mean by this? Passing the QueueURL as a parameter in the body is supported by SQS, and should be supported by any SQS-compatible API implementation. Many of our other SDKs use this mechanism as well.

**Comment by AdityaManohar** [comment] 2015-02-05 23:35
>  I guess that is the reason there is a buildEndpoint() function in sqs.js to modify the endpoint of the http request, but the that modification is not really reflected in the real http request sent out to the server.

The `buildEndpoint()` handler correctly set the region from the `QueueUrl`. I just confirmed this with the AWS CLI as well. There is no queue name in the path.
```
POST
/

host:us-west-2.queue.amazonaws.com
user-agent:aws-cli/1.6.4 Python/2.7.6 Darwin/14.1.0
x-amz-date:20150205T230444Z
```
> only when you talk to CMB server

Can you explain what you mean by this please?

**Comment by oldshuren** [comment] 2015-02-05 23:51
Comcast released an open source implementation of Amazon's SQS and SNS server, here is github link

https://github.com/Comcast/cmb

In Comcast's implementation, if the queue info is missing in the path, the server will return AWS.SimpleQueueService.NonExistentQueue error.

**Comment by oldshuren** [comment] 2015-02-06 00:03
The JAVA AWS SDK uses only queue name in path, no QueueUrl in the body. And the Amazon's own document "Making Query Request" http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/MakingRequests_MakingQueryRequestsArticle.html says the queue name should be in the URL path. And the SQS service wsdl http://queue.amazonaws.com/doc/2012-11-05/QueueService.wsdl doesn't mention QueueUrl as parameter

**Comment by lsegal** [comment] 2015-02-06 07:13
@oldshuren SQS supports the QueueURL either as the endpoint *or* as the parameter. This isn't documented all that well, but it is supported, and many tools like this SDK and the CLI actually rely on this behavior, so ideally any implementation of this protocol should support this parameter. I would recommend opening an issue against Comcast/cmb to let them know about this behavior.

**Comment by oldshuren** [comment] 2015-02-06 14:35
@lsegal I'll open an issue in Comcast/cmb, but aws-sdk should also use its own standard. At least among different languages, such as java and javascript. Now java and javascript use different implementation, it really confuses people.

By the way, I notice another difference between java and javascript implementations. Java will reuse the TCP connection, but javascript will open a new TCP connection for each request. It impacts performance somehow :-1:

**Comment by lsegal** [comment] 2015-02-06 14:54
>  but javascript will open a new TCP connection for each request

This is a detail of Node.js. You can configure your Node.js runtime to use [keepalive connections](https://github.com/node-modules/agentkeepalive) if necessary. Node.js 0.12 (and io.js) is going to provide out-of-the-box support for keepalive connection pooling, which should improve performance.

**Comment by oldshuren** [comment] 2015-02-06 17:07
Thanks! 

By the way, I submitted an issue in comcast/cmb.

**Comment by AdityaManohar** [comment] 2015-02-09 17:50
@oldshuren 
I'm closing this out as this doesn't seem to be a problem with the SDK. Please feel free to re-open it or open another issue if you have any other questions.

**Closed by AdityaManohar** 2015-02-09 17:50 UTC
Labels: Question, Third Party

**Comment by oldshuren** [comment] 2015-02-09 18:00
@AdityaManohar I think aws-sdk-js should be modified to put queue info in the URL PATH, the QueueUrl can be still used. The reasons are,

1. It is what Amazon's documentation specified. If someone implements a server they will follow the specification, not reverse engining existing code.
2. Different language implementations should use the same protocol on the wire. 

For me personally I have to patch the aws-sdk, because it is much easier to patch aws-sdk-js (just add one line) than to patch the cmb/sqs.

Thanks!

**Comment by lsegal** [comment] 2015-02-09 18:18
@oldshuren we will reach out to the documentation team to ensure that the SQS docs reflect the current API. Thanks for reporting!
