### ISSUE TITLE
ssm.listDocuments Filters not working for custom key/value pairs

### ISSUE THREAD

**Issue by awsjosh** [aws/aws-sdk-js#3637] opened 2021-02-17 21:08 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  **A previous bug report was submitted here:  https://github.com/aws/aws-sdk-js/issues/2858**

**Describe the bug**

**ssm.listDocuments Filters is not returning results when filtering on a custom key/value pair.  For example, when filtering on:  `Key=tag:tagName,Values=valueName`, (replacing tagName and valueName with the appropriate values) no results are returned.  When running the same listDocuments command via the CLI, with the same filters, the expected results are returned.**

**Is the issue in the browser/Node.js?**
**Node.js**

**If on Node.js, are you running this on AWS Lambda?**
**Yes**

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`

**AWS_Lambda_nodejs12.x**

**SDK version number**

**SDK VERSION 2.804.0**

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

1. Create an SSM document and add the tag key: 'Project', value: 'SSM'.
2. Create a Lambda function with the appropriate IAM permissions (Systems Manager : ListDocuments):

```
var AWS = require("aws-sdk");
var ssm = new AWS.SSM();
exports.handler = function(event, context, callback) {
    var params = {
        Filters: [
        {
            Key: 'tag:Project',
            Values: [
                'SSM'
            ]
        }
        ] 
    }; 
ssm.listDocuments(params, function(err, data) {
    if (err) console.log(err, err.stack); // an error occurred
    else     console.log(data);           // successful response
});
};
```

3. Test the Lambda function

**Expected behavior**

The listDocuments function should return an object with a list of the SSM Documents created in Step 1 via the DocumentIdentifiers property.

**Screenshots**

**Additional context**

**Comment by ajredniwja** [comment] 2021-02-19 00:10
@awsjosh, thanks for opening this,  I was able to reproduce the issue, I am not sure about the root cause just yet, but would compare the request created by JS and CLI

**Comment by awsjosh** [comment] 2021-02-19 00:13
Thanks, @ajredniwja!

**Comment by ajredniwja** [comment] 2021-02-19 00:36
Params that work: 

```
var params = {
  Filters: [
  {
      Key: 'tag:Project',
      Values: [
          'SSM'
      ]
  },
  {
    Key: 'Owner',
    Values: [
      'Self'
    ]
  }
  ] 
}
```

**Comment by ajredniwja** [comment] 2021-02-19 00:38
CLI command that diddnt work in my test: 
```
aws ssm list-documents --filter Key=tag:Project,Values=SSM
```

CLI command that worked:

```
aws ssm list-documents \
--filters Key=Owner,Values=Self Key=tag:Project,Values=SSM
```

**Comment by ajredniwja** [comment] 2021-02-19 00:38
Also worth noting that the results were same for PHP SDK i.e similar to JS SDK

**Comment by ajredniwja** [comment] 2021-02-25 10:50
@awsjosh closing this issue as the results were consistent to other SDKs. 

Please reach out if you have any questions or you feel differently.

**Closed by ajredniwja** 2021-02-25 10:50 UTC
Labels: guidance

**Comment by awsjosh** [comment] 2021-02-25 12:22
Hi @ajredniwja, since the expected behavior is for this filtering by custom tag to work, and since it does work in the CLI (screenshot attached) - I do believe this needs to be reopened and fixed in all SDKs.  The documentation provides examples for this scenario, so customers expect this to work.  The SDKs will need to be consistent with the expected behavior provided in the documentation and with the CLI.

<img width="701" alt="Screen Shot 2021-02-25 at 7 20 54 AM" src="https://user-images.githubusercontent.com/64805019/109152889-1770a980-773a-11eb-96f7-6d61ef8ab64b.png">
