### ISSUE TITLE
Is it possible to use the getSignedUrl like this?

### ISSUE THREAD

**Issue by jontelm** [aws/aws-sdk-js#480] opened 2015-01-24 07:40 UTC
https://github.com/bookingbricks/file-upload-example

I have only be able to upload a file without any content or if i set Body in the getSignedUrl.
Seems like Content-Length is set to 0 as default?

**Comment by lsegal** [comment] 2015-01-24 23:53
@jontelm FYI this is unrelated but one thing I would *strongly* recommend is not hardcoding your access and secret keys in your project. Rely on the shared credentials file, environment variables, or IAM roles instead. See our [Getting Started Guide](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html) for more.

**Comment by lsegal** [comment] 2015-01-24 23:59
Re-opening since this is a better place to discuss your specific issue instead of #468. I've not been able to reproduce requiring a content length or body when signing. Which version of Node.js and the SDK are you using?

**Comment by jontelm** [comment] 2015-01-25 10:09
Node v0.10.33 with version 2.1.7. The example works now after setting ContentType.

**Comment by lsegal** [comment] 2015-01-25 10:12
@jontelm sounds good. I'm going to close this again then. Feel free to reopen if you have more questions. Note that you only have to provide a ContentType if your client is passing one. To be specific, your client **must** send the same Content-Type that the URL was signed with, so if your client is being forced to use a specific Content-Type header, make sure to sign with that when generating the URL. That is one of the few restrictions when using the default S3 signer. Using SigV4 (`signatureVersion: 'v4'` in config options) would allow you to remove that restriction, if that is necessary.

Hope that helps!

**Closed by lsegal** 2015-01-25 10:12 UTC
