### ISSUE TITLE
S3.createBucket with LocationContraint: '' fails

### ISSUE THREAD

**Issue by e-gineer** [aws/aws-sdk-js#526] opened 2015-03-06 17:24 UTC
Creating an S3 bucket while setting the LocationConstraint to an empty string fails, but should work as a valid setting for US Standard according to the documentation at:
* http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#createBucket-property
* http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUT.html

The workaround is simple enough (just remove LocationConstraint when working in US Standard), but I wanted to bring this to your attention / confirm it's not just me <grin>.

Code to reproduce:

```
aws = require 'aws-sdk'

#
# Works, as expected, creating bucket in US Standard
#

params =
  Bucket: 'bucket-test-should-work-in-us-standard'

conn = new aws.S3
  signatureVersion: 'v4'
  s3ForcePathStyle: true

conn.createBucket params, (err, result) ->
  console.dir err
  console.dir result


#
# Fails, as expected, invalid location constraint since us-east-1 is not valid
#

params =
  Bucket: 'bucket-test-should-fail'
  CreateBucketConfiguration:
    LocationConstraint: 'us-east-1'

conn = new aws.S3
  signatureVersion: 'v4'
  s3ForcePathStyle: true

conn.createBucket params, (err, result) ->
  console.dir err
  console.dir result


#
# FAILS, UNEXPECTED.
# Accoding to http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUT.html
# and http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#createBucket-property
# an empty string should be a valid location constraint for US Standard region.
#

params =
  Bucket: 'bucket-test-should-work-but-doesnt'
  CreateBucketConfiguration:
    LocationConstraint: ''

conn = new aws.S3
  signatureVersion: 'v4'
  s3ForcePathStyle: true

conn.createBucket params, (err, result) ->
  console.dir err
  console.dir result


#
# FAILS, UNEXPECTED.
# Confirming that changing the connection path style still doesn't help.
#

params =
  Bucket: 'bucket-test-should-work-but-doesnt-region'
  CreateBucketConfiguration:
    LocationConstraint: ''

conn = new aws.S3
  region: 'us-east-1'

conn.createBucket params, (err, result) ->
  console.dir err
  console.dir result
```

**Comment by lsegal** [comment] 2015-03-06 19:10
I can confirm this behavior. This documentation comes from the S3 documentation for [PUT Bucket](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUT.html). It looks like the documentation there might be incorrect, I'll follow up with the S3 team to make sure.

**Comment by e-gineer** [comment] 2015-03-06 19:18
Thanks for the quick confirmation! I've moved forward with the workaround, so please close this issue when you consider it complete from the AWS side.

**Comment by AdityaManohar** [comment] 2015-03-25 00:37
@e-gineer The documentation has been corrected in the [Amazon S3 PUT Bucket  API reference](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUT.html) as well as the [SDK documentation for createBucket()](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#createBucket-property). 

I'm marking this as closed. Feel free to open a new issue if you have any other questions.

Thanks for reporting!

**Closed by AdityaManohar** 2015-03-25 00:37 UTC
Labels: Documentation, Service / API
