### ISSUE TITLE
ERROR in ./node_modules/aws-sdk/lib/event_listeners.js

### ISSUE THREAD

**Issue by AlexisLapeze** [aws/aws-sdk-js#3221] opened 2020-04-18 16:23 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
event_listener.js does not find module 'util' : 

``` 
Module not found: Error: Can't resolve 'util' in '/Users/lapezealexis/Downloads/listen/frontend/node_modules/aws-sdk/lib'
```
**Is the issue in the browser/Node.js?**
no

**If on Node.js, are you running this on AWS Lambda?**
on aws S3
**Details of the browser/Node.js version**
v12.16.1
**SDK version number**
└── aws-sdk@2.658.0 

**To Reproduce (observed behavior)**
you can find clone and build my repo with ng build: https://github.com/AlexisLapeze/frontend.git

**Expected behavior**
build my app

**Screenshots**
no screenshots
**Additional context**
no

**Comment by ajredniwja** [comment] 2020-04-22 20:33
Hey @AlexisLapeze Thank-you for reaching out to us with your issue, I was not able to reproduce the case as both:

`ng build`
`ng serve`

worked without errors, I would not classify this as a bug with the SDK but something that you might doing wrong unknowingly, I would check the dependencies and try it fresh.

**Comment by AlexisLapeze** [comment] 2020-04-23 06:31
hi, thank's for the reply. 
in my package.json i change aws-sdk for this link : "aws-sdk": "https://github.com/lucastrcts/aws-sdk-js",

this repo modify the lib/event_listeners.js : https://github.com/lucastrcts/aws-sdk-js/commit/b38a99c6790c5cfe557a3bbb456b80ea5542a7ee

and it's working

**Comment by ajredniwja** [comment] 2020-04-23 19:47
That is great, please reach out if you have any other questions. 

On another note, I really liked your frontend. 👍 

Closing this issue now.

**Closed by ajredniwja** 2020-04-23 19:47 UTC
Labels: guidance, response-requested
