### ISSUE TITLE
Using incorrect route53 endpoint in China regions

### ISSUE THREAD

**Issue by zxkane** [aws/aws-sdk-js#3296] opened 2020-06-08 09:06 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**

Using route53 API with default setting in China regions got below error,

```
Error: getaddrinfo ENOTFOUND route53.cn-northwest-1.amazonaws.com.cn
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: -3008,
  code: 'NetworkingError',
  syscall: 'getaddrinfo',
  hostname: 'route53.cn-northwest-1.amazonaws.com.cn',
  region: 'cn-northwest-1',
  retryable: true,
  time: 2020-06-08T09:00:40.798Z
} Error: getaddrinfo ENOTFOUND route53.cn-northwest-1.amazonaws.com.cn
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
```

We have to explicitly specifying the endpoint `route53.amazonaws.com.cn` given in [doc](https://docs.amazonaws.cn/en_us/general/latest/gr/r53.html), which makes the code can not be migrated to aws global.

**Is the issue in the browser/Node.js?**
Browser/Node.js

Both

**If on Node.js, are you running this on AWS Lambda?**

N/A

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`

**v14.3.0**

**SDK version number**
Example: v2.691.0
* For browsers, the SDK version number is in the script tag <pre>src=".../aws-sdk-<b>2.466.0</b>.min.js"</pre>
* For Node.js, get SDK version by
  * running command `npm list aws-sdk` from your root directory
  * printing the output of `console.log(AWS.VERSION)` in your code where `AWS = require("aws-sdk");`
  * if running on Lambda and using SDK provided by Lambda runtime, you can find the SDK versions [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) 

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

```js
var AWS = require('aws-sdk');

var r53 = new AWS.Route53({
//  endpoint: 'route53.amazonaws.com.cn'
});

var params = {
  MaxItems: '10'
};
r53.listHostedZones(params, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});
```
**Expected behavior**

The api returns successfully.

**Screenshots**

**Additional context**

**Comment by ajredniwja** [comment] 2020-06-09 02:13
Hey @zxkane thank-you for reaching out, I am not able to reproduce the behavior with the code sample that you provided. 

Can you provide me some more information on how you are setting the region?

**Comment by zxkane** [comment] 2020-06-09 02:48
I'm using below env to set credentials and region, 

```
export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=
export AWS_SESSION_TOKEN=
export AWS_REGION=cn-northwest-1

# use awscli to query hosted zones in cn regions with above env,
aws route53 list-hosted-zones
{
    "HostedZones": [
        {
            "Id": "/hostedzone/Z2C5FOBW37XAO3",
            "Name": "xxx.com.",
            "CallerReference": "20181113",
            "Config": {
                "PrivateZone": false
            },
            "ResourceRecordSetCount": 16
        }
    ]
}
```

**Comment by philipwigg** [comment] 2020-06-15 09:11
It says [in the docs](https://docs.amazonaws.cn/en_us/general/latest/gr/cnnorthwest_region.html) that URL for Route53 in the ```cn-northwest-1``` region is ```route53-ec2-dns.cn-northwest-1.amazonaws.com.cn```.

**Comment by zxkane** [comment] 2020-06-15 11:15
@ajredniwja Do you need more info to reproduce it?

> It says [in the docs](https://docs.amazonaws.cn/en_us/general/latest/gr/cnnorthwest_region.html) that URL for Route53 in the `cn-northwest-1` region is `route53-ec2-dns.cn-northwest-1.amazonaws.com.cn`.

Looks like the doc is wrong. The record `route53-ec2-dns.cn-northwest-1.amazonaws.com.cn` can not be resolved.

**Comment by zxkane** [comment] 2020-06-15 11:16
@ajredniwja Do you have enough information to reproduce it? If you can reproduce it, any plan to fix it?

**Comment by philipwigg** [comment] 2020-06-15 13:56
@zxkane You're right. On [this page](https://docs.amazonaws.cn/en_us/general/latest/gr/r53.html) it claims the endpoint is ```route53.amazonaws.com.cn``` which does resolve.

I think this is what the Go SDK [is using too](https://github.com/aws/aws-sdk-go/blob/d62ea754257fe243a79fc36dc796b0982138775a/models/endpoints/endpoints.json#L63810).

**Comment by ajredniwja** [comment] 2020-06-15 22:09
> @ajredniwja Do you have enough information to reproduce it? If you can reproduce it, any plan to fix it?

Was able to reproduce it, I also looked at the PR which needs some changes. Will talk to the team.

**Comment by ajredniwja** [comment] 2020-06-15 23:44
@zxkane closing this issue now in the favor of #3274.

It only requires a change log now.

**Closed by ajredniwja** 2020-06-15 23:44 UTC
Labels: bug
