### ISSUE TITLE
Regression in v2.1262.0 - "Request is missing authentication token"

### ISSUE THREAD

**Issue by whih0818** [aws/aws-sdk-js#4286] opened 2022-11-28 10:08 UTC
### Describe the bug

We are using serverless framework.
When trying deploy serverless framework application to aws, failed with "Request is missing authentication token".

SigV4 Authorization header not exists on v2.1262.0, it failed.
So i forcelly downgrade with aws-sdk version to v2.1261.0 and it worked as expected.

![image](https://user-images.githubusercontent.com/1394295/204248522-73ab3a6b-cd96-4f82-9d8d-d00e24d78034.png)

### Expected Behavior

Properly generate and fill 'Authorization' header with AWS V4 Signature 

### Current Behavior

Invalid 'Authorization' header configured

### Reproduction Steps

Make Cloudformation describeStacks API call

### SDK version used

v2.1262.0

### Environment details (OS name and version, etc.)

debian 9, node 12.22.5

**Comment by kayman-mk** [comment] 2022-11-28 10:12
See #4285

**Comment by brainframe-me** [comment] 2022-11-28 11:31
This is causing a lot of issues in the serverless world as well:
https://github.com/serverless/serverless/issues/11561

**Comment by prashant9428** [comment] 2022-11-28 13:09
solution- downgrade the SDK version untill the new release comes

**Comment by MehranJanfeshan** [comment] 2022-11-28 16:25
+1

**Comment by GauravRachchh** [comment] 2022-11-28 18:08
+1

**Comment by BasilaryGroup** [comment] 2022-11-28 18:09
+1

**Comment by Antoniojfl** [comment] 2022-11-28 18:24
+1

**Comment by trivikr** [comment] 2022-11-28 18:31
The AWS SDK for JavaScript team is looking into this issue.

If anyone has a minimal repro, please add it as an issue comment.
We'll provide one, when we come across while triaging.

**Comment by trivikr** [comment] 2022-11-28 18:32
The v2.1262.0 changelog for reference: https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#212620

**Comment by trivikr** [comment] 2022-11-28 18:43
Commits between the releases https://github.com/aws/aws-sdk-js/compare/v2.1261.0...v2.1262.0

The issue is likely in one of the following PRs:
* https://github.com/aws/aws-sdk-js/pull/4274
* https://github.com/aws/aws-sdk-js/pull/4284

**Comment by trivikr** [comment] 2022-11-28 19:13
Commits between releases https://github.com/aws/aws-sdk-js/compare/v2.1259.0...v2.1262.0

There were no custom changes released in `v2.1260.0` or `v2.1261.0`

**Comment by ajredniwja** [comment] 2022-11-28 20:09
Update: The team is currently working on pushing a fix.

**Comment by DSuhinin** [comment] 2022-11-28 20:21
+1

**Comment by trivikr** [comment] 2022-11-28 21:31
Verified that fix from https://github.com/aws/aws-sdk-js/pull/4288 fixes the issue.

Refer Pull request in https://github.com/trivikr/serverless-aws-bug/pull/1
We're aiming to release this fix in `v2.1263.0` within the next 24 hours.

**Comment by sobolk** [comment] 2022-11-28 22:30
+1

**Comment by kim00425** [comment] 2022-11-29 04:12
same here

**Comment by trivikr** [comment] 2022-11-29 05:12
Release v2.1263.0 is out, and verified that "Request is missing Authentication Token" error is no longer thrown.

https://github.com/andrmoel/serverless-aws-bug/pull/2

**Closed by trivikr** 2022-11-29 05:12 UTC
Labels: bug, p0
