### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by Alex0007** [aws/aws-sdk-js#500] opened 2015-02-07 11:12 UTC
/home/ubuntu/processing/node_modules/aws-sdk/lib/sequential_executor.js:261
        throw err;
              ^
TypeError: Cannot read property 'length' of null
    at Object.AWS.util.buffer.concat (/home/ubuntu/processing/node_modules/aws-sdk/lib/util.js:114:29)
    at Request.HTTP_DONE (/home/ubuntu/processing/node_modules/aws-sdk/lib/event_listeners.js:210:36)
    at Request.callListeners (/home/ubuntu/processing/node_modules/aws-sdk/lib/sequential_executor.js:132:20)
    at Request.emit (/home/ubuntu/processing/node_modules/aws-sdk/lib/sequential_executor.js:100:10)
    at Request.emitEvent (/home/ubuntu/processing/node_modules/aws-sdk/lib/request.js:392:10)
    at IncomingMessage.onEnd (/home/ubuntu/processing/node_modules/aws-sdk/lib/event_listeners.js:180:26)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

This is node 0.12

**Comment by lsegal** [comment] 2015-02-07 18:50
Can you provide the version of Node.js and SDK that you are using?

**Comment by Alex0007** [comment] 2015-02-08 19:52
Node.js v0.12.0 stable
Latest SDK from npm

**Comment by AdityaManohar** [comment] 2015-02-09 20:52
Would you be able to share some sample code that you are using? I'm unable to reproduce it with the following code:

```javascript
var AWS = require('aws-sdk');
var s3 = new AWS.S3();

s3.listBuckets(function(err, data){
  if (err) console.log(err);
  else console.log(data);
});
```
Would you also be able to log the output of `AWS.VERSION`?

**Comment by stockholmux** [comment] 2015-02-12 18:17
I am getting a similar error -

```
uncaughtException TypeError: Cannot read property 'length' of null
    at Object.AWS.util.buffer.concat (/home/kyle/nodeSites/heccprompt/node_modules/aws-sdk/lib/util.js:118:29)
    at Request.HTTP_DONE (/home/kyle/nodeSites/heccprompt/node_modules/aws-sdk/lib/event_listeners.js:219:36)
    at Request.callListeners (/home/kyle/nodeSites/heccprompt/node_modules/aws-sdk/lib/sequential_executor.js:132:20)
    at Request.emit (/home/kyle/nodeSites/heccprompt/node_modules/aws-sdk/lib/sequential_executor.js:100:10)
    at Request.emitEvent (/home/kyle/nodeSites/heccprompt/node_modules/aws-sdk/lib/request.js:526:10)
    at IncomingMessage.onEnd (/home/kyle/nodeSites/heccprompt/node_modules/aws-sdk/lib/event_listeners.js:184:26)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)
```
I'm using node 0.12 and the latest SDK.

I'm doing a simpledb request something like this:

```
simpledb.select({
      'SelectExpression'  : "Select * from "+this.simpleDBTable+" where itemName() like '"+ this.year+this.month+this.day +"%' limit 1000";,
      'ConsistentRead'    : true
    },
    this.indexCallback(complete)
  );
```

Worked fine on Node 10.30

**Comment by AdityaManohar** [comment] 2015-02-12 23:38
@stockholmux 
I am still unable to replicate this on Node v0.12 stable and SDK v2.1.10

```javascript

var callback = function(err, data){ if (err) console.log(err); else console.log(data)};

simpledb.putAttributes({
  Attributes: [{Name: 'foo', Value: 'bar'}], 
  DomainName: 'foobar', 
  ItemName: 'test'
}, callback);

simpledb.select({SelectExpression: 'select * from aditm'}, callback);

```
Can you provide some more information about your environment? Are you running this on an EC2 instance?

**Comment by stockholmux** [comment] 2015-02-14 17:16
Here is the system that is causing the issue:
`Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-37-generic x86_64)` on DigitalOcean, node version `v0.12.0` and aws-sdk package.json shows version `1.6.0`.

I can recreate the issue by running the this script (table names, etc removed)
```
var
    aws = require('aws-sdk'),
    simpleDBTable = '*************',
    simpledb;

aws.config.apiVersions = {
  simpledb: '2009-04-15'
};

aws.config.loadFromPath(*****************);

simpledb = new aws.SimpleDB({
  region : 'US-East',
  endpoint : 'https://sdb.amazonaws.com'
});

simpledb.select({
    'SelectExpression'  : "Select * from "+simpleDBTable+" where itemName() like '20150213%' limit 1000",
    'ConsistentRead'    : true
  },
  function(err, data){ if (err) console.log(err); else console.log(data) }
);
```

This outputs:
```
TypeError: Cannot read property 'length' of null
    at Object.AWS.util.buffer.concat (/home/kyle/nodeSites/heccprompt/node_modules/aws-sdk/lib/util.js:118:29)
    at Request.HTTP_DONE (/home/kyle/nodeSites/heccprompt/node_modules/aws-sdk/lib/event_listeners.js:219:36)
    at Request.callListeners (/home/kyle/nodeSites/heccprompt/node_modules/aws-sdk/lib/sequential_executor.js:132:20)
    at Request.emit (/home/kyle/nodeSites/heccprompt/node_modules/aws-sdk/lib/sequential_executor.js:100:10)
    at Request.emitEvent (/home/kyle/nodeSites/heccprompt/node_modules/aws-sdk/lib/request.js:526:10)
    at IncomingMessage.onEnd (/home/kyle/nodeSites/heccprompt/node_modules/aws-sdk/lib/event_listeners.js:184:26)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

When I execute the same code after switch to Node 0.10.36 (with `nvm use 0.10`) it runs without error.

**Comment by lsegal** [comment] 2015-02-14 17:33
I can't seem to reproduce this on Node 0.12 either. FWIW you should know that 'us-east' is not an actual region name. I would recommend constructing the client as, simply:

```js
simpledb = new aws.SimpleDB({region: 'us-east-1'});
```

Note that the endpoint is built based on the region, you don't need to configure it manually. That said, I'm not sure this will change your results. I was unable to reproduce even without changing that line.

**Comment by lsegal** [comment] 2015-02-14 17:38
@stockholmux are you sure this is the only code you have in your project? Can you confirm the node/SDK version by logging the following in your script?

```js
console.log(process.version, AWS.VERSION);
```

**Comment by stockholmux** [comment] 2015-02-14 18:00
Okay - I think I'm squared on this. As mentioned above my aws-sdk version was set at 1.6.0 not the 2.1.10. During debugging I had swapped aws-sdk versions between 1.6.0 and * in package.json trying to isolate the problem - should I have removed the the directory before running `npm install` again to get the latest version. So, with sdk version 2.1.10 it works fine.

**Comment by AdityaManohar** [comment] 2015-02-16 19:54
@Alex0007 @stockholmux 
I'm closing this issue as the problem is not reproducible, and the SDK seems to be working with Node.js v0.12 stable. Feel free to reopen this issue or open another issue if you continue to have problems.

**Closed by AdityaManohar** 2015-02-16 19:54 UTC
