### ISSUE TITLE
Content-MD5 Error on upload

### ISSUE THREAD

**Issue by hoodsy** [aws/aws-sdk-js#1879] opened 2018-01-15 18:12 UTC
Occasionally when uploading files, I'll receive a `BadDigest: The Content-MD5 you specified did not match what we received.` error.

This has been happening for larger files – small files generally have no issue uploading.

**Comment by chrisradek** [comment] 2018-01-15 18:16
@hoodsy 
Are you providing the MD5 yourself? That will only work for `putObject` calls, and `upload` calls where only a single `putObject` call is made behind the scenes (body < 5 MB). The SDK will actually calculate MD5s for you though, so it shouldn't be necessary for you to also calculate them.

**Comment by hoodsy** [comment] 2018-01-15 18:17
I am not.. could it be related to me specifying the `contentLength`?

**Comment by chrisradek** [comment] 2018-01-15 18:39
Are you uploading streaming data? Do all large files (are those files > 5MB?) fail, or just some of them?

Also, if you could provide some info such as SDK version, and a simple code snippet, that may help as well!

**Comment by srchase** [comment] 2018-08-27 23:52
@hoodsy,

Were you able to get this sorted? If there are not further questions, I'm going to close out this issue.

**Comment by srchase** [comment] 2018-09-04 16:04
Closing out this issue.  Let us know if you have anything additional to add.

**Closed by srchase** 2018-09-04 16:04 UTC
Labels: Closing Soon - Feedback Requested, Question

**Comment by jmhmd** [comment] 2019-02-22 18:47
@srchase 
I have just started getting this error sporadically as well- specifically, I'm uploading streamed gzipped files from an electron app to s3, using `upload()`. On a user's Windows machine in the UK, he gets the `BadDigest` error for some files (seems like smaller ones), but I cannot reproduce the errors on my test machines using the same files. Trying various combinations of including or excluding `ContentLength` and `ContentType` have not fixed the errors. I'm not including `ContentMD5` at all.

SDK version: "aws-sdk": "^2.404.0"

Relevant code:
```js
 // upload instance to s3
          const remoteFolder = `${remoteStudy.shortid}_${series.seriesInstanceUID}`;
          const filename = path.basename(compressedInstancePath);
          // Don't use path.join to build s3 key, because it will use system specific path
          // separators, i.e. backslashes on windows which we don't want.
          const fileKey = `${prefix}/${remoteFolder}/${filename}`;
          const uploadParams = {
            Bucket: s3Bucket,
            Body: fs.createReadStream(compressedInstancePath),
            Key: fileKey,
          };
          await s3.upload(uploadParams).promise();
          instanceObj.url = `https://${path.join('s3.amazonaws.com', s3Bucket, fileKey)}`;
```
