### ISSUE TITLE
Typing issue for DynamoDbClient batchWrite expecting us to us AttributeValue

### ISSUE THREAD

**Issue by mattiLeBlanc** [aws/aws-sdk-js#3339] opened 2020-07-07 05:40 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When I use the `DynamoDB.DocumentClient` from AWS-SDK 2.7 I still get an issue when construct my Batch write items.

The problem is that I using the `BatchWrite` which should support unmarshalled `WriteRequest` as input.
However, when I construct my item:
```
  const items: WriteRequest[] = [];
    
      for (const userId of batch) {
        const item = {
          PutRequest: {
            Item: {
              pk: userId,
              sk: `USER_EVENT:PUBLISHED=${publishedAt}&EVENT_ID=${eventId}`,
              type: 'USER_EVENT',
              eventId,
              publishedAt: publishedAt
            }
          }
        };
        items.push(item);
      }
``` 
I am getting a Typescript complain on the Item map that is not using AttributeValue.
When I step through the typescript of BatchWrite -> BatchWriteItemInput -> BatchWriteItemRequestMap -> WriteRequests -> PutRequest -> PutItemInputAttributeMap  I end up with `export type PutItemInputAttributeMap = {[key: string]: AttributeValue};` which is the AttributeValue. This not unmarshalled!
Only when I use the `batchWriteItem` of Dynamo and not the client, will my code work. 

I believe `export type PutItemInputAttributeMap = {[key: string]: AttributeValue};` should become `export type PutItemInputAttributeMap = {[key: string]: any};` 

**Is the issue in the browser/Node.js?**
NodeJS

**If on Node.js, are you running this on AWS Lambda?**
Yes on Lambda

**Details of the browser/Node.js version**
v12.16.1

**SDK version number**
v2.7

**To Reproduce (observed behavior)**
Create a lambda with the document client and add my code above. You should get a Typescript error on the `items.push(item)`.

**Expected behavior**
No typing error

**Screenshots**
![image](https://user-images.githubusercontent.com/5285035/86719140-21d51a80-c067-11ea-837a-6161672e2ae8.png)

**Comment by mattiLeBlanc** [comment] 2020-07-07 05:41
one typescript hack is to do the following:

```
items.push(item as WriteRequest);
```
This silences Typescript compiler but I haven't run the code yet.

**Comment by ajredniwja** [comment] 2020-07-08 01:49
Hey @mattiLeBlanc thank-you for reaching out to us with your issue, this issue is a duplicate of #2428

Please refer to https://github.com/aws/aws-sdk-js/issues/2428#issuecomment-450405046

Closing this now, please reach out if you have any questions.

**Closed by ajredniwja** 2020-07-08 01:49 UTC
Labels: typings

**Comment by mattiLeBlanc** [comment] 2020-07-08 03:48
The fix was to use `DocumentClient.WriteRequest` instead of `WriteRequest` and `DocumentClient.BatchWriteItemRequestMap` instead of `BatchWriteItemRequestMap`.

It was easy to make this mistake because the interface are exported separately  from  `'aws-sdk/clients/dynamodb';` but are also nested under `DocumentClient`.

Thanks for the hint @ajredniwja
