### ISSUE TITLE
UnknownEndpoint: Inaccessible host:`XXXXXXXXXX`. This service may not be available in the `XXXXXXXXXX` region.

### ISSUE THREAD

**Issue by DeepCFoxXx** [aws/aws-sdk-js#3286] opened 2020-05-28 17:43 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When using s3.upload(); the error of  (UnknownEndpoint: Inaccessible host:`XXXXXXXXXX`. This service may not be available in the `XXXXXXXXXX` region.) is logged.

**Is the issue in the browser/Node.js?**
/Node.js
Had issues with AWS SDK dropping a version number when invoked 2.684.0 => 2.683.0
Updated SDK to newest version 2.685.0 and when using s3.upload(); get the above error.

**If on Node.js, are you running this on AWS Lambda?**
No Lambda

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`

UnknownEndpoint: Inaccessible host: `XXXXXXXXXX. This service may not be available in the `XXXXXXXXXX' region.
    at Request.ENOTFOUND_ERROR (/usr/src/app/node_modules/aws-sdk/lib/event_listeners.js:495:46)
    at Request.callListeners (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/src/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/src/app/node_modules/aws-sdk/lib/request.js:683:14)
    at ClientRequest.error (/usr/src/app/node_modules/aws-sdk/lib/event_listeners.js:333:22)
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/aws-sdk/lib/http/node.js:96:19)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20) {
  code: 'UnknownEndpoint',
  region: 'XXXXXXXXXX',
  hostname: 'XXXXXXXXXX',
  retryable: true,
  originalError: Error: getaddrinfo ENOTFOUND the-best-bucket-2020.s3.eu
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
    errno: 'ENOTFOUND',
    code: 'NetworkingError',
    syscall: 'getaddrinfo',
    hostname: 'XXXXXXXXXX',
    region: 'XXXXXXXXXX',
    retryable: true,
    time: 2020-05-28T14:43:53.421Z
  },
  time: 2020-05-28T14:43:53.421Z
}
/usr/src/app/node_modules/aws-sdk/lib/request.js:31
            throw err;

**SDK version number**
v2.685.0

* For browsers, the SDK version number is in the script tag <pre>src=".../aws-sdk-<b>2.466.0</b>.min.js"</pre>

* For Node.js, get SDK version by
  * running command `npm list aws-sdk` from your root directory
  * printing the output of `console.log(AWS.VERSION)` in your code where `AWS = require("aws-sdk");`
  * if running on Lambda and using SDK provided by Lambda runtime, you can find the SDK versions [here](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) 

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

  s3.upload(params, (err, data) => {
          if (err) {
            console.log(err);
            throw err;
          }
          console.log('Upload Complete', data);
        });
      } catch (error) {
        throw error;
      }

**Expected behavior**

The required data is uploaded to the designated s3 bucket

**Screenshots**

Due to the nature of the data and ownership of the code screens shots can not be provided.

**Additional context**

Issue only occurred when SDK was updated

**Comment by weisisheng** [comment] 2020-05-29 04:06
This also occurs on a previously good working app when trying to push a new api using amplify.

**Comment by weisisheng** [comment] 2020-05-31 05:31
FWIW, switching from expressvpn to google outline cleared up my problem.  No explanation however.

**Comment by philipwigg** [comment] 2020-06-02 21:59
On the surface, this would seem to be a DNS resolution error.

It's not possible to troubleshoot this without a reproducible test case.

**Comment by ajredniwja** [comment] 2020-06-02 22:08
@weisisheng, thank-you for reaching out to us with your issue, I was not able to reproduce the case, and I am not really sure how changing your VPN might effect that but I am certain that this wont be classified as a bug with the SDK. 

I agree with @philipwigg.

I would like to close this issue now, please reach out if you have any further questions.

**Closed by ajredniwja** 2020-06-02 22:08 UTC
Labels: bug, needs-triage

**Comment by DeepCFoxXx** [comment] 2020-06-03 12:50
No Problem At All. 

I appreciate your time.

I have overhauled the project in question and done a fresh install of the SDK (which stays at the current latest version no. ) and the problem seems to have been fixed. 

Apologies for not providing adequate test case data (its due to code ownership issues)

Thank you for your time its much appreciated.
