### ISSUE TITLE
#2506 still persists

### ISSUE THREAD

**Issue by kevinresol** [aws/aws-sdk-js#3061] opened 2020-01-22 02:53 UTC
This is per the request in https://github.com/aws/aws-sdk-js/issues/2506#issuecomment-576980864

**Comment by ajredniwja** [comment] 2020-01-22 03:02
Hey @kevinresol thank-you for reaching out.

Can you please fill out out the issue template found [here](https://github.com/aws/aws-sdk-js/issues/new?assignees=&labels=bug+report&template=---bug-report.md&title=).

**Comment by kevinresol** [comment] 2020-01-22 03:18
@ajredniwja please refer to the original details: https://github.com/aws/aws-sdk-js/issues/2506#issue-404477215

**Comment by ajredniwja** [comment] 2020-01-22 03:22
@kevinresol I have looked at them and some of the information is outdated. Like the SDK versions or react native version. The issue may be related to your particular use case as well. That is why it would be easier to solve your issue if I can have those details asked in the issue template.

**Comment by ajredniwja** [comment] 2020-01-23 00:39
Hey @kevinresol the issue here doesn't come from the SDK but react native where the allocated memory is not sufficient to process your files which happens after you add SDK, at that point you can only manually configure to increase the memory which you have already provided how to do. 

It might be appropriate to open the issue at react-native gitHub repo found [here](https://github.com/facebook/react-native/issues). 

If you are trying to only use AWS service with react native, you might be interested in AWS Amplify, which provides a set of libraries, UI components and a command line interface to build mobile backends and integrate with your React Native apps. More information found [here.](https://aws-amplify.github.io/docs/js/start?ref=amplify-rn-btn&platform=react-native)

Since this is not a bug with the JS-SDK, I will go ahead and close the issue.

**Closed by ajredniwja** 2020-01-23 00:39 UTC
Labels: 3rd-party, bug report
