### ISSUE TITLE
Are `scripts` & `dist-tools` required in the published package?

### ISSUE THREAD

**Issue by G-Rath** [aws/aws-sdk-js#3159] opened 2020-03-18 01:38 UTC
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers

**Describe the question**

I submitted a [PR](#2967) to add `.vscode` & `.eslintignore` to the `.npmignore` since they're not needed in the package.

I suspect that the `scripts` & `dist-tools` folders don't need to be published as well, but don't know the package well enough to make a PR.

These folders together take up about ~100kb on disk - while that might not seem like a lot, it adds up pretty quickly if you consider that's there for every release, which is stored in multiple caches which are accessed by CIs doing automatic builds that are triggered who knows how many times a minute; not to mention AWS itself has this package baked into its infrastructure countless times over, so it adds up to a decent savings for something that costs nothing :)

**Comment by ajredniwja** [comment] 2020-03-19 19:46
Hey @G-Rath, thank-you for reaching out and bringing this up, 

`scripts` is used by some of the internal customers and `dist-tools` is used for browser tests.

That being said I think that `dist-tools` can be removed from the package but not sure about the customer impact for `scripts`. You can submit a similar PR and I can have more inputs from the team.

Marking it as a feature request. Please reach out if you have any additional questions.

**Comment by G-Rath** [comment] 2020-03-19 19:54
Awesome, thanks for the response. I'll make two PRs so they don't block each other :)

**Comment by matthopson** [comment] 2020-03-23 16:24
We're seeing build failures this morning in CircleCI while running cypress tests with the following error:
```
Error: Cannot find module './dist-tools/transform.js' from '/home/app/node_modules/aws-sdk'
```

Are we sure it was safe to remove that, or are is this potentially something we are doing wrong on our end?

**Comment by AllanFly120** [comment] 2020-03-23 19:42
Hey @matthopson Can you find how `./dist-tools/transform.js` is imported to your project? `dist-tools` folder contains tools we use to manage our release, it shouldn't be consumed directly.

**Comment by matthopson** [comment] 2020-03-23 21:19
@AllanFly120 Yeah, I was trying to work that out. We downgraded the previous version and the problem went away. There is at least one other case I'd seen on SO (posted this morning). 

The first place that jumps out to me is here: https://github.com/aws/aws-sdk-js/blob/2f5261f46eb95a33ddb72ba27a6f7304e4f9ded9/package.json#L62

Given the following error (more context than what I originally posted):

```
The error was:

Error: Cannot find module './dist-tools/transform.js' from '/home/app/node_modules/aws-sdk'

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.
```

**Comment by AllanFly120** [comment] 2020-03-23 21:37
@matthopson Good catch I see where the problem is. Will fix it shortly!

**Comment by ajredniwja** [comment] 2020-03-23 21:55
@matthopson fixed in #3178

**Comment by ajredniwja** [comment] 2020-03-23 21:55
@G-Rath as observed, this will be a breaking change for many customers, hence would like to close this.

**Closed** 2020-03-23 21:55 UTC
Labels: feature-request

**Comment by G-Rath** [comment] 2020-03-23 22:01
@ajkerr fair enough, but you can still exclude `dist-tools/tests`.
