### ISSUE TITLE
Direct upload to Amazon S3: Corrupted files !

### ISSUE THREAD

**Issue by billyshena** [aws/aws-sdk-js#547] opened 2015-03-26 08:17 UTC
Hello everyone !

I'm currently trying to setup a direct upload from angular-file-upload to Amazon S3 bucket.
The upload process works fine, ex: If I upload an image of 3MB, the image is correctly transferred on my Amazon S3 bucket (located in Francfort btw, using the new AWS V4 signature)

The issue is the following one: The uploaded files cannot be opened and when I try to "cat" to see the binary content of the file, there are 3 lines added:

------WebKitFormBoundaryfOtaE6TQBF0hzBnw
Content-Disposition: form-data; name="file"; filename="01_-_Rock_Or_Bust.mp3"
Content-Type: audio/mp3

For each uploaded file, there is this "webkitformboundary" stuff added inside my file's binary content which is the reason of my issue I guess.

Does anyone know how to solve it?

I have a Node.js server that is basically generating pre-signed url and my app using this plugin to do the upload to S3.

I've been looking to solve this with my team for 24 hours now but no clue at moment.
Any ideas?

Best regards,

**Comment by AdityaManohar** [comment] 2015-03-26 08:39
This usually occurs because you are serializing the entire form when you post to your signed URL.

Instead of serializing your form you will need to supply the `File` object from the form control as the data to your asynchronous request.

Form control:
```html
<input type="file" id="upload"/>
```
Uploading your file:
```javascript
var upload = document.getElementById('upload');
var file = upload.files[0];

// Assuming jQuery
$.ajax({
  type: 'PUT',
  url: signedUrl,
  data: file,
  success: callback
});
```
Let me know if this helps.

**Comment by billyshena** [comment] 2015-03-26 08:48
Hi Aditya ! Thanks for your quick answer.
Well, this is how my Ajax request looks like:

![capture d ecran 2015-03-26 a 09 46 46](https://cloud.githubusercontent.com/assets/6057397/6842872/22264034-d39d-11e4-8c4b-0689668bea5f.png)
![capture d ecran 2015-03-26 a 09 46 33](https://cloud.githubusercontent.com/assets/6057397/6842871/2223f0a4-d39d-11e4-89ef-01dc11c3faf7.png)
![capture d ecran 2015-03-26 a 09 46 55](https://cloud.githubusercontent.com/assets/6057397/6842873/2226ddd2-d39d-11e4-9698-e55c582cae06.png)

**Comment by AdityaManohar** [comment] 2015-03-26 08:54
Like I mentioned earlier, this does look like your are serializing the entire form. Instead of posting the entire form to the signed URL, you will have to upload only the file object asynchronously to the signed URL.

**Comment by billyshena** [comment] 2015-03-26 11:39
Hi, your example is working like a charm with a simple <input type=file> and the file is not corrupted anymore after being uploaded to Amazon S3.

However, I've tried to use some angular plugins to handle the upload for me https://github.com/nervgh/angular-file-upload but this is not working (I have to do something with transformRequest?). If I use any kind of plugin => the file is still corrupted. I'm sending the same parameters as the working sample u provided.

**Comment by AdityaManohar** [comment] 2015-03-27 01:24
I'm not certain about the details of how this plugin works. I would recommend opening an issue with the maintainer of that plugin to help debug any issues with the plugin.

**Comment by lsegal** [comment] 2015-03-27 09:06
Marking this as closed since this is not an issue with the SDK. @billyshena the plugin you referenced is posting [form data](https://github.com/nervgh/angular-file-upload/blob/master/src/module.js#L443), which is simply not compatible with a binary upload to S3. You do not want to post the entire form, which uploads per the [HTTP spec as multipart/form-data](http://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.2), but instead need to upload *only* the file portion as @AdityaManohar pointed out.

I don't know enough whether this is possible or not using the plugin you referenced, but if it is not, you will not be able to use that specific plugin. Again, this is not a compatibility issue with the SDK-- the behavior happens because you are uploading the entire form instead of a single element. There might be other plugins that can work for you, but you might also consider simply not using a plugin for this at all, as the code provided above is very simple to use.

**Closed by lsegal** 2015-03-27 09:06 UTC

**Comment by guumaster** [comment] 2015-10-07 14:56
I wrote [this simple gist](https://gist.github.com/guumaster/9f18204aca2bd6c71a24) with a working example to upload a file with an $.ajax() call.

**Comment by tsdmrfth** [comment] 2019-06-12 21:17
I have same issue. I am trying to upload user documents to s3 with signed url. How can i send document files without sending it as FormData?

**Comment by trivikr** [comment] 2019-06-12 21:31
Locking this thread as the issue is old, and resolved.
Please open a [new issue](https://github.com/aws/aws-sdk-js/issues/new/choose) for related bugs and link to relevant comments in this thread.
