### ISSUE TITLE
s3.upload in Docker container in VPC very slow starting from version v2.575

### ISSUE THREAD

**Issue by wdittmer-mp** [aws/aws-sdk-js#3223] opened 2020-04-22 14:53 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When we updated our NodeJS services to use the latest (2.660) aws-sdk version, s3 uploads from a docker container inside a VPC (with S3 endpoint) became very slow (around 4 secs).
I wrote a small test program running inside a docker container and then it turns out up till and including 2.574 is still fast, but starting from v2.575 it becomes slow.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No, this is a simple nodejs process in a docker container, inside a VPC.

**Details of the browser/Node.js version**
v12.16.2

**SDK version number**
still fast up until including: v2.574
slow starting from: v2.575

**To Reproduce (observed behavior)**
To reproduce this, I started a shell container in our Kubernetes cluster hosted in a VPC.
From this I added the following files and installed nodejs etc.

app.js
---
> 'use strict';
> 
> const s3 = require('./s3');
> 
> async function main() {
> 
>     const someObject = {
>         id: 'testId1',
>         key: 'value1',
>         key2: 'looooooooooooooooooooooooooooooooooooooooonger value',
>     }
> 
>     const start = process.hrtime();
> 
>     for (let i=0; i < 100; i++) {
>         console.log(`Run ${i}`)
>         await s3.saveObjectInS3(someObject, 'TEST_WRD');
>     }
> 
>     const duration = process.hrtime(start);
>     console.log(`Uploading took ${duration} ms`);
> }
> 
> main();

---
s3.js

> 'use strict';
> 
> const AWS = require('aws-sdk');
> AWS.config.logger = console;
> 
> const awsAccessKeyId = process.env.AWS_ACCESS_KEY_ID;
> const awsSecretAccessKey = process.env.AWS_SECRET_ACCESS_KEY;
> const awsRegion = process.env.AWS_DEFAULT_REGION || 'eu-west-1';
> const awsBucketName = 'YOUR_BUCKET_NAME';
> 
> const s3Options = {
>         accessKeyId: awsAccessKeyId,
>         secretAccessKey: awsSecretAccessKey,
>         region: awsRegion,
>         s3ForcePathStyle: true,
>     };
> 
> const s3Client = new AWS.S3(s3Options);
> 
> async function saveObjectInS3(someObject, location) {
>     const bufferedObject = Buffer.from(JSON.stringify(someObject));
>     const params = {
>         Bucket: awsBucketName,
>         Key: getObjectFileKey(someObject.id, location),
>         Body: bufferedObject,
>         ContentType: 'application/json',
>     };
> 
>     try {
>         await s3Client.upload(params).promise();
>         console.log(`Object '${someObject.id}' saved to '${location}'`);
>     } catch (err) {
>         throw new Error(`Something went wrong: ${err.message}`);
>     }
> }
> 
> function getObjectFileKey(objectId, location) {
>     return location + objectId + '.json';
> }
> 
> module.exports = {
>     saveObjectInS3,
> }

package.json

> {
>   "name": "s3testnew",
>   "version": "1.0.0",
>   "description": "Test latest aws-sdk",
>   "main": "app.js",
>   "scripts": {
>     "test": "echo \"Error: no test specified\" && exit 1"
>   },
>   "dependencies": {
>     "aws-sdk": "^2.575.0"
>   },
>   "author": "",
>   "license": "ISC"
> }

**Expected behavior**
In version 2.574 the upload times are in the order of 110ms, after version 2.575, the upload times are in the order of 4 seconds.

**Screenshots**
Output (truncated) when I run above with 2.574:
-- aws-sdk@2.574.0 

> $ node app.js 
> Run 0
> [AWS s3 200 0.076s 0 retries] putObject({
>   Body: <Buffer 7b 22 69 64 22 3a 22 74 65 73 74 49 64 31 22 2c 22 6b 65 79 22 3a 22 76 61 6c 75 65 31 22 2c 22 6b 65 79 32 22 3a 22 6c 6f 6f 6f 6f 6f 6f 6f 6f 6f 6f ... 43 more bytes>,
>   Bucket: 'YOUR_BUCKET_NAME',
>   Key: 'TEST_WRDtestId1.json',
>   ContentType: 'application/json'
> })
> Object 'testId1' saved to 'TEST_WRD'
> Run 1
> [AWS s3 200 0.049s 0 retries] putObject({
>   Body: <Buffer 7b 22 69 64 22 3a 22 74 65 73 74 49 64 31 22 2c 22 6b 65 79 22 3a 22 76 61 6c 75 65 31 22 2c 22 6b 65 79 32 22 3a 22 6c 6f 6f 6f 6f 6f 6f 6f 6f 6f 6f ... 43 more bytes>,
>   Bucket: 'YOUR_BUCKET_NAME',
>   Key: 'TEST_WRDtestId1.json',
>   ContentType: 'application/json'
> })
> ....
> Run 98
> [AWS s3 200 0.038s 0 retries] putObject({
>   Body: <Buffer 7b 22 69 64 22 3a 22 74 65 73 74 49 64 31 22 2c 22 6b 65 79 22 3a 22 76 61 6c 75 65 31 22 2c 22 6b 65 79 32 22 3a 22 6c 6f 6f 6f 6f 6f 6f 6f 6f 6f 6f ... 43 more bytes>,
>   Bucket: 'YOUR_BUCKET_NAME',
>   Key: 'TEST_WRDtestId1.json',
>   ContentType: 'application/json'
> })
> Object 'testId1' saved to 'TEST_WRD'
> Run 99
> [AWS s3 200 0.025s 0 retries] putObject({
>   Body: <Buffer 7b 22 69 64 22 3a 22 74 65 73 74 49 64 31 22 2c 22 6b 65 79 22 3a 22 76 61 6c 75 65 31 22 2c 22 6b 65 79 32 22 3a 22 6c 6f 6f 6f 6f 6f 6f 6f 6f 6f 6f ... 43 more bytes>,
>   Bucket: 'YOUR_BUCKET_NAME',
>   Key: 'TEST_WRDtestId1.json',
>   ContentType: 'application/json'
> })
> Object 'testId1' saved to 'TEST_WRD'
> Uploading took 5,12850540 ms

Note the 'ms' is a bit misleading here. it took 5 seconds.

Then I remove node_modules and package-lock.json. Update to 2.575 and run npm install.

-- aws-sdk@2.575.0 

> $ node app.js 
> Run 0
> [AWS s3 200 4.314s 0 retries] putObject({
>   Body: <Buffer 7b 22 69 64 22 3a 22 74 65 73 74 49 64 31 22 2c 22 6b 65 79 22 3a 22 76 61 6c 75 65 31 22 2c 22 6b 65 79 32 22 3a 22 6c 6f 6f 6f 6f 6f 6f 6f 6f 6f 6f ... 43 more bytes>,
>   Bucket: 'YOUR_BUCKET_NAME',
>   Key: 'TEST_WRDtestId1.json',
>   ContentType: 'application/json'
> })
> Object 'testId1' saved to 'TEST_WRD'
> Run 1
> [AWS s3 200 4.476s 0 retries] putObject({
>   Body: <Buffer 7b 22 69 64 22 3a 22 74 65 73 74 49 64 31 22 2c 22 6b 65 79 22 3a 22 76 61 6c 75 65 31 22 2c 22 6b 65 79 32 22 3a 22 6c 6f 6f 6f 6f 6f 6f 6f 6f 6f 6f ... 43 more bytes>,
>   Bucket: 'YOUR_BUCKET_NAME',
>   Key: 'TEST_WRDtestId1.json',
>   ContentType: 'application/json'
> })
> ...
> Run 98
> [AWS s3 200 4.467s 0 retries] putObject({
>   Body: <Buffer 7b 22 69 64 22 3a 22 74 65 73 74 49 64 31 22 2c 22 6b 65 79 22 3a 22 76 61 6c 75 65 31 22 2c 22 6b 65 79 32 22 3a 22 6c 6f 6f 6f 6f 6f 6f 6f 6f 6f 6f ... 43 more bytes>,
>   Bucket: 'YOUR_BUCKET_NAME',
>   Key: 'TEST_WRDtestId1.json',
>   ContentType: 'application/json'
> })
> Object 'testId1' saved to 'TEST_WRD'
> Run 99
> [AWS s3 200 4.251s 0 retries] putObject({
>   Body: <Buffer 7b 22 69 64 22 3a 22 74 65 73 74 49 64 31 22 2c 22 6b 65 79 22 3a 22 76 61 6c 75 65 31 22 2c 22 6b 65 79 32 22 3a 22 6c 6f 6f 6f 6f 6f 6f 6f 6f 6f 6f ... 43 more bytes>,
>   Bucket: 'YOUR_BUCKET_NAME',
>   Key: 'TEST_WRDtestId1.json',
>   ContentType: 'application/json'
> })
> Object 'testId1' saved to 'TEST_WRD'
> Uploading took 443,811773965 ms

Note that the 'ms' is a bit misleading. It took 443 seconds.

**Additional context**
The bucket is a normal bucket, nothing special to it.

Please let me know if I can provide you with additional information, because I can understand that it can be hard to reproduce. If I run the nodejs code on a mac, it is fast no matter which version (Uploading took 11,4945153 ms). Only if I run it inside the VPC (node is m5.large | eu-west-1b) it becomes slow.

**Comment by wdittmer-mp** [comment] 2020-05-04 15:08
Possibly related to #3005

> My buddy find out that the problem occurred since version 2.575.0

**Comment by ajredniwja** [comment] 2020-05-12 22:29
@wdittmer-mp this wont be related to the SDK as it didn't make any major changes after or in v2.576, I have reached out to the service team and update once I hear back from them. 

Also would like to track this with #3005

Closing this for now, can reopen if the root cause is different for both. 

Please leave comment if you would want anything differently, I'd happy to keep this one open too to update you on this issue if you prefer that.

**Closed by ajredniwja** 2020-05-12 22:29 UTC
Labels: bug, needs-triage

**Comment by wdittmer-mp** [comment] 2020-05-13 07:02
@ajredniwja Thanks for your feedback.
Just to be sure, the changes occurred between 2.574 and 2.575 not 2.576.

I tried to check the changes, and indeed I couldn't easily find anything between 2.574 and 2.575 that could indicate what happens.

If it is not related to the SDK, what else could be influenced when the only change is switching from 2.574 to 2.575? Perhaps a package dependency was updated or a newer API version used? Just curious what your thoughts are.

I will watch/track #3005 and hopefully that points out what the root cause is for both or issues.

**Comment by ajredniwja** [comment] 2020-05-13 08:44
> @ajredniwja Thanks for your feedback.
> Just to be sure, the changes occurred between 2.574 and 2.575 not 2.576.

Yes, I meant 2.575.
The SDK wont be responsible for how the service side will handle things, I think this may be related to the new logics in the backend but can not really comment until I don't hear back from them.
