### ISSUE TITLE
S3 CopyObject fails with SignatureDoesNotMatch when using uppercase metadata

### ISSUE THREAD

**Issue by lallinger-arbeit** [aws/aws-sdk-js#3458] opened 2020-09-22 14:23 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Adding a custom metadata field with an uppercase letter works the first time, trying to change it using headObject and copyObject fails with SignatureDoesNotMatch

**Is the issue in the browser/Node.js?**
Browser/Node.js

Did not test it.

**If on Node.js, are you running this on AWS Lambda?**
Happens with and without Node.js, did not run it in AWS Lambda.

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`

**SDK version number**
v2.755.0

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code or minimal repo)

How to reproduce can be found [here](https://github.com/minio/minio/issues/10488). Even though i created the orignal issue for minio harshavardhana from the team did test it with direct AWS S3 access, [see here](https://github.com/minio/minio/issues/10488#issuecomment-696465228)

**Expected behavior**

Both copyObject calls should succeed.

**Screenshots**

**Additional context**

**Comment by ajredniwja** [comment] 2020-09-25 07:03
Hey @lallinger-arbeit thanks for opening this issue, as pointed out by you, I narrowed it down to the `parentID` as well. 
Its a bit tricky, so:
 
Scenario 1: If the object doesn't have any metadata and you run your code it should work fine. Just running it once. 

Scenario 2: If the object you run `headBucket` on the object that has metadata(same as you are defining in your `fullArray`), the `copyObject` function wont run successfully that is because it will have two `parentids` something like :
 ```
{
  uuid: 'cf493d7c-6c0c-4991-b259-9bfe8700ea86',
  id1: 'Test',
  parentid: 'none',
  parentID: 'none'
}
```

Now that runs all fine for the first scenario because `parentID` that you pass to `copyObject` actually gets converted to lower case as mentioned [here](https://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html#RESTAuthenticationConstructingCanonicalizedAmzHeaders). 
But running the same code on same object will make the object look like something I mentioned above. 

To avoid this, the best practice would be to use lower case fields i.e `parentid`

While this might be frustrating, I think it is not a bug but how you implement it in your code. 

Would like to close this issue now, please reach out if you have any other questions.

**Closed by ajredniwja** 2020-09-25 07:03 UTC
Labels: bug, needs-triage

**Comment by lallinger-arbeit** [comment] 2020-09-28 06:30
Hey @ajredniwja

> To avoid this, the best practice would be to use lower case fields i.e `parentid`

i already figured you can easily avoid this by just using lowercase metadata, but i think the error shouldn't happen.

> Now that runs all fine for the first scenario because `parentID` that you pass to `copyObject` actually gets converted to lower case as mentioned [here](https://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html#RESTAuthenticationConstructingCanonicalizedAmzHeaders).

As stated in your link, this should not be a issue because like it says in point 3 there: 

> Combine header fields with the same name into one

As far as i understand this this would in this case result in this header to be signed:
```
'x-amz-meta-parentid: none,none' 
```
And if the client and the server use the same procedure to sign, this should work..


> While this might be frustrating, I think it is not a bug but how you implement it in your code.
> 
> Would like to close this issue now, please reach out if you have any other questions.

If you say this is a none issue, i'm fine with it too, because the workaround is trivial.
