### ISSUE TITLE
Problems using ComprehenMEdical

### ISSUE THREAD

**Issue by wedwin53** [aws/aws-sdk-js#2417] opened 2018-12-10 20:54 UTC
I am having problems using the ComprehendMedical API, when making the requests I always get the same error, change the authentication way by Cognito and keep giving me problems, I also use the same credentials for the Comprehend API and it works without problems. I hope you can help me.

Error: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

**Comment by srchase** [comment] 2018-12-10 21:01
@wedwin53 

Can you provide a code samples and details on how you are getting this error?

Which version of the SDK?  What environment?

**Comment by wedwin53** [comment] 2018-12-10 21:10
Thanks, 
I'm Using Reactjs
 
"aws-sdk": "2.368.0",
"react": "16.6.0"


`
 getTextAnalysisCM(textToAnalyze){

    AWS.config.region = 'us-west-2'; 
    AWS.config.credentials = new AWS.CognitoIdentityCredentials({
      IdentityPoolId: 'IDENTITY-POOL-ID'
    });

 
    let entAnalysisCM = new Promise(function (successCallback, errorCallback) {
      var params = {
           Text: textToAnalyze
         }
      var comprehendMed = new AWS.ComprehendMedical();
 
      comprehendMed.detectEntities(params, function (error, data) {
          if (error) {
              errorCallback(error)
          } else {
              console.log('comprehendMedical: ' + JSON.stringify(data))
              successCallback(data)
          }
      }); // End detectEntities
 
    }); // End promise entAnalysis

  return entAnalysisCM

  }
`
When giving me error this option, also test placing the parameters in the constructor and also gives me error

**Comment by srchase** [comment] 2018-12-10 22:40
@wedwin53 

How did you include the SDK in your React app?

The default browser build does not include ComprehendMedical because that service does offer CORS Support.

**Comment by wedwin53** [comment] 2018-12-11 01:15
I include the SDK like that:

`import AWS from 'aws-sdk/dist/aws-sdk-react-native';`

**Comment by srchase** [comment] 2018-12-14 19:20
@wedwin53 

Is this a react-native app?  Or a normal react app for use in the browser?

**Comment by srchase** [comment] 2018-12-14 21:49
Comprehend does work with CORS, we've enabled that with this change: https://github.com/aws/aws-sdk-js/pull/2427.  You'll be able to use it with the standard build once that is released.

ComprehendMedical does not currently work in the browser.  You should be getting a CORS error.

**Comment by srchase** [comment] 2018-12-14 21:56
Closing this as a duplicate of this request: https://github.com/aws/aws-sdk-js/issues/2408

**Comment by cnusrini** [comment] 2019-06-15 12:33
I am getting the same error as the above.Can someone help me there please ?

**Comment by trivikr** [comment] 2019-06-18 21:45
Locking this thread as the issue was resolved, and has been inactive.
Please open a [new issue](https://github.com/aws/aws-sdk-js/issues/new/choose) for related bugs and link to relevant comments in this thread.

**Closed by trivikr** 2019-06-18 21:46 UTC
Labels: guidance
