### ISSUE TITLE
Using Media Store Data SDK raises an UnknownEndpoint error, regardless of region.

### ISSUE THREAD

**Issue by lreher** [aws/aws-sdk-js#3503] opened 2020-10-19 02:10 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I'm trying to use the MediaStoreData module in the AWS SDK, however I'm running into a

```
UnknownEndpoint: Inaccessible host: `data.mediastore.ap-southeast-2.amazonaws.com'. This service may not be available in the `ap-southeast-2' region.
```
I've tried multiple regions and still cant use the endpoint. I'm simply trying to retrieve an object from MediaStore.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No 

**Details of the browser/Node.js version**
v12.16.3

**SDK version number**
^2.773.0

**To Reproduce (observed behavior)**
Require MediaStore data using your credentials:

```
var AWS = require("aws-sdk");
var mediaStoreData = new AWS.MediaStoreData();
```
And call getObject(params, callback)

**Expected behavior**
To retrieve the requested object in MediaStore.

**Comment by ajredniwja** [comment] 2020-10-20 02:30
Hey @lreher thanks for opening this, I was able to reproduce this using the code how ever I believe that is happening because the API is not able to hit the correct endpoint. This might be a usage issue since notice in the following endpoints there is `aaabbbcccdddee` which is added in the data endpoint (retrieved from the console) but if that particular information is not provided to the API call the call fails hence the workaround/solution here would be to the use path and the endpoint together: 

CLI example: 
```
aws mediastore-data get-object \
    --endpoint https://aaabbbcccdddee.data.mediastore.us-west-2.amazonaws.com \
    --path events/baseball/setup.jpg setup.jpg
```

JS example: 
```
var mediastoredata = new AWS.MediaStoreData({region: 'us-west-2', endpoint: 'https://aaabbbcccdddee.data.mediastore.us-west-2.amazonaws.com'});

var params = {
    Path: 'events/baseball/setup.jpg',
};

mediastoredata.getObject(params, function(err, data) {
    if (err) console.log(err, err.stack); // an error occurred
    else     console.log(data);           // successful response
});
```

Closing this issue now, please reach out if you have any other questions.

**Closed by ajredniwja** 2020-10-20 02:30 UTC
Labels: bug, needs-triage

**Comment by lreher** [comment] 2020-10-20 02:35
Thanks for that! I didn't realise you can specify the endpoint.

**Comment by ajredniwja** [comment] 2020-10-20 02:37
Not a problem, this may help someone in future too.
