### ISSUE TITLE
Pinpoint SMS Message with URL Isn't Actually Sent(Received by phone)

### ISSUE THREAD

**Issue by mjmostachetti** [aws/aws-sdk-js#4334] opened 2023-02-03 22:36 UTC
### Describe the bug

I can send messages via the Pinpoint SMS without a problem if there is no https:// url in the text message. It even works just fine with a custom scheme(fakeScheme://). I'm trying to setup some deep linking messages on Android, which requires an https url, but these texts are not received by the phones. Is this expected? Am I missing something/configuration within pinpoint, or is this a bug?

### Expected Behavior

I can send text messages with valid https:// urls in the message and it be received by the phone.

### Current Behavior

I get this response, even though the message never gets to my phone.
```json
{
    "MessageResponse": {
        "ApplicationId": "34740ce3c47e44d2adc7bfbd7fa3a9b8",
        "RequestId": "145d4e31-0c93-4a69-a5b5-c27fbb477ef5",
        "Result": {
            "myvalidnumber": {
                "DeliveryStatus": "SUCCESSFUL",
                "MessageId": "q9r65afkslog0pbpk248c1tto0d89d5poq1hj5o0",
                "StatusCode": 200,
                "StatusMessage": "MessageId: q9r65afkslog0pbpk248c1tto0d89d5poq1hj5o0"
            }
        }
    }
}
```
### Reproduction Steps
```js
var message = "Hello, please go to this link - https://environment.fjasdfaklsjdfasd.amplifyapp.com/blah/blah";
 
 const params = {
      ApplicationId: applicationId,
      MessageRequest: {
        Addresses: {
          [phoneNumber]: {
            ChannelType: "SMS",
          },
        },
        MessageConfiguration: {
          SMSMessage: {
            Body: message,
            Keyword: registeredKeyword,
            MessageType: "TRANSACTIONAL",
            OriginationNumber: originationNumber,
            SenderId: senderId,
          },
        },
      },
    };

pinpoint.sendMessages(params, function (err, data) {
      if (err) {
        console.log(`ERROR : ${JSON.stringify(err)}`);
        reject(err);
      } else {
        console.log(`SUCCESS : ${JSON.stringify(data)}`);
        resolve();
      }
    });
```

### SDK version used

^2.1264.0

### Environment details (OS name and version, etc.)

Node AWS Lambda

**Comment by RanVaknin** [comment] 2023-02-03 23:36
Hi @mjmostachetti ,

While we try to reproduce this, can you please check out this troubleshooting guide? 
I would also check against a different phone on a different network, and check your spam folder for auto-screened calls.

Some carriers may block incoming messages with hyperlinks in them as a security measure against phishing attacks and marketing campaigns.

Thanks,
Ran~

**Comment by CayneBartoo** [comment] 2023-09-15 05:15
I am experiencing something similar, is this still an issue?

**Comment by mjmostachetti** [comment] 2023-09-15 05:17
We stopped trying this and resorted to sending emails with the url instead.

**Comment by mjmostachetti** [comment] 2023-10-12 17:41
@RanVaknin Do you have any documentation or info about this? How does AWS assign a phone number to send from in Pinpoint? It seems like there's an issue there. I just tried out a trial Twilio account, and I can send links through their API without any issues to my phone.

**Comment by RanVaknin** [comment] 2024-07-19 20:48
Hi there,

This is definitely not an SDK issue, since the entity that sends the SMS is the Pinpoint backend API.
The reason the messages with URL are not sent might be a reason with Pinpoint, or more likely with the network carrier receiving the message. 

From the docs:
>Don't use shortened URLs created from third-party URL shorteners, as these messages are more likely to be filtered as spam. If you want to use a shortened URL, use a 10LDC phone number or short code. Using either of these number types requires that you register your message template, which can then include a shortened URL in the message.

Carriers automatically profile and block suspicious senders on your behalf. Depending on your carrier, the type of virtual number, the content of your message you might be flagged and messages containing URLs might not appear (worth checking your phone's spam folder if one exists).

When you get the response back from sending the `SendMessages` API request, you can take the provided `RequestID` field, and file a support ticket to AWS internal support using the developer console. Those will end up with the Pinpoint team and they can investigate whether there's a specific issue with the contents of your request, or if the carrier is the one blocking the SMS message from being received. Also at least for the US, major carriers would let you see all the text messages your phone received and sent (not the contents, but the count and timeline) you might want to cross reference to see if the message actually makes it to the provider but perhaps blocked by your device. 

Since this is not an issue with the SDK, and not actionable by the SDK team, I'm going to close this issue.
Thanks,
Ran~

**Closed by RanVaknin** 2024-07-19 20:48 UTC
Labels: bug, p3

**Comment by mjmostachetti** [comment] 2024-07-19 21:56
Sounds good. We switched to twilio and haven’t had any problems since.
