### ISSUE TITLE
Content MD5 error when uploading to S3

### ISSUE THREAD

**Issue by mfdez97** [aws/aws-sdk-js#3600] opened 2021-01-13 12:05 UTC
- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When trying to upload a zip file to an S3 bucket the error "The Content-MD5 you specified did not match what we received" is thrown. I have checked the MD5 hash that is generated with the configuration "computeChecksums" set to true and it is correct, as well as the content length with the size of the buffer.
This seems to only happen when the file size is only smaller than 5mb, which is the max part size specified when configuring the S3 service. When the file is uploaded with a single putObject operation instead of being broken into chunks, the bad digest error is thrown. Currently, it seems that removing the "Content-Length" header works, but I do not understand how that is mitigating this issue.

**Is the issue in the browser/Node.js?**
Electron app

**Details of the browser/Node.js version**
Node.js 10.11.0 and Electron 4.2.12

**SDK version number**
2.824

**To Reproduce (observed behavior)**
```js
// Create zip archive with files
const archive = archiver.create("zip", { zlib: { level: Z_BEST_COMPRESSION } });
const fileReadStream = fs.createReadStream(file));
archive.append(fileReadStream, { name: file });

// Pipe archive into buffer
const chunks: Buffer[] = [];
let buf: Buffer;
archive.on("data", (chunk: Buffer) => {
    chunks.push(chunk);
})
archive.on("end", function(){
  buf = Buffer.concat(bufs);
}

// Upload stream to S3
const stream = createReadStream(buf);
const options = {
    partSize: 5 * 1024 * 1024
}
const params = {
    Key: uuid,
    ContentLength: buf.byteLength
    ContentType: "application/zip",
    ServerSideEncryption: "AES256",
    Bucket: bucket,
    Body: stream,
    Metadata: metadata
};
await s3.upload(params, options).promise();
```

**Expected behavior**
The zip file is uploaded to S3

**Additional context**
This zip file contains .log and .json files and it was being uploaded fine until recently. The error only happens when the file size is bigger than 5mb.

**Comment by mfdez97** [comment] 2021-01-13 12:06
I have also seen this comment which reports a very similar scenario https://github.com/aws/aws-sdk-js/issues/1879#issuecomment-466503902

**Comment by ajredniwja** [comment] 2021-01-15 00:16
Hey @mfdez97, thanks for opening this issue, I was not able to reproduce this issue when I ran it locally. 

Code I used: 

```javaScript
var AWS = require('aws-sdk');

var fs = require('fs');

var s3 = new AWS.S3({region: 'us-west-2'});
const stream = fs.createReadStream("/path/testFileToupload.zip");

const params = {
    Key: "xyz",
    ContentType: "application/zip",
    ServerSideEncryption: "AES256",
    Bucket: 'bucket-name',
    Body: stream,
    partSize: 5 * 1024 * 1024,
};
s3.upload(params, function(err, data){
    if (err){
        console.log(err)
    }
        console.log(data)
})
```

Can you try running the code to see the problem is not occurring because of the SDK.

**Comment by ajredniwja** [comment] 2021-02-03 05:12
I think it is a 400 Bad Request error then. You can check more about them here: https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

> have one more question though if you can clarify it. If the content length parameter is wrong, does S3 throw a bad digest error?


Closing this out now, please reach out if you have any other questions.

**Closed by ajredniwja** 2021-02-03 05:12 UTC
Labels: bug
