### ISSUE TITLE
IllegalLocationConstraintException when creating bucket

### ISSUE THREAD

**Issue by craigphume** [aws/aws-sdk-js#475] opened 2015-01-22 04:06 UTC
Hi

I am getting 
"IllegalLocationConstraintException: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to."
when trying to create a new bucket in any region except us-east-1 or eu-west-1

If I create in us-east-1 it works perfectly.

I followed the guide @ http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-examples.html as a test and it still wont work. I can create it in the S3 Console in the web portal.

Im trying to access ap-southeast-2 which is the Sydney DS

Thanks Craig

**Comment by lsegal** [comment] 2015-01-22 04:08
In order to create a bucket in `ap-southeast-2` you have to set you `region` configuration parameter to `ap-southeast-2` so that you are talking to the correct endpoint:

```js
var s3 = new AWS.S3({region: 'ap-southeast-2'});
s3.createBucket(...);
```

By default S3 defaults to `us-east-1`, which is why that works.

**Comment by craigphume** [comment] 2015-01-22 04:19
Thanks for the reply Isegal

I have tried that sorry

Snippet below

var s3bucket = new AWS.S3({params: {Bucket: 'itctestbucket', region: 'ap-southeast-2' }});
    s3bucket.createBucket(function (err) {
        if(err) {
            console.log('Error: ' + err);
            return callback(err, null);
        }
        var params = {Key: key, Body: body};
        s3bucket.upload(params).on('httpUploadProgress', function (evt) {
            console.log(evt);
        }).send(function (err, data) {
            console.log(err, data);
            return callback(null, true);
        });
    });

Using the aws command line tool on linux I can create buckets in ap-southeast-2 region

craighume@host:~
$ aws s3 mb s3://isegal-craig-test
make_bucket: s3://isegal-craig-test/

**Comment by lsegal** [comment] 2015-01-22 04:30
It looks like you put the `region` parameter inside the `params` hash rather than its own config option.

**Comment by craigphume** [comment] 2015-01-22 04:48
Oops you are correct, but it didn't fix anything.

I have tried setting 
`AWS.config.region = 'ap-southeast-2'` and `AWS.config.update({region:  'ap-southeast-2'  });`
Both to no avail.

This is a full script that I just did and it doesn't work with the 'ap-southeast-2' region either
```var AWS = require('aws-sdk');
AWS.config.region = 'ap-southeast-2';
AWS.config.update({
    accessKeyId: '<ID>',
    secretAccessKey: '<KEY>'
});
var s3bucket = new AWS.S3({
    params: {
        Bucket: 'itctestbucket'
    },
    region: 'ap-southeast-2'
});
s3bucket.createBucket(function (err) {
    if(err) {
        console.log('Error: ' + err);
    }
    var params = {Key: 'CRAIG', Body: 'HUME'};
});```

**Comment by craigphume** [comment] 2015-01-22 05:23
Update...

I build the same example from above in php/laravel4, got the same result until I added the key `'LocationConstraint' => 'ap-southeast-2'` to the create bucket array

```	$s3 = App::make('aws')->get('s3');
	$s3->createBucket(array('Bucket' => 'itctestbucket', 'LocationConstraint' => 'ap-southeast-2',));```

once I did this it created the bucket as expected.

Does the node code have this parameter, I added it to the to 
```var s3bucket = new AWS.S3({
    params: {
        Bucket: 'itctestbucket'
    },
    LocationConstraint: 'ap-southeast-2'
});```

But no change

**Comment by lsegal** [comment] 2015-01-22 05:34
I was unable to reproduce your issue with the JS SDK. I used the following with Node.js v0.10.35 and SDK v2.1.7.

```js
var AWS = require('aws-sdk');
var s3 = new AWS.S3({region: 'ap-southeast-2'});

s3.createBucket({Bucket:process.env.BUCKET}, function(err, data) {
  console.log(err, data)
});
```

Run:

```
$ BUCKET=my-ap-bucket node test
```

What version of the SDK and Node.js are you using?

**Comment by craigphume** [comment] 2015-01-22 05:42
Node is `v0.10.35`
aws-sdk is `aws-sdk@2.1.7`

I copied your script and it worked!?
Must be my code then.
Than you for your quick help, Craig

**Comment by lsegal** [comment] 2015-01-22 08:44
Glad you got it working! Marking this as closed since it seems like the SDK is doing the right thing.

**Closed by lsegal** 2015-01-22 08:44 UTC
Labels: Question
