### ISSUE TITLE
s3.upload is not a function

### ISSUE THREAD

**Issue by jeremythille** [aws/aws-sdk-js#3312] opened 2020-06-17 08:25 UTC
- [X] I've confirmed that I'm using latest version of SDK, and issue is still reproducible

I'm using aws-sdk version 2.697.0 for NodeJS, it should be the latest one, I installed it yesterday with `npm install aws-sdk --save`.
OS : Win10 x64
NodeJS : v13.11
Typescript v3.9.5

When I try to use `s3.upload(params)` the script crashes with an error `s3.upload is not a function`.

Minimum code to reproduce the issue (that's all that is left in my file, I commented out everything else) :

```
const AWS:any = require("aws-sdk");
const s3:any = new AWS.S3();

console.log(`typeof s3.upload = `);
console.log(typeof s3.upload); // undefined?? WHY

console.log(`typeof s3.putObject = `);
console.log(typeof s3.putObject); // function, and works
```

I have no idea why `s3.upload` is undefined. I ended up using `s3.putObject`, which is defined and works as expected.

I Googled it, and nobody else seems to have this issue. We tried to debug it with a friend developer, and we couldn't figure out what's going on here.

**Comment by ajredniwja** [comment] 2020-06-17 23:52
Hey @jeremythille thank-you for reaching out to us with your issue. 

Was not able to use `:any` syntax

used the code below:

```
const AWS = require("aws-sdk");
const s3 = new AWS.S3();

console.log(`typeof s3.upload = `);
console.log(typeof s3.upload); 

console.log(`typeof s3.putObject = `);
console.log(typeof s3.putObject);
```

Results: 

```
typeof s3.upload = 
function
typeof s3.putObject = 
function
```

Would you want to share your use case to let me help you better?

**Comment by jeremythille** [comment] 2020-06-18 05:55
Hi, thanks for your reply.

OK I'll try to give more context. The code I gave above (and pretty much nothing else, because I commented out everything else), from my NodeJS app, is in a file called `products.ts`.

```
// start of file
import { indexToImageName } from '../../utils';
import { resolve } from "path"
import { promisify } from "util"

const readfilePromise = promisify(readFile);

const AWS = require("aws-sdk");
const Bucket = "easyfoodrunner";

AWS.config.update({
	accessKeyId: process.env.s3_accessKeyId,
	secretAccessKey: process.env.s3_secretAccessKey,
	region: 'eu-west-3' 
});

const s3 = new AWS.S3();

console.log(`\ntypeof s3.upload = `);
console.log(typeof s3.upload);  // undefined?? WHY

console.log(`\ntypeof s3.putObject = `);
console.log(typeof s3.putObject);  // function, and works

/* --- COMMENTED EVERYTHING ELSE ---
	class Products {
		constructor(public req: Request, public res: Response) {
			// .......
		}
 
              // Other methods here

		async transferOneImageToS3(productId: string, imageIndex: number, isThumb: boolean = false): Promise<any> {
	
			const fileName = indexToImageName(productId, imageIndex, isThumb);
			const fullPath: string = resolve("./uploads/" + fileName);
	
			let fileContent = await readfilePromise(fullPath); // fs.readFile, but promisified
	
			// Setting up S3 upload parameters
			let params = {
				Bucket,
				Key: fileName, // File name you want to save as in S3
				Body: fileContent
			};
	
			s3.putObject(params, (err, data) => {
				if (err) {
					console.log(err);
				} else {
					console.log(`Upload success for file ${fullPath} - data = `, data);
				}
			});
		}
	}
	module.exports = (req: Request, res: Response) => new Products(req, res)
*/
// end of file
```

I import this file into my API like this :

`api["products"] = require("./products");`

Then I can call `api.products(req, res)` with a classic Express route.

Everything works with `putObject()`, my images are being uploaded correctly to S3.

The only problem is, if I try to use `s3.upload`, the script crashes saying `s3.upload is not a function`. 

Here's a screenshot of my logs :

![2020-06-18_074020](https://user-images.githubusercontent.com/3706912/84982515-317fd400-b137-11ea-94f7-91d40a4f21db.png)


Really, I don't get it.

**Comment by jmclean-cnexus** [comment] 2020-06-18 17:46
I cant reproduce:
```
Welcome to Node.js v12.14.1.
Type ".help" for more information.
> let AWS = require('aws-sdk')
undefined
> let s3 = new AWS.S3()
undefined
> console.log(typeof s3.upload);
function
```

**Comment by jeremythille** [comment] 2020-06-22 04:49
Hi, thanks for trying. Really, nobody else can reproduce it. My buddy developper neither, on his machine. We still have no idea why this is happening. But it is happening :)

**Comment by ajredniwja** [comment] 2020-06-24 23:24
It should not be related to windows, you can try using the CLI as well, I would also recommend try doing a fresh SDK install. 

Closing this issue now.

**Closed by ajredniwja** 2020-06-24 23:24 UTC
Labels: guidance
