### ISSUE TITLE
AWS sdk is not accepting parameters as mentioned in the document

### ISSUE THREAD

**Issue by shubham-sp444** [aws/aws-sdk-js#4561] opened 2023-12-27 08:56 UTC
### Describe the bug

SDK used:- https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RedshiftServerless.html#listEndpointAccess-property

getting an error saying Unexpected key 'ownerAccount' found in params, this is not working locally as well as calling from the lambda.
Property is also missing from the types.
<img width="470" alt="Screenshot 2023-12-27 at 2 26 17 PM" src="https://github.com/aws/aws-sdk-js/assets/33379213/8b4c56a5-6ceb-4358-bebb-8036472fdd72">

### Expected Behavior

It should accept the property as mentioned in the AWS document.

### Current Behavior

error: UnexpectedParameter: Unexpected key 'ownerAccount' found in params
at ParamValidator.fail (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:50:37)
at ParamValidator.validateStructure (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:78:14)
at ParamValidator.validateMember (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:89:21)
at ParamValidator.validate (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:34:10)
at Request.VALIDATE_PARAMETERS (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:166:42)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
at /var/runtime/node_modules/aws-sdk/lib/event_listeners.js:120:11
at finish (/var/runtime/node_modules/aws-sdk/lib/config.js:396:7)
at /var/runtime/node_modules/aws-sdk/lib/config.js:414:9 {
code: 'UnexpectedParameter',
time: 2023-12-26T13:22:29.456Z
},

### Reproduction Steps

Try to call the API:  https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RedshiftServerless.html#listEndpointAccess-property

and use the `ownerAccount` property

### SDK version used

V2 javascript

### Environment details (OS name and version, etc.)

I've used node 14 and 16 both , and currently running on MacOS Ventura 13.4 with Apple M1 Pro chip ( for local ).

**Comment by aBurmeseDev** [comment] 2024-01-03 20:09
Looks like this's duplicate of https://github.com/aws/aws-sdk-js/issues/4560. Please refer to that issue. Closing.

**Closed by aBurmeseDev** 2024-01-03 20:09 UTC
Labels: duplicate, bug

**Comment by shubham-sp444** [comment] 2024-01-04 05:54
> Looks like this's duplicate of #4560. Please refer to that issue. Closing.

Hello @aBurmeseDev , It has the same issue but it's a different SDK with the issue, Please keep it open until both SDKs are fixed.

**Comment by aBurmeseDev** [comment] 2024-01-04 08:10
@shubham-sp444 - Can you clarify which different SDK other than JavaScript seems to be having same issue? It looks like you opened two duplicate issue in same repo.

**Comment by shubham-sp444** [comment] 2024-01-05 11:30
> https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RedshiftServerless.html#listEndpointAccess-property

This issue is for [listEndpointAccess](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RedshiftServerless.html#listEndpointAccess-property)

while [another issue is](https://github.com/aws/aws-sdk-js/issues/4560) for [createEndpointAccess](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RedshiftServerless.html#createEndpointAccess-property).

Both refer to different SDKs
