### ISSUE TITLE
'FunctionError' property in lambda result is absent on IE

### ISSUE THREAD

**Issue by rstahl** [aws/aws-sdk-js#1113] opened 2016-08-26 01:59 UTC
I have a lambda function that creates and returns an error.  The calling client should receive a result with the FunctionError property set to 'Handled' and the Payload set to information about the error.  This works fine on all browsers except IE.  In IE, the FunctionError property is absent from the results. Note, I'm using the latest aws SDK (version 2.5.3) on the client.

**Comment by LiuJoyceC** [comment] 2016-08-26 02:33
Hi @rstahl 
Thanks for you question. What versions of IE are you using (and are you including Edge)? Can you share the relevant code snippet from your Lambda function? Which version of Node are you using in your Lambda function?

**Comment by rstahl** [comment] 2016-08-26 13:48
Hi,

Thanks for your response.  I am testing on  IE 11.0 running on Windows 8.0.  Under the developer tools section of the browser, there's an indication that the browser is running in 'Edge' mode (??).

Regarding the lambda function, I am using Nodejs 4.3 and here's a snippet of code that is equivalent to what I'm doing:
```
exports.handler = function(event, context, callback) {
    // detect and return some error
   var authErr = new Error('No OAuth tokens available');
   authErr.name = 'authError';
  callback(authErr);
}
```
I'm curious if this is yet another CORS-related issue with IE, since I believe the 'FunctionError' value is returned via a response header.

Thanks again.

**Comment by rstahl** [comment] 2016-08-30 15:36
Any update regarding this problem?

**Comment by rstahl** [comment] 2016-09-20 14:06
Hello?  We need resolution of this issue please.

**Comment by chrisradek** [comment] 2016-09-20 19:31
@rstahl 
I've reached out to the Lambda team to look into this issue. At first glance, it looks it could be a CORS issue, since the headers are returned, but not accessible through JavaScript.

I'll keep this thread updated when I hear back from Lambda.

**Comment by rstahl** [comment] 2016-12-22 21:35
Need an update on this please.. Has this been fixed in the latest released SDK?

**Comment by chrisradek** [comment] 2016-12-22 21:39
@rstahl 
The issue has been reported to Lambda but has not yet been fixed. There aren't any code changes to be made to the SDK, since the issue is on the service side. I know this issue is on their radar but I don't have an ETA on when it will be fixed.

**Comment by rstahl** [comment] 2016-12-22 21:42
So essentially users of the SDK have to create a workaround for IE.  Weird that this would not be a hight priority.

**Comment by rstahl** [comment] 2017-02-01 21:02
Please provide an update on this.  I was able to look at the actual HTTP responses, and it *does not* appear to be a lambda service issue.  The HTTP response contains the 'function error' header, but that header is not getting parsed out and returned via the SDK in IE--it is returned in Chrome.  I am using version 2.9.0 of the SDK.  Here's the HTTP response headers as shown in IE:

Access-Control-Allow-Origin:*
Access-Control-Expose-Headers:x-amzn-RequestId,x-amzn-ErrorType,x-amzn-ErrorMessage,Date
Access-Control-Expose-Headers:x-amzn-RequestId,x-amzn-ErrorType,x-amzn-ErrorMessage,x-amz-log-result,x-amz-function-error
Content-Type:application/json
Date:Wed, 01 Feb 2017 16:31:16 GMT
**X-Amz-Function-Error:Handled**
x-amzn-Remapped-Content-Length:0
x-amzn-RequestId:da45ef2b-e89b-11e6-bf3f-83d1d15e132b
Content-Length:207
Connection:keep-alive

Here's the response as shown in Chrome:

Access-Control-Allow-Origin:*
Access-Control-Expose-Headers:x-amzn-RequestId,x-amzn-ErrorType,x-amzn-ErrorMessage,Date
Access-Control-Expose-Headers:x-amzn-RequestId,x-amzn-ErrorType,x-amzn-ErrorMessage,x-amz-log-result,x-amz-function-error
Connection:keep-alive
Content-Length:213
Content-Type:application/json
Date:Wed, 01 Feb 2017 16:37:43 GMT
**X-Amz-Function-Error:Handled**
x-amzn-Remapped-Content-Length:0
x-amzn-RequestId:c0e3de27-e89c-11e6-b582-15221e551bf5

In both cases the **X-Amz-Function-Error** header is returned; however in the I.E case the SDK apparently does not parse it out correctly and return the 'FunctionError' property in the result object, whereas Chrome does.

**Comment by chrisradek** [comment] 2017-02-01 21:10
@rstahl 
The issue is caused by the way the headers are exposed via the Access-Control-Expose-Headers header. The developer tools from a browser will show all the headers received/sent, but the browser will only expose information about the response (i.e. headers) to the JavaScript run-time based on the Access-Control-* headers if the request was a cross-origin request.

We've seen that IE is more easily tripped up than other browsers when it comes to reading these headers.

I know the Lambda team is actively looking into this, I've requested an update on when they'll be able to make the fix.

**Comment by chrisradek** [comment] 2017-02-06 23:11
@rstahl 
I've been told by the Lambda team that they have resolved this issue. If you continue to see this error, please let me know what region you're testing in so I can forward that to the Lambda team for troubleshooting.

**Comment by chrisradek** [comment] 2017-04-18 16:45
Closing, let me know if you continue to see this issue.

**Closed by chrisradek** 2017-04-18 16:45 UTC
Labels: Service / API
