### ISSUE TITLE
TypeError: Attempting to change enumerable attribute of unconfigurable property with PhantomJS

### ISSUE THREAD

**Issue by sridharrajagopal** [aws/aws-sdk-js#1396] opened 2017-03-08 23:00 UTC
Hi, 

I'm trying to use AWS SDK for Javascript in a browser environment, but with PhantomJS. 

PhantomJS chokes with the following error stack with the aws-sdk-js

  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:40 in defineProperty
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:40 in error
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:37 in i
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:37 in n
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:37
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:39 in callListeners
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:39 in emit
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:38 in emitEvent
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:38 in e
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:40 in runTo
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:40
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:38
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:38
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:39 in callListeners
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:39 in i
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:37
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:36 in t
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:36
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:37 in get
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:36 in s
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:36 in getCredentials
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:37
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:39 in callListeners
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:39 in emit
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:38 in emitEvent
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:38 in e
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:40 in runTo
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:40
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:38
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:38
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:39 in callListeners
  https://sdk.amazonaws.com/js/aws-sdk-2.24.0.min.js:39 in i

I'm referencing the corresponding issue in phantomjs github - https://github.com/ariya/phantomjs/issues/13895

Any help is greatly appreciated!

Thanks,
Sridhar

**Comment by chrisradek** [comment] 2017-03-09 16:46
@sridharrajagopal 
What version of phantomJS are you using? Travis currently runs anytime a PR is submitted to this SDK, and one of the steps is running the browser sdk tests using phantomjs 2.1.14.

**Comment by sridharrajagopal** [comment] 2017-03-09 18:28
I'm running phantomjs 2.1.1
Can you tell me where I can find 2.1.14?

Thanks,
Sridhar

**Comment by sridharrajagopal** [comment] 2017-03-09 20:04
Here is such a call that phantomjs complains about - 

            // s3.upload({
            //     Key: "file.png",
            //     Body: buf,
            //     ACL: 'public-read',
            //     ContentType: 'image/png'
            // }, function(err, data) {
            //     if (err) {
            //         return alert('There was an error uploading your chart: ', err.message); 
            //     }
            //     alert('Successfully uploaded chart.');
            // });

The other one was a dynamodb query

Both of these work in a "regular" browser.

**Comment by sridharrajagopal** [comment] 2017-03-13 17:06
Btw, I checked that 2.1.14 from npm is indeed version 2.1.1 that I got directly from the phantomjs github.

**Comment by bla0815** [comment] 2017-03-31 20:11
Hi i had the same error message using the AWS browser SDK in  Apache Cordova, whenever i tried to invoke aws-lambda functions. Apparently it was due my restrictive Content-Security-Policy (albeit allowing for the aws-sdk), since i was able to get it running by using the wildcard (for development). 

I have yet to figure out, which domain is specifically needed for my lambda-invocations, so feedback is appreciated, but i wanted to get this out, because i never would have guessed the cause from the error message alone and maybe it's also the cause for OP's problem.

**Comment by sridharrajagopal** [comment] 2017-03-31 20:36
Any updates or feedback on this issue?

Much appreciated!
Thanks,
Sridhar

**Comment by sridharrajagopal** [comment] 2017-04-18 23:47
Any updates?

Thanks,
Sridhar

**Comment by sridharrajagopal** [comment] 2017-06-13 22:05
Any updates?

Thanks,
Sridhar

**Comment by 1c7** [comment] 2018-07-28 09:02
No updates?

Thanks 
Cheng

**Comment by srchase** [comment] 2018-10-03 21:35
@sridharrajagopal 

Is this still an outstanding issue?  Since you raised this issue, development on PhantomJS has stopped.

There are some more recent alternatives that would likely be a better fit for you long-term as they are being developed.

**Comment by sridharrajagopal** [comment] 2018-10-10 21:55
Yes, this is still an outstanding issue for me, though I haven't tried it again since I reported my issue above as it didn't work. 

I can look into alternatives for PhantomJS as you suggest.

**Comment by srchase** [comment] 2018-10-15 23:33
As PhantomJS is no longer supported, I'm going to close this issue.  Let us know if you have any issues using the SDK with the current alternatives.

**Closed by srchase** 2018-10-15 23:33 UTC
Labels: Question
