### ISSUE TITLE
RDS data API cannot handle insert enum

### ISSUE THREAD

**Issue by jakeleventhal** [aws/aws-sdk-js#4563] opened 2023-12-27 16:17 UTC
### Describe the bug

https://github.com/drizzle-team/drizzle-orm/issues/1073

### Expected Behavior

See issue

### Current Behavior

See issue

### Reproduction Steps

See issue

### SDK version used

3.450.0

### Environment details (OS name and version, etc.)

Node 18.17.1

**Comment by aBurmeseDev** [comment] 2024-01-10 00:33
Hi @jakeleventhal - thanks for reaching out. 

I'm not very familiar with [drizzle](https://github.com/drizzle-team/drizzle-orm) or how the linked issue is related to AWS JS SDK. Could you please elaborate more on that to help us understand a issue, perhaps with a minimal reproducible code?

**Comment by jakeleventhal** [comment] 2024-01-10 16:02
@aBurmeseDev drizzle is just a simple SQL wrapper. This may be the wrong place, but it seems like the issue is with the data API itself. Essentially in postgres if you have a table with a field that is an enum, insertion fails when trying to insert that record (see linked issue in drizzle).

@ anasmohammed361 to add more context.

**Comment by RanVaknin** [comment] 2024-01-23 07:53
Hi @jakeleventhal ,

Thank you for bringing this issue to our attention. To effectively address and investigate this issue, we require a detailed report that specifically outlines how this issue manifests within the JS SDK.

While I understand that this issue is linked to drizzle-orm, it's important to note that our support scope is limited to the AWS SDK itself. We do not directly support third-party tools or libraries.

It would be extremely helpful if you could update the original issue description with the relevant information. Detailed reproduction steps, error messages, and any SDK-specific context that you can provide.

Thanks again,
Ran~

**Comment by hugo082** [comment] 2024-01-31 16:15
I have the save error when I try to insert `text[]` column. I cannot execute the following statement

```sql
CREATE TABLE "public"."my_table" (
    "id" text NOT NULL,
    "shares_with" _text NOT NULL DEFAULT '{}'::text[],
    PRIMARY KEY ("id")
);
```

```js
{
   sql: 'insert into "my_table" ("id", "my_array") values (:1, :2)',
   params: [
     'mp_02',
     '{"org_graspgraspgraspgras2"}'
  ]
}
```

**Comment by anasmohammed361** [comment] 2024-02-06 00:58
https://github.com/notifications?query=is%3Aunread#issuecomment-1928569930

**Comment by jakeleventhal** [comment] 2024-02-06 13:15
> [drizzle-team/drizzle-orm#1073 (comment)](https://github.com/drizzle-team/drizzle-orm/issues/1073#issuecomment-1928584106)

Yeah, it seems that the real issue is that enums just aren't supported in the data API

**Comment by RanVaknin** [comment] 2024-03-19 16:51
Closing because no relevant info was provided, and the issue seems unrelated to the SDK.

If you still think this is an SDK related issue please open another issue and provide all the info in the intake form.

Thanks again,
Ran~

**Closed by RanVaknin** 2024-03-19 16:51 UTC
Labels: bug, p3
