### ISSUE TITLE
A way to add InvalidAccessKeyId as a retryable error?

### ISSUE THREAD

**Issue by djanowski** [aws/aws-sdk-js#920] opened 2016-03-02 19:32 UTC
We use [Vault](https://www.vaultproject.io) to create AWS credentials. We can add a high delay between creating and using the credentials, but it would be nice to take advantage of the retry mechanism already present in this library.

**Comment by chrisradek** [comment] 2016-03-03 18:38
@djanowski 
There is a way to make additional errors retryable. Instead of passing in a callback to your operation, you can grab a reference to an [`AWS.Request`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html) object and bind a callback to the [`extractError`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html#extractError-event) event. In this callback, you can set the [error](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Response.html#error-property) to retryable.

Quick example:
```javascript
var req = lambda.invoke(params);
req.on('extractError', function(response) {
  var error = response.error;
  if (error.code === 'InvalidAccessKeyId') {
    error.retryable = true;
  }
});
//Add custom retry delay as well
req.on('retry', function(response) {
  var error = response.error;
  if (error.code === 'InvalidAccessKeyId') {
    // override retry delay to be 1 second
    error.retryDelay = 1000;
  }
});
req.send(function(err, data) {});
```

However, what's the cause for the error you're seeing? The retry strategy is aggressive by default, though you can supply custom retry logic:
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#retryDelayOptions-property
You can also define a set retryDelay using the example above.

**Comment by chrisradek** [comment] 2016-03-08 22:43
Closing this issue, but feel free to comment or open a new issue if you still have any questions on how to implement the above!

**Closed by chrisradek** 2016-03-08 22:43 UTC
Labels: Feedback Requested, Question

**Comment by djanowski** [comment] 2016-03-09 13:20
Thank you!
