### ISSUE TITLE
LastEvaluatedKey incorrectly returned from DynamoDB.DocumentClient, vs correct results from DynamoDB directly

### ISSUE THREAD

**Issue by bluepeter** [aws/aws-sdk-js#1981] opened 2018-03-20 02:42 UTC
We have a strange situation.

We have a table with 10 items.

We do a query like so:

```
const response = await docClient.query({
    TableName: "site",
    IndexName: "orgId-lastCaptured-index",
    KeyConditionExpression: "orgId = :orgId",
    ExpressionAttributeValues: {
      ":orgId": orgId,
    },
    Limit: 10,
}).promise();
```

We get results that always includes a non-null `LastEvaluatedKey`, despite there only being 10 items in the table. And of course, when we do a followup query using `ExclusiveStartKey` we don't get any data.

We've tried many things in `DocumentClient` to prevent this. But nothing works.

The only thing that *does* work is using AWS CLI with the same query, *OR* using the more verbose `DynamoDB.query()` directly.

It appears to be an issue with `DocumentClient` and the use of `Limit`?

Note: we cannot repeat this issue on other tables with exactly 10 items. It is only in a single (critical) table where we have this issue: it concerns us about the stability of `DocumentClient` if it can unreliably return `LastEvaluatedKey` as non-null when there are indeed no more items to paginate.

**Comment by jeskew** [comment] 2018-03-26 23:39
When using the `AWS.DynamoDB#query` method, is `LastEvaluatedKey` undefined or an object with no properties?

**Comment by emainier** [comment] 2018-04-07 12:29
I have the same issue on a table, it always returns a LastEvaluatedKey outside of the range of the query:

    { Items: [],
      Count: 0,
      ScannedCount: 7880,
        LastEvaluatedKey:
         { id: '0d12c551-1942-11e8-957b-b5f8e93ff7ae',
           date: 1511578408599 } } { TableName: 'log-db-dev',
        IndexName: 'date-index',
        ProjectionExpression: '#date, email',
        FilterExpression: '#date between :startTime and :endTime',
        ExpressionAttributeNames: { '#date': 'date' },
        ExpressionAttributeValues: { ':startTime': 1523102683059, ':endTime': 1523189083058 } }

This issue appeared suddenly a few days ago.

**Comment by bluepeter** [comment] 2018-04-08 18:56
@jeskew it returns an object. I would have to recreate it to tell you specifically what, however. This almost certainly is related to `DocumentClient` as doing the same query "verbosely" without DocumentClient does not have this issue.

**Comment by CKitisak** [comment] 2018-05-23 10:00
I have this issue as well. How you guy solve it ?

My aws-sdk is 2.245.1.

**Comment by emainier** [comment] 2018-05-24 03:12
@CKitisak 

Not really solved but I got rid of it by doing a similar request and made sure it wasn't interrupted.
It seems to come back every time a request is interrupted and keeps the value of the LastEvaluatedKey.

**Comment by srchase** [comment] 2018-11-29 23:42
@bluepeter 

Were you able to get this resolved, or to reliably reproduce it with another table?

**Comment by bluepeter** [comment] 2018-11-29 23:48
@srchase we just worked around it. In our case we were using `LastEvaluatedKey` to determine if we need to paginate. We decided having a next button and paginating to an empty page was "okay." Not ideal, but ok.

**Comment by srchase** [comment] 2018-12-26 21:21
Per the DynamoDB [Query](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html) Documentation:

> If LastEvaluatedKey is not empty, it does not necessarily mean that there is more data in the result set. The only way to know when you have reached the end of the result set is when LastEvaluatedKey is empty.

As this is the intended behavior of the DynamoDB Service team, I'm opting to close this issue.

**Closed by srchase** 2018-12-26 21:21 UTC
Labels: guidance

**Comment by rlisnoff** [comment] 2019-02-22 17:16
We're having the same issue on our end, when using DynamoDB Local our queries return with a LastEvaluatedKey when the Limit passed in happened to equal the exact amount of entries that matched the query. For example, I query DDB local with a limit of 1, and I happen to know that query only matches a single entry, yet the query returns with a non-empty LastEvaluatedKey, which signals that there's more data left to be retrieved even though I know there is not.

Using the same exact setup & code, when run against AWS-hosted DynamoDB we get an empty object as we expect via the documentation. The issue here seems to be an inconsistency between the local program & your hosted solution.

**Comment by bluepeter** [comment] 2019-02-22 19:26
@rlisnoff our ultimate solution was to query for X + 1 and then only show X in the client, but use the + 1 to determine if we need to paginate.

**Comment by wjrjerome** [comment] 2019-07-11 23:04
Hi Any updates on this? We experienced similar but rather strange behavior. 
If we set limit to 1 and we know there is only 1 item for that query, the query will not return `lastEvaluatedKey`. Which is not what the documentation says.

fyi @srchase

**Comment by trivikr** [comment] 2019-07-12 18:23
This thread has been locked as the issue has been resolved for quite some time. Please open a  [new issue](https://github.com/aws/aws-sdk-js/issues/new/choose) for related bugs and link to relevant comments in this thread.
