### ISSUE TITLE
Angular ECSCredentials is not a constructor

### ISSUE THREAD

**Issue by baillyjamy** [aws/aws-sdk-js#3229] opened 2020-04-26 01:05 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I would like to use `AWS.ECSCredentials()` or `AWS.EC2MetadataCredentials()` to authenticate my angular application and use my s3 bucket without `accessKeyId` and `secretAccessKey` in my code. But the problem is that at runtime I get the following error message: `core.js:4061 ERROR TypeError: aws_sdk__WEBPACK_IMPORTED_MODULE_3__.ECSCredentials is not a constructor`.
I have of course tried with the following lines of code from the documentation:
```
AWS.config.credentials = new AWS.ECSCredentials({
  httpOptions: { timeout: 5000 },
  maxRetries: 10,
  retryDelayOptions: { base: 200 }
});
```
It is interesting to note that `retryDelayOptions` is not part of the `ECSCredentialsOptions` interface and therefore causes a compilation error. But it's in the [documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ECSCredentials.html). (so I removed it).

**Is the issue in the browser/Node.js?**
This issue is in the browser console.

**Details of the browser/Node.js version**
Node `v12.16.1`
Angular `9.1.0`

**SDK version number**
`aws-sdk@2.663.0`

**To Reproduce (observed behavior)**
You can execute a minimal Angular application that reproduce this issue : https://github.com/baillyjamy/aws-sdk-js-issue-sample

**Complete error**
```
ERROR TypeError: aws_sdk__WEBPACK_IMPORTED_MODULE_1__.ECSCredentials is not a constructor
    at aws.service.ts:11
    at new ZoneAwarePromise (zone-evergreen.js:960)
    at AwsService.Init (aws.service.ts:10)
    at Array.<anonymous> (aws.service.ts:23)
    at ApplicationInitStatus.runInitializers (core.js:40823)
    at core.js:42753
    at _callAndReportToErrorHandler (core.js:42927)
    at core.js:42747
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Object.onInvoke (core.js:41784)
defaultErrorLogger @ core.js:6210

```

**Comment by ajredniwja** [comment] 2020-04-28 20:43
Hey @baillyjamy thank-you for reaching out to us with your issue. 
I believe this is not a particularly a bug with the SDK but problems with the way it is imported can you try something like mentioned in https://github.com/aws/aws-sdk-js/issues/2794#issuecomment-522886306 

I will test the `retryDelayOptions`, it is not mentioned in the interface but defined [here](https://github.com/aws/aws-sdk-js/blob/master/lib/config.d.ts) it is mentioned in the example you mentioned since the `config` will be able to accept it, I haven't tested it but can get back to you on that. If that is the case the docs should make it clear as well.

**Comment by baillyjamy** [comment] 2020-04-29 00:29
I tried to import ECSCredentials with:
```
import { ECSCredentials } from 'aws-sdk/lib/credentials/ecs_credentials';
```
```
import { ECSCredentials } from 'aws-sdk';
```
But i have same error. 
With this way i have a compile time error:
```
import * as ECSCredentials from 'aws-sdk/lib/credentials/ecs_credentials';
```
```
error TS2351: This expression is not constructable.
      Type 'typeof import("/Users/jamybailly/dev/test/aws-sdk-js-issue-sample/node_modules/aws-sdk/lib/credentials/ecs_credentials")' has no construct signatures.
    
    12       AWS.config.credentials = new ECSCredentials({
```

**Comment by baillyjamy** [comment] 2020-05-21 04:45
Can you reproduce the problem?

**Comment by ajredniwja** [comment] 2020-05-27 22:36
I was able to reproduce it although it took me some time to get around and start the angular app, will get back to you once I solve the problem, thanks for waiting.

**Comment by philipwigg** [comment] 2020-06-03 20:34
Something I don't understand... ```AWS.ECSCredentials()``` fetches credentials from the local metadata endpoint when it's running inside a container running on ECS. eg. it's backend functionality.

Wouldn't an angular app be running in a client browser? eg, it's not going to be able to fetch the creds? Sorry if I'm missing something obvious, I'm more of a devops/cloud engineer than a dev by trade.

**Comment by ajredniwja** [comment] 2020-06-03 21:25
@philipwigg you are right, since the app runs on the client browser the webPack doesn't package all the modules. 

https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-credentials-browser.html

Can you use one of these methods to set your credentials @baillyjamy ?

Let me know if I am missing anything on your use case.

**Comment by baillyjamy** [comment] 2020-06-04 00:45
`AWS.ECSCredentials()` was helpful not to have a credential with access token in the code. I can manage without it during the dev but I don't want to use Amazon Cognito Identity. I think it's not good to have credentials in the code even if the file is in the `.gitignore`.
But ok i understand if is not possible to use `AWS.ECSCredentials()` in angular

**Comment by ajredniwja** [comment] 2020-08-19 22:30
Closing this now. Please reach out if there is any questions.

**Closed by ajredniwja** 2020-08-19 22:30 UTC
Labels: documentation, guidance

**Comment by peichengliu-kinto** [comment] 2021-12-28 07:33
@baillyjamy I also encountered this problem. ECS has role permission. I failed to obtain ECS credentials using react. How did you solve it in the end
