### ISSUE TITLE
Optional fields in Typescript type definition files

### ISSUE THREAD

**Issue by afroozeh** [aws/aws-sdk-js#1719] opened 2017-09-14 12:25 UTC
I am using the typescript API to access Amazon S3. After enabling `strict` for typscript I get errors due to optional types. For example for these interfaces:

```
export interface ListObjectsV2Output {
  IsTruncated?: IsTruncated;
  Contents?: ObjectList;
  Name?: BucketName;
  Prefix?: Prefix;
  Delimiter?: Delimiter;
  MaxKeys?: MaxKeys;
  CommonPrefixes?: CommonPrefixList;
  EncodingType?: EncodingType;
  KeyCount?: KeyCount;
  ContinuationToken?: Token;
  NextContinuationToken?: NextToken;
  StartAfter?: StartAfter;
}
```

```
export interface Object {
  Key?: ObjectKey;
  LastModified?: LastModified;
  ETag?: ETag;
  Size?: Size;
  StorageClass?: ObjectStorageClass;
  Owner?: Owner;
}
```

Why all these fields are declared optional? Under which circumstances should I check for `undefined`? Can I safely use `!` and ignore type errors?

**Comment by chrisradek** [comment] 2017-09-14 18:06
@afroozeh 
The TypeScript definitions for services are generated based on the service models (found in `apis/`) that are shared across all the SDKs.

Generally, we only know which fields are required as input to an operation, not which fields will always be present on the output. I can reach out to S3 to see if they can document which fields are always present.

**Comment by navaati** [comment] 2017-11-28 18:24
It's huuuuuugely annoying to have to use `!` absolutely *everywhere* !

**Comment by MatthiasKunnen** [comment] 2018-11-15 04:56
Duplicate of #1553

**Closed** 2018-11-15 15:40 UTC
Labels: Typings, duplicate, service-api
