### ISSUE TITLE
httpOptions Timeout not working with Dynamodb

### ISSUE THREAD

**Issue by gregcope** [aws/aws-sdk-js#758] opened 2015-10-20 08:17 UTC
trying to use;

httpOptions: { timeout: 5000 }

To timeout a dynamodb API call appears to not work.

Expected result - timeout in 5 secs

Actual result - timeout in around 25 decs

####

$ time node dynamoTimeout.js 
Unable to create table. Error JSON: {
  "message": "connect ECONNREFUSED 127.0.0.1:8000",
  "code": "NetworkingError",
  "errno": "ECONNREFUSED",
  "syscall": "connect",
  "address": "127.0.0.1",
  "port": 8000,
  "region": "us-west-2",
  "hostname": "localhost",
  "retryable": true,
  "time": "2015-10-20T08:17:45.230Z"
}

real	0m26.023s
user	0m0.301s
sys	0m0.074s

####

This is on;
$ node --version
v4.1.2
$ uname -a
Darwin FT-MW4209 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
OSX: 10.10.5 (14F27)

example code;

##### dynamoTimeout.js 

var AWS = require("aws-sdk");

AWS.config.update({
  region: "us-west-2",
  endpoint: "http://localhost:8000",
//  maxRetries: 1,
  logger: "process.stdout",
  httpOptions: { timeout: 5000 }
});

//var dynamodb = new AWS.DynamoDB({httpOptions: {timeout: 5000}});
var dynamodb = new AWS.DynamoDB();

var params = {
    TableName : "Movies",
    KeySchema: [       
        { AttributeName: "year", KeyType: "HASH"},
        { AttributeName: "title", KeyType: "RANGE" }
    ],
    AttributeDefinitions: [       
        { AttributeName: "year", AttributeType: "N" },
        { AttributeName: "title", AttributeType: "S" }
    ],
    ProvisionedThroughput: {       
        ReadCapacityUnits: 10, 
        WriteCapacityUnits: 10
    }
};

dynamodb.createTable(params, function(err, data) {
    if (err) {
        console.error("Unable to create table. Error JSON:", JSON.stringify(err, null, 2));
    } else {
        console.log("Created table. Table description JSON:", JSON.stringify(data, null, 2));
    }
});

**Comment by jeskew** [comment] 2015-10-20 23:45
Hi @gregcope,

The `timeout` option is applied to a connection attempt, not to an entire operation like `dynamodb.createTable`. Because operations can be retried a number of times with an exponentially increasing delay between attempts, an operation might take significantly longer than its allotted socket timeout to fail. This is especially true of DynamoDB operations, which are retried 11 times. If the connection were actually timing out instead of being refused, the operation could take over a minute to fail.

I see that you commented out a line limiting the operation to a single retry. That's your best option if you want an operation to fail fast.

**Comment by gregcope** [comment] 2015-10-21 10:47
Thanks,

Where is the logic around the delay between attempts?  This is probably where the time is disappearing.

**Comment by jeskew** [comment] 2015-10-21 17:23
The retry delay is calculated using [this function](https://github.com/aws/aws-sdk-js/blob/7d02a64bc559a0edba3799dae42a3f964cfb9c28/lib/services/dynamodb.js#L44). You're right that this is where most of the 25 seconds recorded is being spent.

**Comment by jeskew** [comment] 2015-11-03 22:21
Closing for now. Please feel free to reopen if you have any questions or concerns.

**Closed by jeskew** 2015-11-03 22:21 UTC

**Comment by cocobiz** [comment] 2019-05-30 07:40
@jeskew hi jeskew
does this `timeout` option is same as node.js http.Agent which also has an option called `timeout`?
https://nodejs.org/dist/latest-v10.x/docs/api/http.html#http_new_agent_options

and i also have one more question:
our app often occurred that some dynamodb query costs long time about "120s” or "200s", does this due to the `timeout` options? i found that this option got a default value 120000 ms (https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#constructor-property), so i suspect that this option maybe the root cause for long query(200s maybe related to our maxRetries=2).

you can get the detail info related to #2585 

thanks a lot.

**Comment by jeskew** [comment] 2019-05-30 14:02
@cocobiz `timeout` in the SDK is equivalent to the http.Agent option. Both [the SDK](https://github.com/aws/aws-sdk-js/blob/251142886aa14ff7d2c2fd0bdb86d9441f243872/lib/http/node.js#L82) and [node](https://github.com/nodejs/node/blob/0df581c30728fae75405e7aa66102d98571cec87/lib/_http_outgoing.js#L192) call [`setTimeout`](https://nodejs.org/dist/latest-v10.x/docs/api/net.html#net_socket_settimeout_timeout_callback) on the underlying socket with the provided value.

**Comment by cocobiz** [comment] 2019-06-03 08:32
@jeskew 
Thanks for your replay!
And can you give us some tips about my second questions which why a normal query took so long time? thank you again.

**Comment by AllanFly120** [comment] 2019-06-03 20:36
Hey @cocobiz 
Sometimes you see long latency becuase server has difficulty to establish an ssl connection. You can try reusing the connection the reduce the need to re-establish the connection. You do so by either using `keepAlive` option in [Agent option](https://nodejs.org/docs/latest/api/http.html#http_new_agent_options) or set the [environmental varible we just introduced](https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#24630) without a code change.

**Comment by cocobiz** [comment] 2019-06-04 02:23
hi @AllanFly120 
thanks for your replay, and we have set `keepAlive: true` option to reuse current socket, but we still got some long latency queries. the code as below
```js
new AWS.DynamoDB.DocumentClient({
            endpoint: config.dynamoEndpoint,
            region: config.dynamoRegion,
            accessKeyId: config.dynamoAccessKeyId,
            secretAccessKey: config.dynamoSecretAccessKey,
            maxRetries: 2,
            httpOptions: {
                agent: new https.Agent({
                    maxSockets: Infinity,
                    keepAlive: true
                })
            }
        }
```

From the metrics, we got some query took about 120 seconds, even though it's a very normal query :(

**Comment by trivikr** [comment] 2019-06-05 21:20
Locking this thread as the issue is old, and resolved.
Please open a [new issue](https://github.com/aws/aws-sdk-js/issues/new/choose) for related bugs and link to relevant comments in this thread.
