### ISSUE TITLE
Images are not complete and show grey background

### ISSUE THREAD

**Issue by SilverFoxA** [aws/aws-sdk-js#3164] opened 2020-03-18 12:41 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [ x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
In my application, I'm allowing admins to upload products in bulk. In the excel sheet, admin can add multiple images. The images are the link of google drive photos. The application downloads the image from google drive and stores it in the local webserver. Which looks like this: https://i.imgur.com/qOWoMGn.jpg

When I upload using the SDK to AWS S3, it looks like this: https://i.imgur.com/tbDcSfR.jpg

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v13.7.0

**SDK version number**
"aws-sdk": "^2.524.0",

**To Reproduce (observed behavior)**
We couldn't trace the issue of why, as it happens with few where the others are just fine.

**Expected behavior**
It's should display me the complete image.

**Screenshots**
Original Image: https://i.imgur.com/qOWoMGn.jpg
Faulty Image: https://i.imgur.com/tbDcSfR.jpg

**Additional context**

**Comment by ajredniwja** [comment] 2020-03-19 19:51
Hey @SilverFoxA thank-you for reaching out, can you please share repro code.

Do you see any errors when a faulty picture is uploaded?

**Comment by SilverFoxA** [comment] 2020-03-20 05:08
Hello @ajredniwja ,

Hope you are doing well.
Thank you for your prompt response.
The codebase is deployed to live server and was working for almost half a year now and everything was working as expected.

This issue started 2-3days back, I'm assuming it has something to do with the latest changes to AWS S3 - just an assumption.

Here's the codebase 

**UploadToS3Queue.js**
<code>

    const aws = new AWSS3().upload(data.filePath, data.keyName ? data.keyName : data.filePath, data);
    //console.log("AWS",aws)
    if (aws)
        aws.then(async res => {
            //console.log('Response', res)
            // console.log(
            //     The URL is ${res.Location}
            // );

            data['link'] = res.Location

            // perform database operation to update the database with AWS S3 image link
            await performImageDBOps(data)

            // deleteLocalFile(data.filePath)
            done()
        }).catch(reason => {
            done(reason)
            //console.log('Reason', reason)
        });
</code>

**UploadLogic**
<code>

    async upload(filepath, keyName, options) {

        if (filepath[0] === '/') {
            filepath = filepath.substr(1)
        }

        // Create params for putObject call
        const objectParams = {
            Bucket: awsConfig.AWS_BUCKET_ASSETS,
            Key: (keyName ? keyName : filepath).replace('upload_', '').replace('uploads', 'static'),
            Body: fs.readFileSync(filepath),
            ACL: 'public-read',
            CacheControl: 'max-age=86400',
            //Expires:'',
            //Metadata:''
        };

        //console.log(objectParams)
        // Create object upload promise
        return new AWS.S3(config).upload(objectParams).promise();
    }
</code>

Please let me know if you need any further information regarding the same.

The file got uploaded, I got a success response.

**Comment by ajredniwja** [comment] 2020-03-27 23:02
I am able to upload images successfully using the code snippet that you provided. 

Is there anything that you have noticed, any pattern or special case where it fails every-time?

**Comment by SilverFoxA** [comment] 2020-04-01 08:04
I haven't been able to get to any conclusion as couldn't find any valid reason behind the output.

I have shared the image using which I was able to replicate the error.

**Comment by ajredniwja** [comment] 2020-04-01 21:38
@SilverFoxA, as mentioned there in the thread as well, I am not able to reproduce the error as well.

Do you see any error when the picture is uploaded?
Do you see the error every-time you upload this picture?

**Comment by SilverFoxA** [comment] 2020-04-07 11:50
There's no error as pointed earlier.

**Comment by ajredniwja** [comment] 2020-04-08 21:34
Closing this issue now, reach out if you have additional questions.

**Closed by ajredniwja** 2020-04-08 21:34 UTC
Labels: bug, response-requested
