### ISSUE TITLE
Unauthenticated multipart upload from the browser

### ISSUE THREAD

**Issue by jpfranco** [aws/aws-sdk-js#512] opened 2015-02-16 19:35 UTC
Is there a way to use ```s3.upload``` from the browser with without specifying a secret key? The use case for this would be uploading to a public bucket. I tried using ```makeUnauthenticatedRequest``` but I'm assuming it fails because ```s3.upload``` returns a ```ManagedUpload``` object instead of a single request. Is it a requirement to use signed requests when using multipart uploads? Thanks

**Comment by AdityaManohar** [comment] 2015-02-16 20:33
@jpfranco 
The `AWS.S3.ManagedUpload` is a convenience wrapper over [`AWS.S3.createMultipartUpload`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#createMultipartUpload-property), [`AWS.S3.uploadPart`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#uploadPart-property), and [`AWS.S3.completeMultipartUpload()`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#completeMultipartUpload-property). 

>Is it a requirement to use signed requests when using multipart uploads?

Yes, because Amazon S3 does not allow unauthenticated access to these operations.

You can [authenticate the SDK in the browser using Amazon Cognito](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-configuring.html#Using_Amazon_Cognito_to_Authenticate_Users). Amazon Cognito can be used with unauthenticated roles as well, so your users will not need to log in to access your AWS resources. 

Note: It is important to scope your unauthenticated roles carefully, to only provide access to the resources that you want to expose.

Let me know if this helps, and I'd be happy to answer other questions you may have!

**Comment by jpfranco** [comment] 2015-02-16 21:14
Thanks for the info, I will take a look at Amazon Cognito then. I'm a bit curious though, is there  a particular reason why unauthenticated access is not allowed for multipart uploads?

**Comment by AdityaManohar** [comment] 2015-02-16 21:23
@jpfranco 
Unauthenticated is actually allowed. I misread your initial question and have updated my response above.

I would recommend that you use Amazon Cognito for unauthenticated access. Cognito allows you to configure access using IAM roles at a very granular level. In addition it is also possible to audit identities that users are assigned using Cognito.

**Comment by jpfranco** [comment] 2015-02-16 22:07
@AdityaManohar thanks again. So for testing purposes is it possible to make an ```s3.upload``` call without setting my keys like I can when using ```s3.makeUnauthenticatedRequest('putObject')``` on an unrestricted bucket, for example? Sorry about the repeated questions btw.

**Comment by AdityaManohar** [comment] 2015-02-16 22:23
@jpfranco 
For a test setup you can set `s3.api.signatureVersion = ''`. Note that this would not sign any request made to S3, and would affect all your S3 clients.

Like I mentioned earlier, the other way to do it would be to use a scoped IAM user with hardcoded credentials.

`s3.makeUnauthenticatedRequest()` does not currently work with `s3.upload()` because `s3.upload()` internally makes 3 (sometimes fewer) different operation calls.

**Comment by jpfranco** [comment] 2015-02-16 22:28
@AdityaManohar thanks again. I'm trying out clearing the signature version and that makes the ```CredentialsError: Missing credentials in config``` error go away, but I now get this new error: 

```AccessDenied: Anonymous users cannot initiate multipart uploads.  Please authenticate.```

 I'm very positive that this bucket is unrestricted because I'm able to do a ```putObject``` without credentials, so maybe unauthenticated access is forbidden for multipart uploads after all?

**Comment by AdityaManohar** [comment] 2015-02-16 22:40
@jpfranco 
I am able to confirm the error. It seems like you cannot initiate multipart uploads anonymously. 

For now you could use Cognito to provide anonymous access. In the meantime, I'll verify this behavior with the Amazon S3 team, just to make sure it's not a configuration issue.

**Comment by AdityaManohar** [comment] 2015-03-05 18:51
@jpfranco 
I just confirmed that multipart uploads do not work with unauthenticated requests. I'm closing this issue out since you already have a workaround. Feel free to open this issue or another issue if you have any other questions.

**Closed by AdityaManohar** 2015-03-05 18:51 UTC
