### ISSUE TITLE
Could we please get an update from Amazon on this one thanks.

### ISSUE THREAD

**Issue by dukedougal** [aws/aws-sdk-js#1102] opened 2016-08-21 23:20 UTC
https://github.com/aws/aws-sdk-js/issues/603

Cause it's more than a year since it was raised.

**Comment by LiuJoyceC** [comment] 2016-08-23 17:09
Hi @dukedougal 

Thanks for voicing your concern, as it helps us prioritize issues. We have been actively looking at Webpack support, and we appreciate your patience.

I am closing this as it is a duplicate of the other one.

**Closed by LiuJoyceC** 2016-08-23 17:09 UTC
