### ISSUE TITLE
No error reported when there is a typo in the aws region name

### ISSUE THREAD

**Issue by smandava** [aws/aws-sdk-js#875] opened 2016-01-15 03:02 UTC
Running the following code on node is causing it to hang without any error message. My understanding is that line number 11 (console.log("failed");) should be executed. Please correct me if I'm wrong. 

```javascript
var AWS=require('aws-sdk');
var ec2=new AWS.EC2({
    apiVersion: '2015-10-01',
    region: 'us-east', //NOTE: TYPO HERE
    timeout: 1000
});
ec2.describeInstances({},function(err,response) {
        if (err) {
            console.log("failed");
        } else {
            console.log(response);    
        }
});
```

**Comment by chrisradek** [comment] 2016-01-15 16:44
@smandava 
Running the same code using the latest version of the SDK in node, I see `failed` getting logged to the console. What version of the SDK and what environment are you testing in?

**Comment by smandava** [comment] 2016-01-17 15:33
Seeing this on OS X node version 5.1.0 and aws-sdk@2.2.30.

**Comment by chrisradek** [comment] 2016-01-20 17:27
@smandava 
I tried with the same version of node, SDK, and used OS X, and can't reproduce your error. Are you testing with the exact code you provided, or is this a snippet from surrounding code?

**Comment by smandava** [comment] 2016-01-22 02:10
Thanks for looking into it again. It is possible that something is wrong in my environment, sharing the source code just in case.. 

Node version:
```
❯ node -v
v5.1.0
```

Source code folder:

[test.zip](https://github.com/aws/aws-sdk-js/files/100191/test.zip)

**Comment by chrisradek** [comment] 2016-01-26 16:49
@smandava 
Have you tried running your code on another machine? Even using your exact code as supplied, I am unable to reproduce. Does console.log work at all within your environment?

**Comment by smandava** [comment] 2016-01-26 17:23
@chrisradek thanks for checking again. console.log is working fine. 

The same code working fine on my windows desktop. Some thing must be wrong on my Mac environment..

**Comment by chrisradek** [comment] 2016-01-26 18:02
Thanks @smandava 
I'm closing this issue since I can't reproduce, and it appears to be related to your environment.
If you find any more information that points to an issue with the SDK, feel free to reopen, comment, or open a new issue!

**Closed by chrisradek** 2016-01-26 18:02 UTC
Labels: Feedback Requested
