### ISSUE TITLE
400 Bad request on headBucket if bucket has existed

### ISSUE THREAD

**Issue by bolddp** [aws/aws-sdk-js#2749] opened 2019-06-30 13:49 UTC
**Describe the bug**
S3.headBucket returns 400 Bad request when using a bucket name that has existed in my account. For non existing bucket names, response is 404

**Is the issue in the browser/Node.js?**
Node.js, running a unit test

**Details of the browser/Node.js version**
v8.10.0

**SDK version number**
v2.484.0

**To Reproduce (observed behavior)**
* Create bucket through AWS console
* query it with headBucket
* remove the bucket
* query it with headBucket, returns 400 instead of 404

**Expected behavior**
404 all the time

**Comment by AllanFly120** [comment] 2019-07-01 19:53
Hi @bolddp,

I cannot reproduce this issue. Can you share the exact exception message? What's the name the bucket you are calling to? Which region is it in?

**Comment by trivikr** [comment] 2019-07-01 20:03
I'm not able to reproduce. I'm getting a 404 as described in [HEAD Bucket documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketHEAD.html)

Created three buckets on S3 as follows:
* `test-aws-sdk-js-2749-existent` - bucket which exists
* `test-aws-sdk-js-2749-non-existent` - bucket which doesn't exist
* `test-aws-sdk-js-2749-removed` - bucket created for testing, but was removed

```
$ node -v
v8.10.0
$ AWS.VERSION
'2.484.0'
```

Tested with [console](https://github.com/aws/aws-sdk-js/tree/master/scripts) script:
```javascript
const callback = (err, data) => {
  if (err) console.log(err, err.stack);
  else console.log(data);
};
```

testing existent bucket:
* input
```javascript
s3.headBucket(
  {
    Bucket: "test-aws-sdk-js-2749-existent"
  },
  callback
);
```
* output:
```
[AWS s3 200 0.518s 2 retries] headBucket({ Bucket: 'test-aws-sdk-js-2749-existent' })
{}
```

testing non-existent bucket:
* input
```javascript
s3.headBucket(
  {
    Bucket: "test-aws-sdk-js-2749-non-existent"
  },
  callback
);
```
* output:
```
[AWS s3 404 0.34s 0 retries] headBucket({ Bucket: 'test-aws-sdk-js-2749-non-existent' })
{ NotFound: null
    at Request.extractError (/Users/trivikr/workspace/aws-sdk-js/lib/services/s3.js:565:35)
    at Request.callListeners (/Users/trivikr/workspace/aws-sdk-js/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/trivikr/workspace/aws-sdk-js/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/trivikr/workspace/aws-sdk-js/lib/request.js:683:14)
    at Request.transition (/Users/trivikr/workspace/aws-sdk-js/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/trivikr/workspace/aws-sdk-js/lib/state_machine.js:14:12)
    at /Users/trivikr/workspace/aws-sdk-js/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/trivikr/workspace/aws-sdk-js/lib/request.js:38:9)
    at Request.<anonymous> (/Users/trivikr/workspace/aws-sdk-js/lib/request.js:685:12)
    at Request.callListeners (/Users/trivikr/workspace/aws-sdk-js/lib/sequential_executor.js:116:18)
  message: null,
  code: 'NotFound',
  region: null,
  time: 2019-07-01T19:55:12.942Z,
  requestId: '12E218601B59413C',
  extendedRequestId: 'TEdd70Zda0pwQMjkPnHuWrwqvYsVIyuFFSteJiR10thtw09oczkW2nzQxmUErLmBV274LMqIK5w=',
  cfId: undefined,
  statusCode: 404,
  retryable: false,
  retryDelay: 94.30024480913505 } 'NotFound: null\n    at Request.extractError (/Users/trivikr/workspace/aws-sdk-js/lib/services/s3.js:565:35)\n    at Request.callListeners (/Users/trivikr/workspace/aws-sdk-js/lib/sequential_executor.js:106:20)\n    at Request.emit (/Users/trivikr/workspace/aws-sdk-js/lib/sequential_executor.js:78:10)\n    at Request.emit (/Users/trivikr/workspace/aws-sdk-js/lib/request.js:683:14)\n    at Request.transition (/Users/trivikr/workspace/aws-sdk-js/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/Users/trivikr/workspace/aws-sdk-js/lib/state_machine.js:14:12)\n    at /Users/trivikr/workspace/aws-sdk-js/lib/state_machine.js:26:10\n    at Request.<anonymous> (/Users/trivikr/workspace/aws-sdk-js/lib/request.js:38:9)\n    at Request.<anonymous> (/Users/trivikr/workspace/aws-sdk-js/lib/request.js:685:12)\n    at Request.callListeners (/Users/trivikr/workspace/aws-sdk-js/lib/sequential_executor.js:116:18)'
NotFound: null
    at Request.extractError (/Users/trivikr/workspace/aws-sdk-js/lib/services/s3.js:565:35)
    at Request.callListeners (/Users/trivikr/workspace/aws-sdk-js/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/trivikr/workspace/aws-sdk-js/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/trivikr/workspace/aws-sdk-js/lib/request.js:683:14)
    at Request.transition (/Users/trivikr/workspace/aws-sdk-js/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/trivikr/workspace/aws-sdk-js/lib/state_machine.js:14:12)
    at /Users/trivikr/workspace/aws-sdk-js/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/trivikr/workspace/aws-sdk-js/lib/request.js:38:9)
    at Request.<anonymous> (/Users/trivikr/workspace/aws-sdk-js/lib/request.js:685:12)
    at Request.callListeners (/Users/trivikr/workspace/aws-sdk-js/lib/sequential_executor.js:116:18) 
```

testing to-be-removed bucket:
* input
```javascript
s3.headBucket(
  {
    Bucket: "test-aws-sdk-js-2749-removed"
  },
  callback
);
```
* output (before removing):
```
[AWS s3 200 0.564s 2 retries] headBucket({ Bucket: 'test-aws-sdk-js-2749-removed' })
{}
```
* output (after removing):
```
[AWS s3 404 0.087s 0 retries] headBucket({ Bucket: 'test-aws-sdk-js-2749-removed' })
{ NotFound: null
    at Request.extractError (/Users/trivikr/workspace/aws-sdk-js/lib/services/s3.js:565:35)
    at Request.callListeners (/Users/trivikr/workspace/aws-sdk-js/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/trivikr/workspace/aws-sdk-js/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/trivikr/workspace/aws-sdk-js/lib/request.js:683:14)
    at Request.transition (/Users/trivikr/workspace/aws-sdk-js/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/trivikr/workspace/aws-sdk-js/lib/state_machine.js:14:12)
    at /Users/trivikr/workspace/aws-sdk-js/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/trivikr/workspace/aws-sdk-js/lib/request.js:38:9)
    at Request.<anonymous> (/Users/trivikr/workspace/aws-sdk-js/lib/request.js:685:12)
    at Request.callListeners (/Users/trivikr/workspace/aws-sdk-js/lib/sequential_executor.js:116:18)
  message: null,
  code: 'NotFound',
  region: null,
  time: 2019-07-01T20:00:25.219Z,
  requestId: 'F15630B0184EC7BF',
  extendedRequestId: 'VnkGA4W+i7XW6guHqNZvlq1ByYi3WbUl8QK54sahwbNcVFOSPocg5Yi2//kF6yelVLt7YKTeWs0=',
  cfId: undefined,
  statusCode: 404,
  retryable: false,
  retryDelay: 29.809086635292516 } 'NotFound: null\n    at Request.extractError (/Users/trivikr/workspace/aws-sdk-js/lib/services/s3.js:565:35)\n    at Request.callListeners (/Users/trivikr/workspace/aws-sdk-js/lib/sequential_executor.js:106:20)\n    at Request.emit (/Users/trivikr/workspace/aws-sdk-js/lib/sequential_executor.js:78:10)\n    at Request.emit (/Users/trivikr/workspace/aws-sdk-js/lib/request.js:683:14)\n    at Request.transition (/Users/trivikr/workspace/aws-sdk-js/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/Users/trivikr/workspace/aws-sdk-js/lib/state_machine.js:14:12)\n    at /Users/trivikr/workspace/aws-sdk-js/lib/state_machine.js:26:10\n    at Request.<anonymous> (/Users/trivikr/workspace/aws-sdk-js/lib/request.js:38:9)\n    at Request.<anonymous> (/Users/trivikr/workspace/aws-sdk-js/lib/request.js:685:12)\n    at Request.callListeners (/Users/trivikr/workspace/aws-sdk-js/lib/sequential_executor.js:116:18)'
NotFound: null
    at Request.extractError (/Users/trivikr/workspace/aws-sdk-js/lib/services/s3.js:565:35)
    at Request.callListeners (/Users/trivikr/workspace/aws-sdk-js/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/trivikr/workspace/aws-sdk-js/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/trivikr/workspace/aws-sdk-js/lib/request.js:683:14)
    at Request.transition (/Users/trivikr/workspace/aws-sdk-js/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/trivikr/workspace/aws-sdk-js/lib/state_machine.js:14:12)
    at /Users/trivikr/workspace/aws-sdk-js/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/trivikr/workspace/aws-sdk-js/lib/request.js:38:9)
    at Request.<anonymous> (/Users/trivikr/workspace/aws-sdk-js/lib/request.js:685:12)
    at Request.callListeners (/Users/trivikr/workspace/aws-sdk-js/lib/sequential_executor.js:116:18)
```

**Comment by bolddp** [comment] 2019-07-01 20:04
The bucket was in Ireland, called 'daniel-p-bucket-1'. I'll try to reproduce.

**Comment by bolddp** [comment] 2019-07-01 20:09
Weill, it works now for me too. I got the error several times yesterday, but it was in a short timespan, e.g. at some point I may have deleted the bucket through the AWS console just 20 seconds before running headBucket.
I suppose you can close this, I'll get in touch if I run into it again. Thx for your quick reply!

**Comment by trivikr** [comment] 2019-07-01 20:14
Closing as the issue was intermittent for the user, and was not reproducible.

**Closed by trivikr** 2019-07-01 20:14 UTC
Labels: bug report
