### ISSUE TITLE
Cognito federated identities answers with UnknownError Not Found on getOpenIdTokenForDeveloperIdentity()

### ISSUE THREAD

**Issue by napcoder** [aws/aws-sdk-js#1718] opened 2017-09-14 08:07 UTC
I have an issue in aws lambda (environment nodejs6.10), trying to register a user as custom provider. I'm calling getOpenIdTokenForDeveloperIdentity in my backend, with this params:

```
const params = {
  IdentityPoolId: config.IDENTITY_POOL_ID,
  Logins: {
    [config.DEVELOPER_PROVIDER_NAME]: id
  }
}
```
The code responsible for the call is simple:

```
const cognitoidentity = new AWS.CognitoIdentity({apiVersion: '2014-06-30'})
return cognitoidentity.getOpenIdTokenForDeveloperIdentity(params).promise()
.then(...)
```
Unfortunately the answer from Cognito is this error:

```
{
  "message": "Not Found",
  "code": "UnknownError",
  "statusCode": 404,
  "time": "2017-09-13T16:50:12.832Z",
  "requestId": "4RQE2T66K7LOT3RBGOMN0JO82NVV4KQNSO5AEMVJF66Q9ASUAAJG",
  "retryable": false,
  "retryDelay": 58.96973108302359
}
```
I've done this with almost same code 2 years ago and is still working, but in this project it is not. I've made a little web client for unauthenticated user and it is working well with Cognito, so I assume cognito is set correctly. The region are the same for cognito and lambda, us-east-1. The role and policies seems correct, lambda have permission to do all the stuff with Cognito Identity. I don't know what to do now, just thinking to leave cognito if this cannot be solved. Please help.

Other relevant parts of information: I'm using Serverless framework, but cognito identity pool was created manually (the same for roles).

Lambda allowed permissions:
```
[
  "cognito-identity:DeleteIdentities",
  "cognito-identity:DescribeIdentity",
  "cognito-identity:GetOpenIdTokenForDeveloperIdentity",
  "cognito-identity:ListIdentities",
  "cognito-identity:LookupDeveloperIdentity",
  "cognito-identity:MergeDeveloperIdentities",
  "cognito-identity:UnlinkDeveloperIdentity"
]
```
Code initializations

```
const AWS = require('aws-sdk')

AWS.config.update({
  region: config.REGION
})
AWS.config.setPromisesDependency(require('bluebird'))
```

**Comment by chrisradek** [comment] 2017-09-14 21:18
@napcoder 
I tried a simple lambda function using the same permissions you set up above. I'm not sure what the cause of your issue is. Can you try creating a lambda function that solely tests that you can call getOpenIdTokenForDeveloperIdentity? I wrote a quick example below (Lambda and Cognito are both is us-west-2 in my case).

If you still encounter problems, you may need to reach out to Cognito on the forums [here](https://forums.aws.amazon.com/forum.jspa?forumID=173). They should be able to provide more insight on what is causing your call to fail.

```javascript
/* Lambda Function */
'use strict';
const AWS = require('aws-sdk');

exports.handler = (event, context, callback) => {
    AWS.config.update({
        region: 'us-west-2'
    });
    const provider_name = 'CUSTOM';
    const params = {
        IdentityPoolId: 'ID',
        Logins: {
            [provider_name]: 'test'
        }
    };
    
    const cognito = new AWS.CognitoIdentity({apiVersion: '2014-06-30'});
    return cognito.getOpenIdTokenForDeveloperIdentity(params).promise()
        .then((data) => {
            console.log(JSON.stringify(data, null, 4));
            callback(null, data);
        }).catch((err) => {
            console.log(err, err.stack);
            callback(err);
        });
};

```

**Comment by napcoder** [comment] 2017-09-14 21:42
@chrisradek thank you for suggestion. Just created lambda and pasted your code directly on lambda web interface, using my IAM role, and replacing my connection pool id and provider name. It seems to work properly. This means the problem is somewhere in the code or in serverless framework.

**Comment by chrisradek** [comment] 2017-09-14 21:47
@napcoder 
Glad to hear that's working! In that case, I'm going to close this issue. Feel free to re-open or make a new issue if you discover something wrong with the SDK.

**Closed by chrisradek** 2017-09-14 21:47 UTC
Labels: Question, Service / API

**Comment by napcoder** [comment] 2017-09-14 22:56
Solved: the problem was due to a wrong endpoint in the AWS general config, loaded by my dynamodb data layer
