### ISSUE TITLE
S3 ManagedUpload callback not being called sometimes

### ISSUE THREAD

**Issue by balmasi** [aws/aws-sdk-js#576] opened 2015-04-14 17:44 UTC
Whenever I'm uploading files larger than around *1MB* using streams with the s3 sdk, when listening to the progress events I see it reaching *100% * but the callback on the `ManagedUpload.send` function doesn't get called. It waits like that for like 30 seconds and retries. Sometimes this loop goes on forever, other times it calls the callback successfully.

This is a simplified version of the code I'm using
```javascript
var Uploader = new aws.S3.ManagedUpload({ params: { ... Body: stream } });

Uploader.on('httpUploadProgress', function(evt) {
console.log('%s: %d',fileName, evt.loaded*100/evt.total);
});

Uploader.send(function(err, s3res) {    /// <--- ManagedUpload.send callback VERY LATE
  console.log('done');
});
```

Which generates this output

```
Photo.jpg: 12.87913625519304
Photo.jpg: 19.318704382789562
Photo.jpg: 25.75827251038608
Photo.jpg: 32.1978406379826
Photo.jpg: 38.637408765579124
Photo.jpg: 45.07697689317565
Photo.jpg: 51.51654502077216
Photo.jpg: 57.956113148368686
Photo.jpg: 64.3956812759652
Photo.jpg: 70.83524940356173
Photo.jpg: 77.27481753115825
Photo.jpg: 83.71438565875476
Photo.jpg: 90.1539537863513
Photo.jpg: 96.59352191394781
Photo.jpg: 100
*------- STALLS FOR 30 SECONDS ------*
Photo.jpg: 6.43956812759652
Photo.jpg: 12.87913625519304
Photo.jpg: 19.318704382789562
Photo.jpg: 25.75827251038608
Photo.jpg: 32.1978406379826
Photo.jpg: 38.637408765579124
Photo.jpg: 45.07697689317565
Photo.jpg: 51.51654502077216
Photo.jpg: 57.956113148368686
Photo.jpg: 64.3956812759652
Photo.jpg: 70.83524940356173
Photo.jpg: 77.27481753115825
Photo.jpg: 83.71438565875476
Photo.jpg: 90.1539537863513
Photo.jpg: 96.59352191394781
Photo.jpg: 100

ManagedUpload Send Callback Called
```
Could this have something to do with streams and backpressure (I don't see that being handled anywhere in the nodejs code)?

For the record Im using **Node v0.10.32** and **aws-sdk-js 2.1.23**

**Comment by lsegal** [comment] 2015-04-15 17:49
> Could this have something to do with streams and backpressure (I don't see that being handled anywhere in the nodejs code)?

You could find out if this is related to streams by loading the photo into memory as a test using:

```js
var buf = fs.readFileSync('./path/to/Photo.jpg');
var Uploader = new aws.S3.ManagedUpload({ params: { ... Body: buf } });
// ...
```

Let us know if you run into any different behavior.

As a sidenote, does this happen consistently? If not, how often does it happen?

**Comment by dconnolly** [comment] 2015-04-30 00:00
Related: if the input body is size 0, the callback is never called, because nextChunk() is never called. I would expect he callback to be called with an err value. I can create a separate issue for this specific case.

**Comment by AdityaManohar** [comment] 2015-05-15 21:29
@balmasi would you be able to verify if you still see this issue with `v2.1.28` of the SDK? 

There were a couple of related fixes and performance improvements in `AWS.S3.ManagedUpload` that landed in `v2.1.28`.

**Comment by balmasi** [comment] 2015-05-18 23:21
@lsegal Actually I ended up HAVING TO use in-memory buffer to bypass this problem.
@AdityaManohar I'll let you know as soon as I test it.

**Comment by AdityaManohar** [comment] 2015-06-29 21:07
@balmasi I was wondering if you had a chance to see if the problem still persists after upgrading the SDK to `v2.1.28` or higher?

**Comment by AdityaManohar** [comment] 2015-07-08 21:39
@balmasi I'm marking this as closed as we haven't been able to reproduce the issue. I would recommend upgrading to `v2.1.28` of the SDK. Feel free to reopen this issue or open another issue if you still notice this behavior after you upgrade.

**Closed by AdityaManohar** 2015-07-08 21:39 UTC
Labels: Feedback Requested

**Comment by virtuotechnologies** [comment] 2018-09-12 13:28
s3.upload({ Key: "something/"+ this.files[0]._file.name, Bucket: bucketName, Body: file, ACL: 'public-read'}, function (err, data) {
          if (err) {
             console.log(err, 'there was an error uploading your file');
          }
     var pname = data.Location;
     var C_IMAGE = {"CATEGORY_IMAGE": pname}
      <??? this.service.updatecategory(cid, this.at, C_IMAGE).subscribe(udata => {
        console.log("Sucess",udata);
     });???>
});

**Comment by virtuotechnologies** [comment] 2018-09-12 13:32
s3.upload({ Key: "something/"+ this.files[0]._file.name, Bucket: bucketName, Body: file, ACL: 'public-read'}, function (err, data) {
     if (err) {
       console.log(err, 'there was an error uploading your file');
     }
     var pname = data.Location;
     var C_IMAGE = {"CATEGORY_IMAGE": pname};
     var scope = this;
     <??scope.service.updatecategory(cid, scope.at, C_IMAGE).subscribe(udata => {
        console.log("Sucess",udata);
     });??>
    });

---in console <????> inside this function is said undefined. Please tell how to uplaod the location.

**Comment by virtuotechnologies** [comment] 2018-09-12 13:33
s3.upload({ Key: "something/"+ this.files[0]._file.name, Bucket: bucketName, Body: file, ACL: 'public-read'}, function (err, data) {
if (err) {
console.log(err, 'there was an error uploading your file');
}
var pname = data.Location;
var C_IMAGE = {"CATEGORY_IMAGE": pname};
var scope = this;
<??scope.service.updatecategory(cid, scope.at, C_IMAGE).subscribe(udata => {
console.log("Sucess",udata);
});??>
});

---in console inside this function is said undefined. Please tell how to uplaod the **location.******

**Comment by virtuotechnologies** [comment] 2018-09-12 13:36
s3.upload({ Key: "something/"+ this.files[0]._file.name, Bucket: bucketName, Body: file, ACL: 'public-read'}, function (err, data) {
if (err) {
console.log(err, 'there was an error uploading your file');
}
var pname = data.Location;
var C_IMAGE = {"CATEGORY_IMAGE": pname};
var scope = this;
**scope.service.updatecategory(cid, scope.at, C_IMAGE).subscribe(udata => {
console.log("Sucess",udata);
});**
});

---in console  this bolded function is said undefined. Please tell how to uplaod the location.
