### ISSUE TITLE
ReferenceError in SageMaker invokeEndpointWithResponseStream

### ISSUE THREAD

**Issue by cshen-dev** [aws/aws-sdk-js#4580] opened 2024-02-02 00:46 UTC
### Describe the bug

I created an AWS SageMaker endpoint with Mistral Jumpstarter (jumpstart-dft-hf-llm-mistral-7b-ins-20240130).

`sagemakerRuntime.invokeEndpoint` worked as a charm however when I started exploring its stream capability, I met the issue below.

```console
Error [ReferenceError]: payload is not defined
    at Request.extractData (/Users/c.shen/Workspaces/tmp/sagemaker/node_modules/aws-sdk/lib/protocol/rest_json.js:78:17)
    at Request.callListeners (/Users/c.shen/Workspaces/tmp/sagemaker/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/c.shen/Workspaces/tmp/sagemaker/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/c.shen/Workspaces/tmp/sagemaker/node_modules/aws-sdk/lib/request.js:686:14)
    at Request.transition (/Users/c.shen/Workspaces/tmp/sagemaker/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/c.shen/Workspaces/tmp/sagemaker/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/c.shen/Workspaces/tmp/sagemaker/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/c.shen/Workspaces/tmp/sagemaker/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/c.shen/Workspaces/tmp/sagemaker/node_modules/aws-sdk/lib/request.js:688:12)
    at Request.callListeners (/Users/c.shen/Workspaces/tmp/sagemaker/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'ReferenceError',
  time: 2024-02-02T00:39:53.693Z,
  statusCode: 200,
  retryable: false,
  retryDelay: 62.00239553897755
}
```

### Expected Behavior

```console
[ReferenceError]: payload is not defined
```

^ This error should not occur which I guess is caused by mis-mapped data structure between SageMaker endpoint's Response and the sdk client's Request.

### Current Behavior

It's throwing error and block the downstream processing

### Reproduction Steps

1. Set up a SageMaker endpoint
2. Use the code block below (which is actually from AWS official doc)
```js
// In Node.js, events are streamed and can be read as they arrive.
sagemakerruntime.invokeEndpointWithResponseStream({/** params **/}, function(err, data) {
  if (err) {
    // handle error
    return console.error(err);
  }

  var eventStream = data.Body;

  eventStream.on('data', function(event) {
    // Check the top-level field to determine which event this is.
    if (event.PayloadPart) {
      // handle PayloadPart event
    } else if (event.ModelStreamError) {
      // handle ModelStreamError event
    } else if (event.InternalStreamFailure) {
      // handle InternalStreamFailure event
    }
  });
  eventStream.on('error', function(err) { /** Handle error events **/});
  eventStream.on('end', function() { /** Finished reading all events **/});
});
```

### SDK version used

2.1549.0

### Environment details (OS name and version, etc.)

macos

**Comment by aBurmeseDev** [comment] 2024-02-13 00:56
Hi @cshen-dev - thanks for reaching out.

I’m trying to understand if the error you’re getting is actually related to SDK because it seems like a generic JavaScript error. Can you share your code where you’re making client request with SDK? Are you defining the “payload” somewhere?

I’d be happy to further investigate once you share more information requested.
Best,
John

**Comment by inf3rnus** [comment] 2024-03-08 22:06
FYI @cshen-dev I've created a fix for this with https://github.com/aws/aws-sdk-js/pull/4607, pending Amazon's evaluation of the change.

In the meantime you can pull my fork @ https://github.com/inf3rnus/aws-sdk-js

**Comment by rjvgupta** [comment] 2024-03-11 21:12
Here's a simple repro using 2 lambda functions:
lambda1:
```
var AWS = require("aws-sdk")
AWS.config.update({region: 'us-east-1'}); 
var lambda = new AWS.Lambda();

exports.handler = async (event) => {
  var params = {
    FunctionName: 'lambda2', 
    InvocationType: 'RequestResponse',
    LogType: 'Tail',
    Payload: JSON.stringify({message: 'Do Nothing.'})
  };
        
  const result = await lambda.invokeWithResponseStream(params).promise();
  const events = result.EventStream;
  for await (const event of events) {
    if (event.PayloadChunk) {
      console.log(event.PayloadChunk);
    } 
  }
  
  const response = {
    statusCode: 200,
    body: JSON.stringify('Hello from Lambda!'),
  };
  return response;
};
```
lambda2:
```
exports.handler = awslambda.streamifyResponse(async (event, responseStream, _context) => {
  responseStream.write('message1');
  responseStream.write('message2');
  responseStream.write('message3');
  responseStream.end();
});
```

**Comment by aBurmeseDev** [comment] 2024-03-15 00:04
Hi everyone on the thread, appreciate all your effort into this behavior. 

I was able to reproduce this and will be further looking into it with the team. Will post once we have updates.

**Comment by rjvgupta** [comment] 2024-03-21 18:15
@siddsriv / @aBurmeseDev - any update?

**Comment by inf3rnus** [comment] 2024-03-22 02:42
@rjvgupta if you're only using this part of the AWS sdk, v3 of the sdk solves this problem, and consuming the output of it is a lot easier.

e.g.
```js
  const { Body } = await sageMakerRuntimeClient.send(
    new InvokeEndpointWithResponseStreamCommand(params)
  );

  const readStream = Readable.from(Body);

  readStream.on("error", error => {
    console.error(`Sagemaker endpoint error: ${endpointName}`, error);
    readStream.emit("end");
  });

  const transformStream = createTransform();

  readStream.pipe(transformStream);

  return transformStream;
}

function createTransform() {
  const transformStream = new Transform({
    readableObjectMode: false, // Output should be Buffers or strings
    writableObjectMode: true, // Input will be objects,
    transform({ PayloadPart: { Bytes } = {} } = {}, encoding, callback) {
      const text = Buffer.from(Bytes)?.toString() ?? "";
      // Push the transformed data to the next handler in the stream
      this.push(text);
      callback();
    }
  });

  return transformStream;
}
```

**Comment by rjvgupta** [comment] 2024-03-22 14:38
Hey Aaron, thanks for following up on this.  I was able to try w/ v3 and can confirm, that it worked without needing to override the SDK with my changes.  This is a reasonable workaround, but will take some work to modify the v2 code to v3 and think we should deploy the fix requested.

Thank You,
Rajiv Gupta

Manager, Analytics Specialist Solutions Architects
p: 949-296-5163 | e: ***@***.******@***.***>
Thoughts on our interaction? Provide feedback here<https://feedback.aws.amazon.com/?ea=rjvgupta&fn=Rajiv&ln=Gupta>.


From: Aaron V ***@***.***>
Reply-To: aws/aws-sdk-js ***@***.***>
Date: Thursday, March 21, 2024 at 7:43 PM
To: aws/aws-sdk-js ***@***.***>
Cc: "Gupta, Rajiv" ***@***.***>, Mention ***@***.***>
Subject: Re: [aws/aws-sdk-js] ReferenceError in SageMaker invokeEndpointWithResponseStream (Issue #4580)


@rjvgupta<https://github.com/rjvgupta> if you're only using this part of the AWS sdk, v3 of the sdk solves this problem, and consuming the output of it is a lot easier.

e.g.

  const { Body } = await sageMakerRuntimeClient.send(

    new InvokeEndpointWithResponseStreamCommand(params)

  );



  const readStream = Readable.from(Body);



  readStream.on("error", error => {

    console.error(`Sagemaker endpoint error: ${endpointName}`, error);

    readStream.emit("end");

  });



  const transformStream = createTransform();



  readStream.pipe(transformStream);



  return transformStream;

}



function createTransform() {

  const transformStream = new Transform({

    readableObjectMode: false, // Output should be Buffers or strings

    writableObjectMode: true, // Input will be objects,

    transform({ PayloadPart: { Bytes } = {} } = {}, encoding, callback) {

      const text = Buffer.from(Bytes)?.toString() ?? "";

      // Push the transformed data to the next handler in the stream

      this.push(text);

      callback();

    }

  });



  return transformStream;

}

**Comment by inf3rnus** [comment] 2024-03-22 19:04
@rjvgupta np, and yeah, I agree. Ended up having to migrate to v3 myself because I ran into another problem where the deleteEndpoint method wouldn't actually delete endpoints, which means there's almost certainly other problems lurking.

**Closed** 2024-05-23 16:03 UTC
Labels: bug, p3, queued
