### ISSUE TITLE
Label question, question

### ISSUE THREAD

**Issue by optimisme** [aws/aws-sdk-js#1415] opened 2017-03-20 08:58 UTC
Is label 'question' a way to ignore reported bugs?

**Comment by jeskew** [comment] 2017-03-20 17:50
It is not. The `Bug` label is used when we can confirm that there is a bug in the SDK or a bug that can be fixed by a code change to the SDK. When it is unclear that any remedy is available to the SDK -- for instance, when we're unsure if the issue is how the SDK interacts with a third-party library not listed as an SDK dependency -- more investigation is required before something can be labeled a bug or not a bug.

I think the point you're trying to make is that we could be faster in relabeling issues, which is fair. Typically, once an issue has a label, we don't relabel it unless the requester makes the case that the issue has been mislabeled. With the exception of the `Bug` label, labels do not factor into how we prioritize issues but are instead there to provide context for SDK contributors. 

I'll go ahead and apply an `in progress` tag to #1385, as it's being looked at but isn't really a question.

**Closed by jeskew** 2017-03-20 17:50 UTC
Labels: Question
