### ISSUE TITLE
[react-native] JavaScript heap out of memory when importing "aws-sdk"

### ISSUE THREAD

**Issue by talaikis** [aws/aws-sdk-js#3942] opened 2021-11-03 20:26 UTC
- [x ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
- [ ] This is an issue with version 2.x of the SDK

**Describe the bug**

out of memory having aws-sdk in a react native project for iOS. It's with 8 Gb of memory, other solutions like excluding the file or pathing `Buffer.TYPED_ARRAY_SUPPORT` does nothing.

**SDK version number**

2.998.0

**To Reproduce (observed behavior)**

1. create react-native project
2. import aws-sdk
3. npn run ios
4. wait for out of memory and final aws-sdk error

**Expected behavior**

Should work without problems.

**Comment by cgrady3** [comment] 2021-11-09 21:28
I'm also getting this issue. call retries exceeded for aws-sdk-react-native.js

**Comment by ajredniwja** [comment] 2021-11-22 16:11
@talaikis thanks for opening this issue, the issue is most likely not related to the SDK itself. More discussed about it in https://github.com/aws/aws-sdk-js/issues/2370
The workaround mentioned in the discussion was to increase the stack size, see if that works? 
I would also recommend using the [V3 of the SDK](https://github.com/aws/aws-sdk-js-v3) which I have personally used recently and is amazing for its modularity. 

I'll close this issue now, feel free to reach out if you think its related to SDK.

**Closed** 2021-11-22 16:11 UTC
Labels: bug, needs-triage
