### ISSUE TITLE
aws-sdk-js/react-native android network issue

### ISSUE THREAD

**Issue by peterdev6** [aws/aws-sdk-js#1490] opened 2017-04-28 18:18 UTC
<img width="339" alt="screen shot 2017-04-28 at 2 10 33 pm" src="https://cloud.githubusercontent.com/assets/26579337/25541491/d3c25d4e-2c1c-11e7-98a5-df5daeb6111e.png">
I am using aws-sdk-js/react-native branch to collect user data with aws mobile analytics service. Everything works fine with IOS. But for android for some reason XMLHttpRequest doesn't work.

Any help is appreciated.

**Comment by chrisradek** [comment] 2017-04-28 19:32
@peterdev6 
Can you share a snippet of how you're calling the operation?

**Comment by peterdev6** [comment] 2017-04-28 20:01
@chrisradek I am using [aws-sdk-mobile-analytics-js](https://github.com/aws/aws-sdk-mobile-analytics-js) to create a mobileAnalyticsClient and I am sending custom events like this: `mobileAnalyticsClient.recordEvent('MainPageLoaded', {
     'attribute_1': 'main',
     'attribute_2': 'page'
    }, {
     'metric_1': 1
    });`
According to aws android sdk, I also added 
`<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />` to AndroidManifest.xml file.

**Comment by chrisradek** [comment] 2017-04-28 22:03
@peterdev6 
I've narrowed down the issue. It looks like the react native XmlHttpRequest implementation for iOS automatically populates the Content-Type header when a request has a body and the header hasn't been provided, but the implementation for Android does not. That's probably something that should be fixed on react native's side so both environments have consistent behavior, but we'll explore what can safely be done on our end as well.

As a temporary work-around, the following should help. Just add it before you start calling the mobile analytics sdk. It will add the content-type header when a body exists:
```javascript
AWS.MobileAnalytics.prototype.customizeRequests(function(req) {
    req.on('build', function() {
        if (req.httpRequest.body) {
            req.httpRequest.headers['Content-Type'] = 'application/json';
        }        
    });
});
```

**Comment by peterdev6** [comment] 2017-04-29 03:18
@chrisradek Thank you so much for your help. It works perfectly now.

**Comment by spoeck** [comment] 2017-05-02 12:34
@peterdev6 
Can you explain how do you implemented the aws-sdk-js and the aws-sdk-mobile-analytics-js in React Native?
I want to do the same but my custom event won't be send without any error message.

**Comment by peterdev6** [comment] 2017-05-02 13:41
@spoeck I followed the installation instructions of aws-sdk-js react-native branch but I didnt install aws-sdk-mobile-analytics library via npm, instead I extracted the source files and used them locally coz I had trouble importing it and I could not prevent typescript complaining about node type errors(i'm using typescript for type checking instead of flow).
Can you show your error messages and explain how you are using these two libraries?

**Comment by spoeck** [comment] 2017-05-02 14:08
@peterdev6 Thanks for your reply!

Now I installed aws-sdk-mobile-analytics also without npm, but still no success.

```
import AWS from "aws-sdk/dist/aws-sdk-react-native"; // npm as usual
import AMA from "../lib/aws-sdk-mobile-analytics-js-master/lib/ama"; // local path

 _initAWS() {
        AWS.config.region = 'us-east-1';
        AWS.config.credentials = new AWS.CognitoIdentityCredentials({
            IdentityPoolId: "eu-central-1:426xxxxx-xxxx-xxxxxx-xxxxxxxxx"  
        });

        var options = {
            appId : "axx520b5xxxxxxxxx3xxcxxxxxxxx", 
        };
        let mobileAnalyticsClient = new AMA.Manager(options);

        mobileAnalyticsClient.recordEvent('MainPageLoaded', { 'attribute_1': 'main', 'attribute_2': 'page' }, { 'metric_1': 1 });
        mobileAnalyticsClient.submitEvents();
}

```

I don't get an error. Do you know how to turn on logging for aws-sdk-js?

**Comment by peterdev6** [comment] 2017-05-02 14:29
you need to specify in the options the platform for data to display on aws dashboard and logger for logging. Here is an example:
```
const options = {
    appId : '...',
    platform : Platform.OS === 'ios' ? 'iPhoneOS' : 'Android',
    logger: console
}
```
Also you don't need to call submitEvents manually, mobileanalyticsclient is submitting events automatically.

Note that you may need to change the imports of some of the source files for aws-sdk-mobile-analytics library. This is the structure of all the source files i have locally.
<img width="255" alt="screen shot 2017-05-02 at 10 26 40 am" src="https://cloud.githubusercontent.com/assets/26579337/25622278/eacfd7ac-2f21-11e7-92c6-4858c206fec4.png">

**Comment by spoeck** [comment] 2017-05-02 16:59
@peterdev6 
I just changed the import of the aws-sdk in MobileAnalyticsClient.js to
```
//import AWS from "aws-sdk/dist/aws-sdk-react-native";
var AWS = require('../node_modules/aws-sdk/dist/aws-sdk-react-native');
var AMA = global.AMA;
```
Could you show me your import for the aws-sdk in the MobileAnalyticsClient.js?

**Comment by peterdev6** [comment] 2017-05-02 17:51
@spoeck Are you getting any errors now?

**Comment by spoeck** [comment] 2017-05-02 21:44
It works now!!!!
@peterdev6 Thanks for your input :)

I created a demo under:
https://github.com/spoeck/react-native-aws-mobile-analytics-demo

**Comment by alvelig** [comment] 2017-05-16 03:46
@chrisradek How can adding header to AWS.Lambda can be achieved?
I've tried:
```
lambda
  .invoke(params, callback)
  .on('build', function(req) { 
     req.httpRequest.headers['Content-Type'] = 'application/json'; 
  })
```
But this seems to me an unstable solution.

Could you please give me an idea?

**Comment by chrisradek** [comment] 2017-05-16 15:50
@alvelig 
Just to confirm, are you only seeing an issue in Android? Not iOS?

I'm surprised you needed to add the 2nd listener. Were you getting a Buffer back before?

**Comment by alvelig** [comment] 2017-05-16 16:16
@chrisradek Android only. The same symptoms as stated above. 
I'm not so deep in the library. Maybe that happens because I use https://github.com/AirLabsTeam/react-native-aws-cognito-js (Advanced example from README.MD).

If you need, this weekend I'll try to make an example reproducing the error.

**Comment by chrisradek** [comment] 2017-05-22 03:45
@alvelig 
I put up PR #1517 that should address the issue you're seeing. I made sure to test with `lambda.invoke` with a payload as well.

**Closed** 2017-05-22 16:54 UTC
Labels: in progress, Question
