### ISSUE TITLE
Feature Request: Add Mechanical Turk SDK support

### ISSUE THREAD

**Issue by loretoparisi** [aws/aws-sdk-js#1222] opened 2016-11-11 18:07 UTC
The AmazonMechanicalTurk is available in [few](https://requester.mturk.com/developer/tools/) SDKs community supported, but there is no official Nodejs support.
Any plans to add?

**Comment by jeskew** [comment] 2016-12-09 20:39
We don't have any immediate plans to add support for Amazon Mechanical Turk to the AWS SDK for JavaScript, but I'll mark this as a feature request. In the meantime, there are a few community-supported modules for using mechanical turk from a node application available [on NPM](https://www.npmjs.com/search?q=mturk).

**Comment by jeskew** [comment] 2016-12-27 22:39
Closing as a duplicate of #111.

**Closed by jeskew** 2016-12-27 22:39 UTC
Labels: Duplicate, Feature Request
