### ISSUE TITLE
Unrecognized archive format when trying to update to version 2.778.0

### ISSUE THREAD

**Issue by raghda94** [aws/aws-sdk-js#3513] opened 2020-10-26 12:47 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
getting npm verb stack Error: TAR_BAD_ARCHIVE: Unrecognized archive format when trying to fetch https://registry.npmjs.org/aws-sdk/-/aws-sdk-2.778.0.tgz when doing npm update

**Details of the browser/Node.js version**
node version 15.0.1, npm v 7.0.3

**SDK version number**
 v2.778.0

**Comment by ajredniwja** [comment] 2020-10-28 23:16
Hey @raghda94, thanks for opening this, I was not able to reproduce this with `npm -v 6.14.8` which was installed using `npm install -g npm@next` with that said I would say this is not likely an issue with JS-SDK but NPM can you please open an issue at https://github.com/npm/cli/issues

Closing this as it is not related to the JS-SDK

Please reach out if you have any questions.

**Closed by ajredniwja** 2020-10-28 23:16 UTC
Labels: bug, needs-triage
