### ISSUE TITLE
When no credentials exist the error is irrelevant and it takes a long time to fail.

### ISSUE THREAD

**Issue by patrobinson** [aws/aws-sdk-js#3202] opened 2020-04-08 00:18 UTC
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When no credentials are configured on my laptop, the sdk takes 2.5 minutes to fail and returns an obscure error message:
```
/private/tmp $ time node index.js

Error: connect ETIMEDOUT 169.254.169.254:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)

real	2m30.906s
user	0m0.265s
sys	0m0.037s
```

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
v13.11.0

**SDK version number**
v2.655.0

**To Reproduce (observed behavior)**
https://gist.github.com/patrobinson/7934bc6b834694d7b9205eb663c29157

**Expected behavior**
As with the Ruby SDK and others, it should fail faster and with a helpful error message.
In Ruby you get:
```
Aws::Errors::MissingCredentialsError (unable to sign request without credentials set)
```

**Comment by ajredniwja** [comment] 2020-04-08 00:55
Hey @patrobinson thank-you for reaching out to us with your issue, this is not necessarily a bug with the SDK. 

A duplicate of https://github.com/aws/aws-sdk-js/issues/2983, please refer to the comments there.

Closing this issue now since it will be tracked with https://github.com/aws/aws-sdk-js/issues/2983

Reach out if you have any questions.

**Closed by ajredniwja** 2020-04-08 00:55 UTC
Labels: bug, needs-triage
