### ISSUE TITLE
Marshalled data returned from CallAwsService DynamoDB query has incorrect casing in type names

### ISSUE THREAD

**Issue by Bee-Taylor** [aws/aws-sdk-js#4294] opened 2022-12-01 15:38 UTC
### Describe the bug

When running the step function task CallAwsService to query a database in dynamodb, the returned items have incorrect casing in type names. More specifically, `"BOOL"` is returned as `"Bool"` which means the included unmarshall function throws an error

### Expected Behavior

When running CallAwsService to query a db, it should return data in the form:
```JSON
{
  "Items": [
    {
      "example": {
        "BOOL": true
      }
    }
  ]
}
```

### Current Behavior

When running CallAwsService to query a db, it returns:
```JSON
{
  "Items": [
    {
      "example": {
        "Bool": true
      }
    }
  ]
}
```

### Reproduction Steps

The following step function:
```JSON
{
  "StartAt": "DBQuery",
  "States": {
    "DBQuery": {
      "End": true,
      "Type": "Task",
      "Resource": "arn:aws:states:::aws-sdk:dynamodb:query",
      "Parameters": {
        "TableName": "{tablename}",
        "KeyConditionExpression": "#{key} = :{key}",
        "ExpressionAttributeNames": {
          "#{key}": "{key}"
        },
        "ExpressionAttributeValues": {
          ":scopeId": {
            "S.$": "$.path.{key}"
          }
        },
        "IndexName": "{indexname}"
      }
    }
  },
  "TimeoutSeconds": 300
}
```
 Replacing tablename with an existing table, key with the partition key of a gsi, indexname with the name of a gsi on the table, giving it the necessary permissions, and running with payload:
```JSON
{
  "path": {
    "{key}": "{value}"
  }
}
```

### Possible Solution

I imagine this should be a case of changing a hardcoded value from Bool to BOOL  somewhere in the codebase, but if not, if the unmarshall function was able to deal with typenames insensitive of casing, that would also fix the problem

### SDK version used

Unsure, probably latest

### Environment details (OS name and version, etc.)

Called from a step function

**Comment by ajredniwja** [comment] 2022-12-02 21:23
Hey @Bee-Taylor thanks for opening this issue can you please share the code you are using and please confirm the version of the SDK as well?

**Comment by Bee-Taylor** [comment] 2022-12-06 08:55
Hi, so since this is calling SDK from step functions I'm not 100% sure if this is the right repo to ask this in, feel free to send me to a different repo if not

The dynamodb query operation is called from a step function defined in CDK, like:
```TypeScript
  return new CallAwsService(scope, `${id}-ddbQuery`, {
    service: 'DynamoDB',
    action: 'query',
    parameters: {
      TableName: table.tableName,
      ...parameters,
    },
    iamResources: [table.tableArn, ...(IndexName ? [`${table.tableArn}/index/${IndexName}`] : [])],
    iamAction: 'dynamodb:Query',
  })
```
Where Table is a dynamodb table, and indexname is the name of a gsi on that table

In terms of versions, these are my was versions in package.json:
```JSON
    "aws-cdk": "^2.31.2",
    "aws-cdk-lib": "^2.31.2",
    "@aws-sdk/client-dynamodb": "^3.204.0",
    "@aws-sdk/lib-dynamodb": "^3.204.0",
    "@aws-sdk/util-dynamodb": "^3.204.0",
```

**Comment by JoeWHoward** [comment] 2023-06-07 15:26
+1 for this, we just ran into it.  Specifically when querying a DynamoDB table from the native step function action (resource `arn:aws:states:::aws-sdk:dynamodb:query`) we receive a marshalled DDB object in which top-level attributes are "BOOL" but any booleans nested in a map are "Bool".

We got around this by casting type/marshall attributes to uppercase in a custom implementation of the unmarshalling function.

**Comment by dparish** [comment] 2024-03-01 21:38
Good god this is dumb. I have to write an intermediate layer to turn Bool to BOOL and Nul to NULL. Please fix this.

Step functions have enough quirks. This one is just ridiculous.

**Comment by aBurmeseDev** [comment] 2024-08-29 00:08
Hi everyone - apologies for the delay in responding.

First, I'd like to clarify that this issue is related to AWS Step Functions and not directly related to the AWS SDK.

I have investigated this internally, and a report was submitted to the service team. Here's their response:

> This's expected behavior that we documented here: https://docs.aws.amazon.com/step-functions/latest/dg/supported-services-awssdk.html 
As this is expected behavior, there's not much we can do for this particular issue at the moment. This behavior is present in both our optimized integrations for DDB as well as our AWS SDK integrations.

Since there's no action item for SDK team, I'm going to close this. Please feel free to reach out service team directly via [AWS Support](https://aws.amazon.com/contact-us/).

**Closed by aBurmeseDev** 2024-08-29 00:08 UTC
Labels: service-api, bug, p2

**Comment by cadam11** [comment] 2024-11-19 17:55
> Hi everyone - apologies for the delay in responding.
> 
> First, I'd like to clarify that this issue is related to AWS Step Functions and not directly related to the AWS SDK.
> 
> I have investigated this internally, and a report was submitted to the service team. Here's their response:
> 
> > This's expected behavior that we documented here: [docs.aws.amazon.com/step-functions/latest/dg/supported-services-awssdk.html](https://docs.aws.amazon.com/step-functions/latest/dg/supported-services-awssdk.html)
> > As this is expected behavior, there's not much we can do for this particular issue at the moment. This behavior is present in both our optimized integrations for DDB as well as our AWS SDK integrations.
> 
> Since there's no action item for SDK team, I'm going to close this. Please feel free to reach out service team directly via [AWS Support](https://aws.amazon.com/contact-us/).

Hi @aBurmeseDev – thanks for your response and confirmation that Step Functions will not be updated.

As a broader workaround for the entire community, I'd like to suggest treating `Bool` and `Nul` as aliases in the [`convertToNative`](https://github.com/GoPro16/aws-sdk-js-v3/blob/feat/optional-set/packages/util-dynamodb/src/convertToNative.ts) function. I'd be happy to open a PR (and/or create a fresh issue) to add this feature to the SDK.
