### ISSUE TITLE
Missing required key 'Bucket' in params

### ISSUE THREAD

**Issue by JacobEvelyn** [aws/aws-sdk-js#531] opened 2015-03-12 16:04 UTC
I haven't been able to pin down when this issue happens, but I've got code (in the browser) looking something like this:

```
var s3 = new AWS.S3({
  sslEnabled: true,
  accessKeyId: "XXX",
  secretAccessKey: "XXX"
});

var key = randomKey();

var params = {
  Body: file,
  ContentType: file.type,
  Key: key,
  ACL: "private",
  Bucket: "mybucket",
  ServerSideEncryption: "AES256",
  StorageClass: "STANDARD"
};

console.log(params);

s3.upload(params, function (err, data) { ... });
```

I receive `Missing required key 'Bucket' in params` errors in the console when this code runs. The strange thing is, the files save to S3 successfully, and the `params` that I log do indeed include the `Bucket` argument.

What's going on? I have very similar code on other pages and haven't seen this error there at all.

**Comment by AdityaManohar** [comment] 2015-03-12 23:55
@JacobEvelyn 
What is the size of the file you are uploading? Also which version of the SDK are you using? This information will help debug the issue.

**Comment by JacobEvelyn** [comment] 2015-03-13 14:19
That page handles fairly small files—60 KB for one I'm seeing it on. I'm using version 2.1.15.

Is there particular network information you're looking for? I'm seeing:

Request:
```
OPTIONS https://s3.amazonaws.com/mybucket/path/in/s3/142625520387278wqrc6udfc.png
Host: s3.amazonaws.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:36.0) Gecko/20100101 Firefox/36.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Origin: http://admin.lvh.me:3001
Access-Control-Request-Method: PUT
Access-Control-Request-Headers: authorization,content-type,x-amz-acl,x-amz-date,x-amz-server-side-encryption,x-amz-storage-class,x-amz-user-agent
Connection: keep-alive
```

Response:
```
200 OK
Access-Control-Allow-Origin: "*"
Content-Length: "0"
Date: "Fri, 13 Mar 2015 14:05:25 GMT"
Server: "AmazonS3"
Vary: "Origin, Access-Control-Request-Headers, Access-Control-Request-Method"
access-control-allow-headers: "authorization, content-type, x-amz-acl, x-amz-date, x-amz-server-side-encryption, x-amz-storage-class, x-amz-user-agent"
access-control-allow-methods: "PUT, POST"
access-control-expose-headers: "ETag"
x-amz-id-2: "..."
x-amz-request-id: "..."
```

Request:
```
PUT https://s3.amazonaws.com/mybucket/path/in/s3/1426255544594vsnh7ruh09.png
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:36.0) Gecko/20100101 Firefox/36.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
X-Amz-User-Agent: aws-sdk-js/2.1.15
x-amz-acl: private
Content-Type: image/png
x-amz-server-side-encryption: AES256
x-amz-storage-class: STANDARD
X-Amz-Date: Fri, 13 Mar 2015 14:05:44 GMT
Authorization: AWS ...
Referer: http://admin.lvh.me:3001/upload_page
Content-Length: 59570
Origin: http://admin.lvh.me:3001
Connection: keep-alive
```

Response:
```
200 OK
Access-Control-Allow-Origin: "*"
Content-Length: "0"
Date: "Fri, 13 Mar 2015 14:05:25 GMT"
Etag: ""...""
Server: "AmazonS3"
Vary: "Origin, Access-Control-Request-Headers, Access-Control-Request-Method"
access-control-allow-methods: "PUT, POST"
access-control-expose-headers: "ETag"
x-amz-id-2: "..."
x-amz-request-id: "..."
x-amz-server-side-encryption: "AES256"
```

**Comment by AdityaManohar** [comment] 2015-03-13 18:27
I'd be interested in the network logs of the request that is failing. For what threshold of object sizes do you notice failures? FWIW, I'd recommend upgrading to `v2.1.16` or above.

I've tried to reproduce it with a large object (~50M) and I have been unable to do so.

**Comment by JacobEvelyn** [comment] 2015-03-13 19:38
Sorry for being unclear in my original description... there *is* no failing request. It works perfectly, except for the fact that I get this message in the console:

```
MissingRequiredParameter: Missing required key 'Bucket' in params
Stack trace:
[21]</t.ParamValidator<.fail@https://sdk.amazonaws.com/js/aws-sdk-2.1.15.min.js:6:916
[21]</t.ParamValidator<.validateStructure@https://sdk.amazonaws.com/js/aws-sdk-2.1.15.min.js:5:31539
[21]</t.ParamValidator<.validateMember@https://sdk.amazonaws.com/js/aws-sdk-2.1.15.min.js:5:31893
[21]</t.ParamValidator<.validate@https://sdk.amazonaws.com/js/aws-sdk-2.1.15.min.js:5:31030
[10]</t.EventListeners.Core</<@https://sdk.amazonaws.com/js/aws-sdk-2.1.15.min.js:5:10653
[34]</r.SequentialExecutor<.callListeners@https://sdk.amazonaws.com/js/aws-sdk-2.1.15.min.js:6:27776
n@https://sdk.amazonaws.com/js/aws-sdk-2.1.15.min.js:6:27658
[10]</t.EventListeners.Core</</<@https://sdk.amazonaws.com/js/aws-sdk-2.1.15.min.js:5:10346
r@https://sdk.amazonaws.com/js/aws-sdk-2.1.15.min.js:5:478
[2]</t.Config<.getCredentials@https://sdk.amazonaws.com/js/aws-sdk-2.1.15.min.js:5:1064
[10]</t.EventListeners.Core</<@https://sdk.amazonaws.com/js/aws-sdk-2.1.15.min.js:5:10198
[34]</r.SequentialExecutor<.callListeners@https://sdk.amazonaws.com/js/aws-sdk-2.1.15.min.js:6:27751
[34]</r.SequentialExecutor<.emit@https://sdk.amazonaws.com/js/aws-sdk-2.1.15.min.js:6:27569
[30]</</n.Request<.emitEvent@https://sdk.amazonaws.com/js/aws-sdk-2.1.15.min.js:6:15978
[30]</</u.setupStates/e@https://sdk.amazonaws.com/js/aws-sdk-2.1.15.min.js:6:12289
[48]</r.prototype.runTo@https://sdk.amazonaws.com/js/aws-sdk-2.1.15.min.js:7:23402
[30]</</n.Request<.runTo@https://sdk.amazonaws.com/js/aws-sdk-2.1.15.min.js:6:13790
[30]</</n.Request<.send@https://sdk.amazonaws.com/js/aws-sdk-2.1.15.min.js:6:13688
[33]</r.S3.ManagedUpload<.nextChunk@https://sdk.amazonaws.com/js/aws-sdk-2.1.15.min.js:6:24508
[33]</r.S3.ManagedUpload<.fillBuffer@https://sdk.amazonaws.com/js/aws-sdk-2.1.15.min.js:6:23806
[33]</r.S3.ManagedUpload<.send@https://sdk.amazonaws.com/js/aws-sdk-2.1.15.min.js:6:22497
[38]</<.upload@https://sdk.amazonaws.com/js/aws-sdk-2.1.15.min.js:7:9755
$.fn.initializeUploader/</<@https://d3sjyjw8di3y5z.cloudfront.net/assets/admin/application-29c548168e93ec9f626fb6bd3d29f87a.js:1787:8185
.each@https://d3sjyjw8di3y5z.cloudfront.net/assets/admin/application-29c548168e93ec9f626fb6bd3d29f87a.js:1014:25321
$.fn.initializeUploader/<@https://d3sjyjw8di3y5z.cloudfront.net/assets/admin/application-29c548168e93ec9f626fb6bd3d29f87a.js:1787:7885
jQuery.event.dispatch@https://d3sjyjw8di3y5z.cloudfront.net/assets/admin/application-29c548168e93ec9f626fb6bd3d29f87a.js:1015:23250
jQuery.event.add/elemData.handle@https://d3sjyjw8di3y5z.cloudfront.net/assets/admin/application-29c548168e93ec9f626fb6bd3d29f87a.js:1015:18012
```

**Comment by AdityaManohar** [comment] 2015-03-13 19:45
Can you provide some sample code that you are using?

**Comment by AdityaManohar** [comment] 2015-03-24 21:25
@JacobEvelyn 
I'm marking this as closed because there hasn't been any recent activity. Feel free to reopen this issue or open another issue if you have any questions.

**Closed by AdityaManohar** 2015-03-24 21:25 UTC

**Comment by JacobEvelyn** [comment] 2015-03-25 13:17
Sorry, I didn't see you had responded to my comment. I couldn't get `AWS.config.logger = console.log` to show me any extra output, but you were right that I had multiple code paths—the same uploader callback was firing multiple times, and for some reason one of them wasn't forming the request correctly. Thanks for the help!

**Comment by AdityaManohar** [comment] 2015-03-25 17:51
@JacobEvelyn anytime! I'm glad you got it working.
