### ISSUE TITLE
Duplicate bucket name in hostname when calling s3.putObject inside ECS

### ISSUE THREAD

**Issue by lauramurriagfk** [aws/aws-sdk-js#3215] opened 2020-04-14 13:16 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x ] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x ] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Duplicate bucket name in hostname when calling s3.putObject inside ECS leads to certificate error thrown (see log below)
NB This has been referred by AWS support who were unable to resolve it and suggested I raise as a bug here.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No, within container on AWS ECS Fargate

Code works perfectly

- in local node server writing to same s3 bucket
- in local docker container writing to same s3 bucket
- in lambda on the same VPN

S3 reads from inside same ECS container also work fine.

**Details of the browser/Node.js version**
10.16.3

**SDK version number**
2.656.0

**To Reproduce (observed behavior)**
I am getting an error when writing to s3 from within ECS (Fargate) on a VPC using NodeJS API
To replicate, deploy code containing the following within a container on ECS.
```javascript
await s3
  .putObject(
    {
      Bucket: bucketName,
      Key: s3Key,
      Body: text,
    },
    (err, data) => {
      if (err) {
        logger.error(
          `Error writing to bucket: '${bucketName}', with key: '${s3Key}': `,
          err
        );
        throw new Error("Error writing text to file");
      }
      versionId = data.VersionId;
    }
  )
  .promise();
```

Bucket name is set to 

```console
bfe-ua-develop-portal-files
```

Error logged is:
```console
Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: bfe-ua-develop-portal-files.bfe-ua-develop-portal-files.s3.amazonaws.com. is not in the cert's altnames: DNS:*.s3.amazonaws.com, DNS:s3.amazonaws.com
```

You can see that it implies it is appending bucket name to the hostname twice in a row with a dot in between thus failing the certificate wildcard check due to the dot?

Full log below.

**Expected behavior**
Successful write to S3 without error thrown. See error log below

**Additional context**
Console log output follows:
```console
Result from putObject: { Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: bfe-ua-develop-portal-files.bfe-ua-develop-portal-files.s3.amazonaws.com. is not in the cert's altnames: DNS:*.s3.amazonaws.com, DNS:s3.amazonaws.com
    at Object.checkServerIdentity (tls.js:239:17)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1068:27)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.EventEmitter.emit (domain.js:448:20)
    at TLSSocket._finishInit (_tls_wrap.js:636:8)
  message:
   'Hostname/IP does not match certificate\'s altnames: Host: bfe-ua-develop-portal-files.bfe-ua-develop-portal-files.s3.amazonaws.com. is not in the cert\'s altnames: DNS:*.s3.amazonaws.com, DNS:s3.amazonaws.com',
  reason:
   'Host: bfe-ua-develop-portal-files.bfe-ua-develop-portal-files.s3.amazonaws.com. is not in the cert\'s altnames: DNS:*.s3.amazonaws.com, DNS:s3.amazonaws.com',
  host:
   'bfe-ua-develop-portal-files.bfe-ua-develop-portal-files.s3.amazonaws.com',
  cert:
   { subject:
      [Object: null prototype] {
        C: 'US',
        ST: 'Washington',
        L: 'Seattle',
        O: 'Amazon.com, Inc.',
        CN: '*.s3.amazonaws.com' },
     issuer:
      [Object: null prototype] {
        C: 'US',
        O: 'DigiCert Inc',
        OU: 'www.digicert.com',
        CN: 'DigiCert Baltimore CA-2 G2' },
     subjectaltname: 'DNS:*.s3.amazonaws.com, DNS:s3.amazonaws.com',
     infoAccess:
      [Object: null prototype] { 'OCSP - URI': [Array], 'CA Issuers - URI': [Array] },
     modulus:
      'C95BCE91B929589E2B5C147890DBDF033C316A11A0B5D2DB70DB79B563EDB468789CF8633D8940FEAF65CEECB6AF1286742CE467105E6333A6E3B78687A17A99EAB07D7E3EA8321B6543C33BC3BDBE59D33B689FFA65CA8EDFE341F91079EA98ADA92423BA4BD223CF268D8EA4324FD08366440010376BF0F031F552D4C7339EA6B0FF2B7EB7EAFE7B7DFF5854C06770348E6C973024C856B7295AE96F9336BBD03FE8885E4F7A2C2573CA1ECB8C7E03F4037EB9901EFFF0BBBB097A0163D21950F7A2EA7E3747BB8F2DEAAB9EDB21364BC01EEBED905CCAEF96847D8CE28AD046AB3796F148EA54D47AE2C223703B7FDB1846234A72F4C4B9294CABFF7861F3',
     exponent: '0x10001',
     pubkey:
      <Buffer 30 82 01 22 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 05 00 03 82 01 0f 00 30 82 01 0a 02 82 01 01 00 c9 5b ce 91 b9 29 58 9e 2b 5c 14 78 90 db df 03 3c ... >,
     valid_from: 'Nov  9 00:00:00 2019 GMT',
     valid_to: 'Mar 12 12:00:00 2021 GMT',
     fingerprint:
      '3F:E0:5B:48:6E:3F:09:87:13:0B:A1:D4:EA:0F:29:95:39:A5:82:43',
     fingerprint256:
      '27:2F:C2:83:BF:3E:DC:52:F6:F3:38:7A:9C:52:47:A2:0C:5D:71:76:FE:81:EC:3E:AB:A4:B3:A8:E5:7F:86:74',
     ext_key_usage: [ '1.3.6.1.5.5.7.3.1', '1.3.6.1.5.5.7.3.2' ],
     serialNumber: '082DF68EE9C69315BEBF72079B3810FD',
     raw:
      <Buffer 30 82 06 dc 30 82 05 c4 a0 03 02 01 02 02 10 08 2d f6 8e e9 c6 93 15 be bf 72 07 9b 38 10 fd 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 64 31 0b ... >,
     issuerCertificate:
      { subject: [Object],
        issuer: [Object],
        infoAccess: [Object],
        modulus:
         'BBE700FE000173EF9B88F05C0875F05C70731FFFB57A1F8D0823FDC7C1133FB12106BD4DCCDB2DB8871931DEDA6B0DC15DD251D5B05E72D4F066D484F2911841B50926B2039604699553FA074F3EBE863A432BB259B5ABD1BAF45940725A67B6CDE655FC092BA498B2BFCCA91FD4BF878F8225FD4580A9EC9D8CF97490CF1CF86550AFCDF845ABC82F8D8E361DDEEA89CDB252D9E509CD36712BDAC6D09BC6F6A45B5B39B61F001F19A4FBD3BE0CE6FB8FDD0E80E6A4E75AC4C02F72EE91F38367C9CDCACE4AB02081FDE472AF0918E74F42EC4D27424D07A0DDD50D75F73660CC265498A18837F083F7AD295920CFBB25E1D59EE6F3AEC101EBB50689E20A8F',
        exponent: '0x10001',
        pubkey:
         <Buffer 30 82 01 22 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 05 00 03 82 01 0f 00 30 82 01 0a 02 82 01 01 00 bb e7 00 fe 00 01 73 ef 9b 88 f0 5c 08 75 f0 5c 70 ... >,
        valid_from: 'Dec  8 12:05:07 2015 GMT',
        valid_to: 'May 10 12:00:00 2025 GMT',
        fingerprint:
         'A9:D5:30:02:E9:7E:00:E0:43:24:4F:3D:17:0D:6F:4C:41:41:04:FD',
        fingerprint256:
         'F9:69:08:80:81:9F:06:CD:CC:0B:2F:22:4B:20:7F:2A:F6:00:3F:B5:73:39:B8:67:9A:16:0F:A9:52:08:D6:2D',
        serialNumber: '0182F8098EA2E626B91A3B27841FB9AF',
        raw:
         <Buffer 30 82 04 63 30 82 03 4b a0 03 02 01 02 02 10 01 82 f8 09 8e a2 e6 26 b9 1a 3b 27 84 1f b9 af 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 5a 31 0b ... >,
        issuerCertificate: [Object] } },
  code: 'NetworkingError',
  region: 'us-east-1',
  hostname:
   'bfe-ua-develop-portal-files.bfe-ua-develop-portal-files.s3.amazonaws.com',
  retryable: true,
  time: 2020-04-14T08:30:02.299Z,
  statusCode: 200 } null
```

**Comment by lauramurriagfk** [comment] 2020-04-14 13:19
Referred here as bug by AWS Support: ref [Case 6915194701] Can't s3.putObject from within AWS ECS Fargate

**Comment by gshondal** [comment] 2020-04-15 06:55
@lauramurriagfk 
Can this be replicated? 
What is the source of bucketName, where does it come from?
When you output the bucketName variable putObject is called, what does it display?
Yes, wildcard *.s3.amazonaws.com will not match a second level subdomain.

**Comment by lauramurriagfk** [comment] 2020-04-15 08:24
Thanks for picking this up. As described above...

Bucket name is set to
bfe-ua-develop-portal-files

You will see how this name then appears in the hostname

**Comment by lauramurriagfk** [comment] 2020-04-15 08:30
I also log out the bucket name as part of the application log and the log line

logger.error(`Error writing to bucket: '${bucketName}', with key: '${s3Key}': `, err);

yields the output (in CloudWatch from running ECS task)

2020-04-14 08:29:45 [error]: 	Error writing to bucket: 'bfe-ua-develop-portal-files', with key: 'Releases/1-Handset/24-26 Mar 2020/1-HandsetDataRelease/1-HandsetDataRelease-content.html': Hostname/IP does not match certificate's altnames: Host: bfe-ua-develop-portal-files.bfe-ua-develop-portal-files.s3.amazonaws.com. is not in the cert's altnames: DNS:*.s3.amazonaws.com, DNS:s3.amazonaws.com

**Comment by lauramurriagfk** [comment] 2020-04-15 08:33
There's a passing resemblance to this very old bug, now fixed. The root cause might be a reintroduction of something similar or might just be a red herring

https://github.com/aws/aws-sdk-js/issues/585

**Comment by AllanFly120** [comment] 2020-04-15 16:18
Hi, @lauramurriagfk 

Can you share the code snippet for instantiating the S3 client? Which region did the target buget create in?

**Comment by lauramurriagfk** [comment] 2020-04-16 07:35
This information is all in the case above under 'To Reproduce' including region us-east-1. 
There is code and full log of result(err,data) (as requested by AWS support) and our app logs (verifying bucket name and err), from CloudWatch.
The bucket was created from the same region us-east-1. I have tried all sorts of different bucket settings including removing any CORS, KMS, making it public, setting an s3 endpoint/removing, addressing the endpoint directly, with or without setting all the following options on s3 - region: 'us-east-1', endpoint: <various>
 s3BucketEndpoint: false, hostPrefixEnabled: false
For <various> endpoint I have tried numerous different URLs as advised in docs, with or without region included and using s3:// or https://. Note that the s3 read has no problems accessing the same bucket.
Thanks

**Comment by lauramurriagfk** [comment] 2020-04-27 08:17
Is there any progress on this, please

**Comment by WesKetch** [comment] 2020-05-29 20:48
Just recently ran into a similar issue. The only difference is that my code is running inside of CodeBuild. But same type of error, every write to s3 from inside the docker container in CodeBuild is throwing this exception

```
Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: lang-config-refator-feed.lang-config-refator-feed.s3.amazonaws.com. is not in the cert's altnames: DNS:*.s3.amazonaws.com, DNS:s3.amazonaws.com
    at Object.checkServerIdentity (tls.js:288:12)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1483:27)
    at TLSSocket.emit (events.js:311:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at TLSSocket._finishInit (_tls_wrap.js:916:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:686:12) {
  message: "Hostname/IP does not match certificate's altnames: Host: lang-config-refator-feed.lang-config-refator-feed.s3.amazonaws.com. is not in the cert's altnames: DNS:*.s3.amazonaws.com, DNS:s3.amazonaws.com",
  reason: "Host: lang-config-refator-feed.lang-config-refator-feed.s3.amazonaws.com. is not in the cert's altnames: DNS:*.s3.amazonaws.com, DNS:s3.amazonaws.com",
  host: 'lang-config-refator-feed.lang-config-refator-feed.s3.amazonaws.com',
  cert: {
    subject: [Object: null prototype] {
      C: 'US',
      ST: 'Washington',
      L: 'Seattle',
      O: 'Amazon.com, Inc.',
      CN: '*.s3.amazonaws.com'
    },
    issuer: [Object: null prototype] {
      C: 'US',
      O: 'DigiCert Inc',
      OU: 'www.digicert.com',
      CN: 'DigiCert Baltimore CA-2 G2'
    },
    subjectaltname: 'DNS:*.s3.amazonaws.com, DNS:s3.amazonaws.com',
    infoAccess: [Object: null prototype] {
      'OCSP - URI': [Array],
      'CA Issuers - URI': [Array]
    },
```

**Comment by philipwigg** [comment] 2020-05-31 22:42
@lauramurriagfk  I built [a little test case](https://github.com/philipwigg/3125-test-case) to try to debug this and I have managed to reproduce the error you were getting.

Seems to be just because you're passing in a callback to `s3.putObject` whilst simultaneously calling `.promise()` and that seems to cause weird effects. Can you try it with a try/catch instead like in my [writeFile2](https://github.com/philipwigg/3125-test-case/blob/f8649cf72e3b96ddbafbc2e98318b0b6a9eae7e2/src/s3Service.ts#L32) method? That seems to fix it for me.

Strangely, I could only reproduce the SSL error when I ran the code from Fargate in `us-east-1`. Like you said, in other places such as locally and from Fargate in `eu-west-1`, the file is still written to the bucket (although it does seem to write it twice).

Hope that helps!

**Comment by WesKetch** [comment] 2020-06-01 22:40
@philipwigg thanks for that suggestion! I was doing something similar with the callback + using `.promise()` and removing the callback got it to work. Wonder what it is specifically about these environments that cause that issue. Even though I think having both the callback and `.promise()` probably isnt the right way to implement it.

**Comment by lauramurriagfk** [comment] 2020-06-02 09:35
Thanks for the suggestions, I'll test today or as soon as the environment is available. Re the AWS us-east-1, sometime there are some quirks/differences here versus other regions (perhaps because it was the original default AWS location and so underlying implementation does not always need/use/enforce use of region)

**Comment by philipwigg** [comment] 2020-06-02 17:45
@WesKetch Yeah I think it's a callback or a promise but not both although clearly there's nothing that enforces that.

I think the bug is that you can pass a callback and chain ```.promise()``` simultaneously? Maybe an error should be thrown at that point that this isn't something that's allowed? @AllanFly120?

**Comment by ajredniwja** [comment] 2020-07-14 23:25
I agree with @philipwigg, promises and callbacks should not be mixed as mentioned in https://github.com/aws/aws-sdk-js/issues/3347

It could be regarded as a feature request to throw an error when callbacks and promises are mixed but I believe this is more of a coding practice in the nodeJS world.

Having callbacks inside your promise may not address your exceptions correctly and will cause problems. 

Closing this now, please feel free to reach out if any further discussion is needed.

**Closed by ajredniwja** 2020-07-14 23:25 UTC
Labels: bug
