### ISSUE TITLE
ImportDocumentationPartsCommand - Missing Body Param?

### ISSUE THREAD

**Issue by simon-casasoft** [aws/aws-sdk-js#3710] opened 2021-04-14 18:06 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
I'm getting this error when sending the ImportDocumentationPartsCommand command 
`"errorMessage": "1 validation error detected: Value null at 'body' failed to satisfy constraint: Member must not be null"`

The ImportDocumentationPartsCommandInput interface doesn't have a body param so I opted to using 'any' to test it but I still get the validation error.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
Yes

**Details of the browser/Node.js version**
v10.19.0

**SDK version number**
v2.804.0

**Comment by ajredniwja** [comment] 2021-05-07 03:13
Hey @simon-casasoft, thanks for opening this issue, can you please share a code example to reproduce the issue?

**Comment by simon-casasoft** [comment] 2021-05-15 09:56
Hey @ajredniwja , thanks for getting in touch. I'll try have a code example for you later this week!

**Comment by vudh1** [comment] 2021-11-22 19:54
@simon-casasoft closing this issue since there is no code provided. Feel free to reopen if you still need help.

**Closed** 2021-11-22 19:54 UTC
Labels: bug, needs-triage
