### ISSUE TITLE
AWS.ElasticTranscoder Error Handling Discrepancy: waitFor & readJob returning different error messages for same Job.

### ISSUE THREAD

**Issue by tallboy** [aws/aws-sdk-js#725] opened 2015-09-18 22:19 UTC
I've been working with the transcoder SDK quite a bit and I've noticed what I feel like is a bug with how errors are retrieved using the `transcoder.waitFor('jobComplete'...` versus `transcoder.readJob(jobId, ..`

The `waitFor` command seems to be failing straight away with a Resource Not Ready err callback no matter what the error.  It also has `retryable: false` and it seems to die at that point.  I've tried wrapping it in a timer and it will continually return the Resource not Ready error regardless of the actual error that being captured on the Output like the item already existing in a S3 bucket for instance.  

This error also seems to return as part of a normal use case as well. This is unfortunate because a lot of my node code listens for errors, triggering an error callback, and the entire call flow then breaks.  

transcoder.readJob on the other seems to respond with meaningful error messages in the Output section of the data return.  Although this is part of the data callback and not an error callback which is the opposite of the return payloads of the polling mechanism.  

Case 1 with the waitFor listener (response in the error return object):
`{ [ResourceNotReady: Resource is not in the state jobComplete]\n  message: 'Resource is not in the state jobComplete',\n  code: 'ResourceNotReady',\n  retryable: false,\n  time: Fri Sep 18 2015 14:18:46 GMT-0700 (PDT),\n  statusCode: 200,\n  retryDelay: 30000 } ResourceNotReady 30000","timestamp":"2015-09-18T21:18:46.246Z"}`

Case 2 with the readJob function (response in the data return object):
`{ Job:
   { Arn: 'xxx',
     Id: 'xxx',
     Input:
      { AspectRatio: 'auto',
        Container: 'auto',
        FrameRate: 'auto',
        Interlaced: 'auto',
        Key: 'xxx',
        Resolution: 'auto' },
     Output:
      { Captions: [Object],
        Id: '1',
        Key: 'xxx',
        PresetId: '1351620000001-000020',
        Status: 'Error',
        StatusDetail: '3002 68de6d80-e685-45fe-80ac-fdceb32cc3f8: The specified object could not be saved in the specified bucket because an object by that name already exists: bucket=xxx, key=xxx.',
        Watermarks: [] },
     Outputs: [ [Object] ],
     PipelineId: 'xxx',
     Playlists: [],
     Status: 'Error',
     Timing:
      { FinishTimeMillis: 1442613305225,
        StartTimeMillis: 1442613302501,
        SubmitTimeMillis: 1442613298943 } } }`

Is this by design?  It seems inconsistent at best and broken at worst.  Unless, I should be using different API calls to get job status or I'm simply doing it wrong.  I ended up just wrapping a `readJob` function in a timer but that seems like what the `waitFor` function should be doing anyway.

**Comment by AdityaManohar** [comment] 2015-09-19 00:35
@tallboy can you share the code you are using?

I haven't been able to reproduce the issues you are mentioning with the `waitFor()` method. Here is the code I am using:

```javascript
var AWS = require('aws-sdk');

var transcoder = new AWS.ElasticTranscoder({region: 'us-west-2'});
var callback = function(err, data) { if (err) console.log(err); else console.log(data); };
var params = {
  PipelineId: 'foo-bar',
  Input: {
    Key: 'file',
    AspectRatio: 'auto',
    FrameRate: 'auto',
    Resolution: 'auto',
    Container: 'auto',
    Interlaced: 'auto'
  },
  Output: {
    Key: 'file.mp4',
    PresetId: '1351620000001-000010'
  }
};

transcoder.createJob(params, function(err, data) {
  if (err)
    console.log(err);
  else
    transcoder.waitFor('jobComplete', {Id: data.Job.Id}, callback);
});

```

**Comment by tallboy** [comment] 2015-09-19 17:46
I have the `transcoder.waitFor` as a second step in a waterfall flow.  Is it necessary to have it in the callback of the `transcoder.createJob`?  I can try it that way as well.

Are you able to reproduce the error message in the data object that's returned in readJob?  I get this when a filename with the same name already exists in the S3 bucket and I try to create a new transcode job.

**Comment by tallboy** [comment] 2015-09-21 17:59
Here's the polling code I was using:

    let transcoder = new AWS.ElasticTranscoder();
    let params = {
      ....
    };

    transcoder.createJob(params, (err, data) => {
      if (err) {
        log.error('transcoder.createJob err: ', err);
        return cb(err);
      } else {
        log.info('transcoder.createJob data: ', data);
        transcoder.waitFor('jobComplete', { Id: data.Job.Id }, function(err, data) {
          log.error('transcoder.pollTranscodeJob: ', err, data);
          cb(err, data);
        });
      }

    });

That's how I get the above error:

`transcoder.pollTranscodeJob:  { [ResourceNotReady: Resource is not in the state jobComplete]
  message: 'Resource is not in the state jobComplete',
  code: 'ResourceNotReady',
  retryable: false,
  time: Mon Sep 21 2015 10:44:02 GMT-0700 (PDT),
  statusCode: 200,
  retryDelay: 30000 } null`


Now if I use a SetInterval function and ping it every 10 seconds or so I'll eventually get a return data object with an error message in the Output Status. 

    setInterval(() => {
      transcoder.readJob({ Id: jobId }, (err, data) => {
        if (err) return cb(err);
        if (data.Job.Status && data.Job.Status == 'Error') {
          let errMessage = data.Job.Output.StatusDetail;
          log.error('transcoder readJob: ', errMessage);
          cb(new Error(errMessage));
        } else {
          log.info('transcoder readJob: ', data);
          cb(null, data);
        }
      });
    }, 10000);

Error example:

`{ Job: { Arn: 'xxx', Id: 'xxx', Input: { AspectRatio: 'auto', Container: 'auto', FrameRate: 'auto', Interlaced: 'auto', Key: 'xxx', Resolution: 'auto' }, Output: { Captions: [Object], Id: '1', Key: 'xxx', PresetId: '1351620000001-000020', Status: 'Error', StatusDetail: '3002 68de6d80-e685-45fe-80ac-fdceb32cc3f8: The specified object could not be saved in the specified bucket because an object by that name already exists: bucket=xxx, key=xxx.', Watermarks: [] }, Outputs: [ [Object] ], PipelineId: 'xxx', Playlists: [], Status: 'Error', Timing: { FinishTimeMillis: 1442613305225, StartTimeMillis: 1442613302501, SubmitTimeMillis: 1442613298943 } } }`

I'll probably end up using a guid or something to make sure I don't have any naming collisions in the S3 buckets I just thought it was strange to get a generic `[Resource Not Ready]` error from the poller when there's a more detailed error message on admin panel for the Job.  That error seems to also match with the `Status: 'Error'` detail that I get back when I put the readJob on a timer.

**Comment by chrisradek** [comment] 2015-09-23 21:56
@tallboy 
The `waitFor()` method is intended to provide information on whether a resource is available for use. The `waitFor()` method does not report details behind why that resource is or isn't available. 

A possible workaround is to invoke `readJob()` when `waitFor()` method returns an error. This should give you details of the status of your job.

Let me know if this helps.

**Comment by tallboy** [comment] 2015-09-23 22:31
This is exactly what I ended up implementing with the interval timer I pasted above. It would be beneficial to get back the error message from `readJob()` if the `waitFor()` throws an error.  The documentation states it's calling the underlying `readJob()` function anyway.  

[waitFor('jobComplele')](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ElasticTranscoder.html#jobComplete-waiter)

Why the difference in response payloads?  IMO, it would be nice to get a more descriptive error response other than `ResourceNotReady` if a job fails.

**Comment by AdityaManohar** [comment] 2015-09-23 23:04
@tallboy the reason for this generic error message is because the underlying operation need not return an error. In this case `readJob()` is not returning an error. The `readJob()` operation itself is successful. It happens to contain information about an error that occurred with the job that was created.

The waiters depend on the state of the resource to decide whether the resource is available or not across all of our services. Mapping an the name of an error state to where details of an error is available in the response does not scale well across all the services that we support because this can vary greatly from service to service.

The intention of a waiter is to provide information on whether the resource is available or not so that some other subsequent action can be initiated on a eventually consistent resource. If you specifically want information about why a particular resource is not available, I would recommend invoking the underlying API to get that information. It looks like you are already doing this though.

I hope this helps clarify things.

**Comment by tallboy** [comment] 2015-09-23 23:08
:+1: Feel free to close it

**Comment by AdityaManohar** [comment] 2015-09-24 00:13
@tallboy 
I'm marking this as closed. Feel free to reopen this issue or open another issue if you have other questions.

**Closed by AdityaManohar** 2015-09-24 00:13 UTC
Labels: Feedback Requested
