### ISSUE TITLE
InstanceProtocol parameter doesn't appear under Listeners in documentation.

### ISSUE THREAD

**Issue by mike-rsi** [aws/aws-sdk-js#654] opened 2015-07-08 17:34 UTC
``createLoadBalancer`` and ``createLoadBalancerListeners`` both take a ``Listeners`` parameter.  Each Listener has an optional parameter ``InstanceProtocol``.  In the [documentation ](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ELB.html#createLoadBalancer-property),  under *Examples*, the JavaScript snippets correctly show that ``InstanceProtocol`` is an optional parameter under ``Listeners``, but then under the *Parameters* section, ``InstanceProtocol`` and it's description does not appear.

It does appear the JSON that's used to generate the documentation contains [a description for InstanceProtocol parameter](https://github.com/aws/aws-sdk-js/blob/master/apis/elasticloadbalancing-2012-06-01.normal.json#L2101) for Listeners, but I'm not familiar enough with how the documentation is generated to figure out why that text is not making it into the final rendering of the documentation.

**Comment by lsegal** [comment] 2015-07-08 18:07
Thanks for reporting this, @mike-rsi. This looks like it might be related to #591, but this is helpful in narrowing down the cause. I'll have to dig into this one; it certainly looks like our documentation plugin is missing this string somehow.

**Comment by lsegal** [comment] 2015-07-08 20:03
I've narrowed down the cause and should have a fix for this up shortly.

**Comment by lsegal** [comment] 2015-07-08 20:37
The fix above is live, thanks for reporting!

**Closed** 2015-07-08 20:36 UTC
Labels: Documentation
