### ISSUE TITLE
Unrecognized shape type: map

### ISSUE THREAD

**Issue by henriquebf** [aws/aws-sdk-js#483] opened 2015-01-28 22:34 UTC
I've just tried to update my aws-sdk library to the lastest version, and I get an error when trying to upload a stream to S3:

**Error: Unrecognized shape type: map**

If I rollback to my previous version **(2.0.0-rc1)**, it works fine. Couldn't find any issues in my code, and even the simple upload examples do not work.

```javascript
s3.putObject(params, function(err, data) {
    if(err) {
        // Upload error
        console.log(err);
    }
});
```

**Comment by lsegal** [comment] 2015-01-28 22:51
I'm unable to reproduce that error, could you provide a full stack trace (`err.stack`) in addition to the error? Could you also list your Node.js version as well as any other code in your script?

This works for me:

```js
var AWS = require('aws-sdk');
var s3 = new AWS.S3();

s3.putObject({Bucket: 'mybucket', Key: 'mykey', Body: 'foo'}, console.log);
```

**Comment by henriquebf** [comment] 2015-01-29 09:53
```javascript
Error: Unrecognized shape type: map
    at Function.create (/Users/henriqueferreira/Documents/Projects/www/flux-drive/node_modules/AWS-sdk/lib/model/shape.js:130:13)
    at /Users/henriqueferreira/Documents/Projects/www/flux-drive/node_modules/AWS-sdk/lib/model/api.js:46:18
    at /Users/henriqueferreira/Documents/Projects/www/flux-drive/node_modules/AWS-sdk/lib/model/collection.js:5:12
    at Collection.Sy (/Users/henriqueferreira/Documents/Projects/www/flux-drive/node_modules/AWS-sdk/lib/util.js:713:23)
    at Function.resolve (/Users/henriqueferreira/Documents/Projects/www/flux-drive/node_modules/AWS-sdk/lib/model/shape.js:80:38)
    at Function.create (/Users/henriqueferreira/Documents/Projects/www/flux-drive/node_modules/AWS-sdk/lib/model/shape.js:94:24)
    at /Users/henriqueferreira/Documents/Projects/www/flux-drive/node_modules/AWS-sdk/lib/model/shape.js:159:20
    at /Users/henriqueferreira/Documents/Projects/www/flux-drive/node_modules/AWS-sdk/lib/model/collection.js:5:12
    at Collection.Metadata (/Users/henriqueferreira/Documents/Projects/www/flux-drive/node_modules/AWS-sdk/lib/util.js:713:23)
    at Object.each (/Users/henriqueferreira/Documents/Projects/www/flux-drive/node_modules/AWS-sdk/lib/util.js:535:54)
```

**Comment by AdityaManohar** [comment] 2015-01-29 19:04
Would you be able to share more on how you installed the SDK? It seems like the SDK Node module is in `*/AWS-sdk`? Was this a manual install from GitHub? 

Also, can you print `AWS.VERSION` in your script?

**Comment by AdityaManohar** [comment] 2015-02-04 22:04
I'm closing this out since there hasn't been any recent correspondence and the issue cannot be reproduced. Feel free to reopen this issue or open another issue if the problem still persists.

**Closed by AdityaManohar** 2015-02-04 22:04 UTC
Labels: Feedback Requested
