### ISSUE TITLE
(react-native) Typescript error: Cannot find name 'Buffer'/'http'/'https'

### ISSUE THREAD

**Issue by dudunato** [aws/aws-sdk-js#1926] opened 2018-02-12 10:18 UTC
Hey there, 

After following the steps of #1271 and adding the types to my tsconfig.json then it gives me another error:

```
node_modules/@types/react-native/index.d.ts(8630,14): error TS2300: Duplicate identifier 'require'.
node_modules/@types/node/index.d.ts(140,13): error TS2300: Duplicate identifier 'require'.
```

Here's my tsconfig.json:

``` json
{
  "compilerOptions": {
    "target": "es2015",
    "module": "es2015",
    "moduleResolution": "node",
    "jsx": "react",
    "outDir": "compiled",
    "rootDir": "./src",
    "types": ["node", "react", "react-native", "jest"]
  },
  "include": ["./src/**/*"],
  "exclude": [
    "./compiled",
    "./node_modules"
  ]
}
```

It seems that node types are conflicting with react-native. Any thoughts?

**Comment by jeskew** [comment] 2018-02-13 01:05
It looks like there is [an open PR that might address this issue on the DefinitelyTyped repository](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16825). Unfortunately, there's nothing we can do in the SDK about this while the issue is being resolved by the maintainers of the `@types/node` and `@types/react-native` packages.

As a workaround, you could add bespoke typings for the portions of the React Native API that are called directly by the application being compiled (per the advice given in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15960).

**Comment by kevinsperrine** [comment] 2018-03-02 20:56
@dudunato I just hacked around it. https://github.com/aws/aws-amplify/issues/281#issuecomment-370049435 ¯\_(ツ)_/¯

**Comment by dudunato** [comment] 2018-03-08 08:35
I just ignored it on my tsconfig (but not a good solution at all). I might migrate to yours! Thanks so much for sharing, @kevinsperrine!

**Comment by srchase** [comment] 2018-11-29 23:47
As this is still being sorted out in DefinitelyTyped, I'm going to close this isssue.

**Closed by srchase** 2018-11-29 23:47 UTC
Labels: third-party, typings
