### ISSUE TITLE
s3.createBucket method is mutating the object passed as parameter 

### ISSUE THREAD

**Issue by ericmustin** [aws/aws-sdk-js#3112] opened 2020-02-24 12:44 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
This is the same bug previously reported here https://github.com/aws/aws-sdk-js/issues/3013 .

i've been testing my `s3.createBucket` calls using localstack, which requires me to modify the endpoint to `localhost:4572` and for some reason this causes the parameter object that has been passed in to get mutated and a `CreateBucketConfiguration` key gets erroneously added to it, which breaks future calls using that parameter object. There is probably a missing `Object.assign` call somewhere but I haven't had the time to track it down, otherwise would just make the PR.

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
`v10.15.1`

**SDK version number**
`└── aws-sdk@2.624.0 `

**To Reproduce (observed behavior)**
Reproduction snippet below, please note it only appears to occur when modifying the `endpoint` config option

```
// npm install -g aws-sdk
// https://github.com/localstack/localstack
// run localstack docker container with s3 listening at localhost:4572

const AWS = require('aws-sdk')
const assert = require('assert')
const ep = new AWS.Endpoint('http://localhost:4572')
const s3 = new AWS.S3({endpoint: ep, s3ForcePathStyle: true})
const bucket = 'node-sdk-sample'  
const params = { Bucket: bucket }
const originalKeys = Object.keys(params)

// Create a bucket and upload something into it
s3.createBucket(params, function(err, data) {
  let mutatedKeys = Object.keys(params)

  console.log('original object keys: ', originalKeys)
  console.log('mutated object keys: ', mutatedKeys)

  assert.deepEqual(originalKeys, mutatedKeys)
})
```

**Expected behavior**
parameters object passed into `s3.createObject` should not be mutated, as this can cause future calls that re-use that same parameters object to throw validation errors

**Screenshots**

![reproduction snapshot](https://cl.ly/2003e76413c7/Image%2525202020-02-24%252520at%2525201.37.51%252520PM.png)

**Additional context**
Given that this issue has been opened (and auto-closed 😐 ) before, as seen here https://github.com/aws/aws-sdk-js/issues/3013 it seems very likely there is a legitimate bug.  If you are having trouble reproducing please `@` me and let me know and i'll be happy to provide any additional relevant context. And in general thanks for the great work y'all do maintaining this repo, it's great and very well documented!

**Comment by ericmustin** [comment] 2020-02-25 13:07
@ajredniwja issue is here, fwiw, https://github.com/aws/aws-sdk-js/blob/534033a2edb638252d0030f27b9d6297283aa507/lib/services/s3.js#L1318

Up to y'all on how to fix, depends if you want to allocate another object , and how you want to go about doing that. something like the below probably works, although it should be note that `Object.assign` will miss things like properties that only exist on the `params` object prototype chain, and also non-enumerable properties, things like Symbols or what have you 

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

```
  createBucket: function createBucket(params, callback) {
    if (typeof params === 'function' || !params) {
      callback = callback || params;
      params = {};
    }
    var hostname = this.endpoint.hostname;
    var updatedParams = Object.assign({}, params);
    if (hostname !== this.api.globalEndpoint && !updatedParams.CreateBucketConfiguration) {
      updatedParams.CreateBucketConfiguration = { LocationConstraint: this.config.region };
    }
    return this.makeRequest('createBucket', updateParams, callback);
  },
```

**Comment by ajredniwja** [comment] 2020-03-03 02:02
I was able to reproduce this, while this is not potentially is not a bug with the SDK but something that can be improved, I marked this as a feature request, would be glad to take a PR, otherwise will let the team evaluate the priority and work on it later.

**Comment by ericmustin** [comment] 2020-03-08 11:26
@ajredniwja alrighty, thanks for taking a look and the feedback. I have made a PR to address this and also wrote a unit test to prevent a regression in future versions https://github.com/aws/aws-sdk-js/pull/3138

As an aside, i think marking this a feature request is not in line with my understanding of the term.

**Comment by ajredniwja** [comment] 2020-03-10 00:12
@ericmustin I agree with you but I marked this as a feature request since its more of a behavior issue, which can be enhanced and not necessarily a bug, meaning not really a bug. 
Since you have already created a PR, I would let the team review it.

**Closed** 2020-03-18 01:00 UTC
Labels: feature-request
