### ISSUE TITLE
Cannot read property 'Stream' of undefined

### ISSUE THREAD

**Issue by patrik-piskay** [aws/aws-sdk-js#1289] opened 2017-01-05 12:01 UTC
Hi,

we are trying to move from inline script AWS files to npm packages and when trying to log in user using `amazon-cognito-identity-js` package, it results in this error:

```
TypeError: Cannot read property 'Stream' of undefined
    at Object.computeSha256 (util.js:687)
    at Request.COMPUTE_SHA256 (event_listeners.js:97)
    at Request.callListeners (sequential_executor.js:101)
    at Request.emit (sequential_executor.js:77)
    at Request.emit (request.js:668)
    at Request.transition (request.js:22)
    at AcceptorStateMachine.runTo (state_machine.js:14)
    at state_machine.js:26
    at Request.<anonymous> (request.js:38)
    at Request.<anonymous> (request.js:670)
```

The files from the trace are all part of this `aws-sdk` npm package hence I'm creating the issue in this repo.

Thanks!

**Comment by chrisradek** [comment] 2017-01-05 17:02
@patrik-piskay 
Can you share how you're consuming the `amazon-cognito-identity-js` package in your project?

The error you're seeing is because the node.js version of the AWS SDK is being used instead of the browser version.
https://github.com/aws/aws-sdk-js/blob/master/lib/util.js#L696
 `AWS.util.isNode()` will return true if the node.js version of the SDK is used, or false if the browser version is being used.

I'm not familiar with how the `amazon-cognito-identity-js` package is meant to work when using the npm package, so this may be a better question to ask on that project's github.

**Comment by itrestian** [comment] 2017-01-09 22:55
computeSha256 is called to do Sigv4. I understand the signatureVersion is at the API level so that is why we call computeSha256. However, since we are calling makeUnauthenticatedRequest why is it being called? Can we have a way to not do that for unauthenticated requests?

**Comment by chrisradek** [comment] 2017-01-09 23:09
@itrestian 
It's useful because it helps services be certain that the body they received is what the client meant to send, though without authentication I suppose the header and body of a request could be subject to manipulation anyways.

It should be possible to remove the COMPUTE_SHA256 call from being called by doing something like:
```javascript
var cognito = new AWS.CognitoIdentityServiceProvider({/* config */});
var req = cognito.makeUnauthenticatedRequest('signUp', {/* params */});
req.removeListener('afterBuild', AWS.EventListeners.Core.COMPUTE_SHA256);
req.send(callback);
```

**Comment by WChoy** [comment] 2018-01-12 19:24
Having the same issue.   also in https://github.com/aws/aws-amplify/issues/153

It a problem that with the use of the "cipher-base" module, which was designed for a node.js.   
In line:2 of their index.js file:
   "var Transform = require('stream').Transform"
It uses the stream module is the node.js core (https://nodejs.org/api/stream.html#stream_new_stream_transform_options).  
```
aws-sdk@2.180.0
└┬ create-hash@1.1.3
   └┬ ripemd160@2.0.1
      └─ hash-base@2.0.2 
```

**Comment by srchase** [comment] 2018-08-28 21:11
@itrestian 

Was the suggestion @chrisradek helpful in getting this working for you?  If you don't have any followup questions, I'd like to close out this issue.

**Comment by srchase** [comment] 2018-09-04 16:13
Closing out this issue.  Let us know if you have anything additional to add.

**Closed by srchase** 2018-09-04 16:13 UTC
Labels: Question

**Comment by Omi0** [comment] 2018-10-03 14:07
Note: if you intend to use it in TS in Angular - you need to set up as following:

AWS.EventListeners['Core'].removeListener('afterBuild', AWS.EventListeners['Core'].COMPUTE_SHA256);

**Comment by mayur2345** [comment] 2018-10-20 12:31
AWS.EventListeners['Core'].removeListener('afterBuild', AWS.EventListeners['Core'].COMPUTE_SHA256);

worked for me thanks;

use it like this

import * as AWS from 'aws-sdk';
AWS.EventListeners['Core'].removeListener('afterBuild', AWS.EventListeners['Core'].COMPUTE_SHA256);

**Comment by Omi0** [comment] 2018-10-22 09:55
@mayur2345 by the way - if you really want to fix this problem. Because this approach will not 100% solve your problem. But to fix you simple need to tell AWS, that you use a browser, not Node. And the way to to it is:
`(window as any).process = {
  browser: true
};`
