### ISSUE TITLE
List objects in date range.

### ISSUE THREAD

**Issue by slim-hmidi** [aws/aws-sdk-js#3103] opened 2020-02-19 10:49 UTC
**Is your feature request related to a problem? Please describe.**
List the objects in date range. E.g: list all objects between the date 01-01-2019 and 31-03-2019.

**Describe the solution you'd like**
Be able to get only the objects where the LastModified parameter is between the startDate and endDate.

**Describe alternatives you've considered**
Actually, I fetch all the objects in a given bucket, then I filter the data manually by adding a condition to check that lastModified parameter is in the date range.

**Additional context**
I archive some files in a bucket by date and I want to fetch them by date range when I need that.

**Comment by ajredniwja** [comment] 2020-02-25 01:43
Closing this issue since it is a duplicate of #3102

**Closed by ajredniwja** 2020-02-25 01:43 UTC
Labels: duplicate, feature-request
