### ISSUE TITLE
Js error with sdk in the browser 

### ISSUE THREAD

**Issue by Noxs** [aws/aws-sdk-js#1194] opened 2016-10-20 08:10 UTC
Hi, I am experiencing an issue with sdk  2.6.\* built with the dist tools.
I got in the browser:
chrome 53
`aws-sdk.js:20911 Uncaught SyntaxError: Unexpected identifier`
firefox 49
`SyntaxError: missing ] after element list
http://localhost:9000/scripts/services/aws-sdk.js
Line 20911`

```
if (typeof window !== 'undefined') window.AWS = AWS;
if (typeof module !== 'undefined') module.exports = AWS;
if (typeof self !== 'undefined') self.AWS = AWS;


  AWS.apiLoader.services['s3'] = {};
  AWS.S3 = AWS.Service.defineService('s3', [ '2006-03-01' ]);
  require('./services/s3');
}
/* error at this line */AWS.apiLoader.services['s3']['2006-03-01'] = require('../apis/s3-2006-03-01.min');
AWS.apiLoader.services['s3']['2006-03-01'].paginators = require('../apis/s3-2006-03-01.paginators').pagination;
AWS.apiLoader.services['s3']['2006-03-01'].waiters = require('../apis/s3-2006-03-01.waiters2').waiters;
```

Everything was ok with any  2.5.\* release.
I tried with node 5.3 and node 6.9:
- node 6.9:  error above
- node 5.3: same error as above but not at the line number

The command line I used: 
`node dist-tools/browser-builder.js s3 > aws-sdk.js`

Any help appreciated.

**Comment by chrisradek** [comment] 2016-10-20 15:08
@Noxs 
Have you tried building with version 2.6.10 of the SDK?
I just ran the same command with version `2.6.10`, then used the resulting SDK in an app that calls S3, and didn't encounter any errors.
Command:
`node dist-tools/browser-builder.js s3 > aws-sdk.js`

Tried with node 6.7 and 6.9.
Tested in Firefox, on an OS X machine.

**Comment by Noxs** [comment] 2016-10-20 15:34
@chrisradek 
I tried from 2.6.0 to 2.6.10.
Can you put here the generated file, so i can make a diff.
Mine doesn't work anywhere. (osx, win7).
[aws-sdk.zip](https://github.com/aws/aws-sdk-js/files/542091/aws-sdk.zip)

**Comment by chrisradek** [comment] 2016-10-20 16:53
@Noxs 
It looks like your file is missing a single line:
`if (!Object.prototype.hasOwnProperty.call(AWS, 'S3')) {` at line 20906. Interestingly, the contents of the if block, including the closing bracket, are present.

When I added that line back in, your SDK worked in my app.

Could you run `npm cache clean`, install the SDK in a new directory, and build the browser SDK again to see if that helps?

**Comment by Noxs** [comment] 2016-10-21 09:04
@chrisradek
Same result when I do it in a new directory. I also run npm cache clean.
I tried on a OS X machine, it works perfectly.
I will try to reproduce this bug on another win7 and post here the result.

**Comment by Noxs** [comment] 2016-10-26 08:13
@chrisradek
I tried on other win7 computer, and this is not working.
I got the same problem.
Building the SDK on win7 is not working since 2.6.0.

What should I do? Close the issue or leave it open?

**Comment by chrisradek** [comment] 2016-10-26 23:25
@Noxs 
I'll get my hands on a windows 7 machine and see if I can reproduce the issue from there. Leave the issue open for now.

**Comment by chrisradek** [comment] 2016-11-01 23:52
@Noxs 
Have you been able to test this on Windows 10? Still working on getting a windows 7 machine, but I don't see the issue on Windows 10.

**Comment by Noxs** [comment] 2016-11-02 09:02
@chrisradek
No, I have not been able to test on windows 10. I don't have any.

**Comment by chrisradek** [comment] 2018-08-10 17:46
Cleaning up old issues. Please open a new issue if you're still encountering this behavior.

**Closed by chrisradek** 2018-08-10 17:46 UTC
Labels: Feedback Requested, Question
