### ISSUE TITLE
Route53.waitFor('resourceRecordSetsChanged') throwing `[Throttling: Resource is not in the state resourceRecordSetsChanged]`

### ISSUE THREAD

**Issue by ggoodman** [aws/aws-sdk-js#1018] opened 2016-06-08 19:17 UTC
The `waitFor` method of the `Route53` object occasionally errors with an Error: `[Throttling: Resource is not in the state resourceRecordSetsChanged]`.

The stack trace is as follows:

```
Error submitting Route53 update: Throttling: Resource is not in the state resourceRecordSetsChanged
    at Request.extractError (/path/to/code/node_modules/aws-sdk/lib/protocol/rest_xml.js:44:29)
    at Request.callListeners (/path/to/code/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/path/to/code/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/path/to/code/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/path/to/code/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/path/to/code/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /path/to/code/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/path/to/code/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/path/to/code/node_modules/aws-sdk/lib/request.js:617:12)
    at Request.callListeners (/path/to/code/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/path/to/code/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/path/to/code/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/path/to/code/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/path/to/code/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /path/to/code/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/path/to/code/node_modules/aws-sdk/lib/request.js:38:9)
```

Enumerable properties of the error:

```
{ [Throttling: Resource is not in the state resourceRecordSetsChanged]
  message: 'Resource is not in the state resourceRecordSetsChanged',
  code: 'ResourceNotReady',
  time: Wed Jun 08 2016 19:00:31 GMT+0000 (UTC),
  requestId: '<REDACTED>',
  retryable: false,
  originalError: 
   { message: 'Rate exceeded',
     code: 'Throttling',
     time: Wed Jun 08 2016 19:00:31 GMT+0000 (UTC),
     requestId: '<REDACTED>' },
  statusCode: 400,
  retryDelay: 30000 }
```

Some factors that make this issue very difficult to work around:

1. The `waitFor` method does not provide a (documented) option to configure the ultimate wait timeout
2. The returned error indicates that `retryable: false`.

As a consequence I will need to investigate the possibility of implementing a backoff strategy on top of the built in resource waiter. This appears to defeat the purpose of this method and would ideally be configurable at the library level.

**Comment by chrisradek** [comment] 2016-06-23 00:10
@ggoodman 
Apologies for the late response.

Are you seeing this error happen after waiting for an extended period of time? Whenever an error with the code `Throttling` is encountered, the request should be retried, as long as `maxRetries` hasn't been reached. Inside the callback you pass to `waitFor`, you can log the total `retryCount` by logging `this.retryCount`, and can compare it to `this.maxRetries`.

The returned error may show `retryable:false` if the `retryCount` hit the `maxRetries`, so I'd be interested in seeing if that's what is happening. If it isn't, we'll need to investigate further what is happening.

It's possible to configure the max wait timeout in an indirect (and not officially supported) way.
Calling `waitFor()` returns an `AWS.Request` object. You could directly modify it to change the `maxRetries` and `retryDelay` value:

```javascript
var req = route53.waitFor('resourceRecordSetsChanged', {Id: "ID"});
req.response.maxRetries = 100; //Default is 60 for this waiter
req._waiter.config.delay = 40; //Default is 30 seconds for this waiter
req.send(callback);
```
The above code could break in the future, especially the delay, so at the very least tests should be written to ensure an SDK update doesn't break it. It may be useful when troubleshooting. We have a feature request to have a public API to modify these settings.

**Comment by chrisradek** [comment] 2016-06-27 16:26
Closing this as a feature request duplicate of #881 to expose an API to configure waiters.

Please feel free to re-open if after some investigation the `retryCount` and `maxRetries` aren't equal when the `Throttling` error is encountered.

**Closed by chrisradek** 2016-06-27 16:26 UTC
Labels: Feedback Requested
