### ISSUE TITLE
secretsmanager describeSecret returns wrong result

### ISSUE THREAD

**Issue by akittana** [aws/aws-sdk-js#3307] opened 2020-06-14 16:00 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
calling describeSecret does not return the details listed in the sdk documentation or API reference guide such as rotation configuration or kms key id, instead it only returns the following info: 
```
{
    "ARN": "arn:aws:secretsmanager:XXXXXXX:XXXXXXXX:secret:test-secret-2-YjXh7H",
    "Name": "test-secret-2",
    "LastChangedDate": "2020-06-14T11:41:58.891000-04:00",
    "Tags": [],
    "VersionIdsToStages": {
        "8e4b4cff-c15f-4ccb-ac56-c18b1c5b8573": [
            "AWSCURRENT"
        ]
    }
}
```

**If on Node.js, are you running this on AWS Lambda?**
> Yes, running in lambda with the latest sdk version 2.696.0

**Details of the browser/Node.js version**
Paste output of `npx envinfo --browsers` or `node -v`

**SDK version number**
v2.696.0

* For Node.js, get SDK version by
 npm list aws-sdk
├─┬ aws-amplify@2.1.0
│ └─┬ @aws-amplify/core@2.1.0
│   └── aws-sdk@2.518.0 
├─┬ aws-appsync@3.0.2
│ ├─┬ aws-appsync-auth-link@2.0.1
│ │ └── aws-sdk@2.696.0  deduped
│ └── aws-sdk@2.518.0 
└── aws-sdk@2.696.0 

**To Reproduce (observed behavior)**
```
async function secretsmanager_describeSecret(secretsmanager, secretArn){
    return new Promise((resolve, reject) => {
        let params = {
            SecretId: secretArn
        }
    
        secretsmanager.describeSecret(params).promise()
                  .then(response => resolve(response))
                  .catch(error =>  reject(error))

      });
    
} 
```

**Expected behavior**
should return the details in https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_DescribeSecret.html or https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SecretsManager.html#describeSecret-property

**Comment by ajredniwja** [comment] 2020-06-16 02:59
@akittana Thank-you for reaching out to us with your issue. 

Was able to reproduce this, however the response is not generated by the SDK but the service, let me reach out to them and find out the root cause.

**Comment by ajredniwja** [comment] 2020-06-16 23:24
The DescribeSecret response will only contain the non-null fields associated with the secret. As a result you will only see the rotation schedule if the secret has been successfully configured for rotation. The KMS key will only be visible if it is explicitly set to a CMK other than the default key. In all other instances, the values are null and are therefore not returned.

Closing this issue now.

**Closed by ajredniwja** 2020-06-16 23:24 UTC
Labels: service-api
