### ISSUE TITLE
Unable to parse the M type of data inn DynamoDb

### ISSUE THREAD

**Issue by sandeepnegi1996** [aws/aws-sdk-js#2824] opened 2019-08-27 10:03 UTC
hello everyone 

I want to parse this document. Actually I am using IoT core and written one rule to send the data to AWS dynamoDb. Now I am fetchiing this data using DynamoDb sdk but unable to fetch the values.

```
{
  "data": {
    "M": {
      "state": {
        "M": {
          "reported": {
            "M": {
              "color": {
                "S": "brown"
              },
              "DeviceId": {
                "S": "nodedevice1"
              },
              "temperature": {
                "N": "27"
              }
            }
          }
        }
      }
    }
  },
  "DeviceId": {
    "S": "NodeDevice1"
  },
  "TimeStamp": {
    "S": "1566553626391"
  }
}
```

```javascript
var attr = require("dynamodb-data-types").AttributeValue;
  var unwrapped = attr.unwrap(data.Item.data.state);
    console.log(unwrapped);
```

I have tried unwrapping the data but it didn't help

**Comment by AllanFly120** [comment] 2019-09-09 06:52
Hey @sandeepnegi1996,

Can you show me how do you use the JavaScript SDK? I see you are using `dynamodb-data-types` package. But it's not owned by us.

**Comment by sandeepnegi1996** [comment] 2019-09-11 06:10
Hey @AllanFly120 

This is the npm package i am using in my node.js API 

npm i dynamodb-data-types

https://www.npmjs.com/package/dynamodb-data-types

You can go through this documentation where it is mentioned how to use it. 

Since my data is coming in this way the solution I came up with is improving the IoT rule in my in Amazon IoT core. 

This is the rule I am using now 
select state.reported.color,state.reported.temperature state.reported.DeviceId from '$aws/things/cividevice1/shadow/update'


After this rule is applied my data is stored in this format but this approach is not suitable since I have so many attribute in my real data which i receive in my IoT core

{
  "data": {
    "color": "new5",
    "temperature": 28
  },
  "DeviceId": "cividevice1",
  "Timestamp": "1567150807063"
}

My request is like can you guys elaborate some ways of writing the iot rule to transfer the data to DynamoDB

Thank you for your reply

**Comment by ajredniwja** [comment] 2019-10-25 20:17
Hey @sandeepnegi1996,

You can troubleshoot your rule using [cloudWatchLogs](https://github.com/aws/aws-sdk-js/issues/2824) by analyzing your logs you'd be able to get to where the issue is. 

Closing this issue for now, please re-open if you have any additional questions.

**Closed by ajredniwja** 2019-10-25 20:17 UTC
Labels: 3rd-party, guidance
