### ISSUE TITLE
ec2.describeInstances does not return all instances 

### ISSUE THREAD

**Issue by isotnikov** [aws/aws-sdk-js#704] opened 2015-09-08 09:09 UTC
I have a case when I'm trying to perform this request:

```describeInstances({DryRun: false, InstanceIds: [ 'i-43****', 'i-42****', 'i-8d****'', 'i-40****'' ]}, cb)```

and I'm getting this response:

```
{
  "data": [
    {
      "id": "i-40****'",
      "privateIp": "10.****',
      "privateDnsName": "ip-10-****'",
      "state": {
        "Code": 80,
        "Name": "stopped"
      },
      "stateReason": {
        "Code": "Client.UserInitiatedShutdown",
        "Message": "Client.UserInitiatedShutdown: User initiated shutdown"
      },
      "tags": [
        {
          "Key": "Name",
          "Value": "****'"
        }
      ]
    },
    {
      "id": "i-8d****'",
      "privateIp": "****'",
      "privateDnsName": "****',
      "state": {
        "Code": 80,
        "Name": "stopped"
      },
      "stateReason": {
        "Code": "Client.UserInitiatedShutdown",
        "Message": "Client.UserInitiatedShutdown: User initiated shutdown"
      },
      "tags": [
        {
          "Key": "Name",
          "Value": "****"
        }
      ]
    }
  ]
}
```
 i-43****, i-42**** are missing here.

But if I'm trying 

```describeInstances({ DryRun: false, InstanceIds: [ 'i-43****, 'i-42****' ]})```

i'm getting this:

```
{
  "data": [
    {
      "id": "i-43****",
      "privateIp": "10.****",
      "privateDnsName": "ip-10-****",
      "state": {
        "Code": 80,
        "Name": "stopped"
      },
      "stateReason": {
        "Code": "Client.UserInitiatedShutdown",
        "Message": "Client.UserInitiatedShutdown: User initiated shutdown"
      },
      "tags": [
        {
          "Key": "Name",
          "Value": "****"
        }
      ]
    }
  ]
}
```

so i-43**** exists and i-42***** doesn't exist. These 4 instances have the same owner and the case is reproducible every time.

Looks like describeInstances doesn't provide full information about all instances.

**Comment by AdityaManohar** [comment] 2015-09-08 22:13
@isotnikov I am not able to reproduce this with two instances that I've set up on a personal account. 

Could you also post the full code that you are using? I see that the response data you are logging differs from the response structure of the [`AWS.EC2.describeInstances()`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2.html#describeInstances-property) API operation.

**Comment by AdityaManohar** [comment] 2015-09-19 00:44
@isotnikov I'm marking this as closed as the issue cannot be reproduced and there hasn't been any recent activity on this thread. Feel free to reopen this issue or open another issue if you have other questions.

**Closed by AdityaManohar** 2015-09-19 00:44 UTC
