### ISSUE TITLE
Unable to deploy frontend changes due to Browser-builder error

### ISSUE THREAD

**Issue by jdc62** [aws/aws-sdk-js#3527] opened 2020-11-11 15:20 UTC
We use ing browser-builder available through the AWS-SDK for Javascript, detailed here - https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/building-sdk-for-browsers.html

This was working yesterday however this no longer works. When running the following -
MINIFY=1 node dist-tools/browser-builder.js > aws-sdk.js

We receive this error -

undefined:1625
    throw new JS_Parse_Error(message, filename, line, col, pos);
    ^
SyntaxError: Unexpected token name «i», expected punc «;»
    at JS_Parse_Error.get (eval at <anonymous> (/Users/gareth/Downloads/temp_test/aws-sdk-js/aws-sdk-js/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)

We have tried by cloning the most recent release ( v2.789.0) and also 2.788.0 to no avail.

The problem is reproduceable by executing these commands -

mkdir test_deploy
cd test_deploy
git clone git://github.com/aws/aws-sdk-js
cd aws-sdk-js
npm install
MINIFY=1 node dist-tools/browser-builder.js > aws-sdk.js

**Comment by ajredniwja** [comment] 2020-11-12 04:49
Hey @jdc62 thanks for opening this issue, I was not able to reproduce the error with the steps you provided. 

I did a little to research and found that it is a know issue with with uglify-js which doesn't support ES6, you can probably use something as mentioned in https://www.npmjs.com/package/uglify-js-es6#harmony

I would close this issue now since it is not related to the SDK, please feel free to ask if you have any other questions.

**Closed by ajredniwja** 2020-11-12 04:49 UTC
Labels: guidance
