### ISSUE TITLE
EnvironmentCredentials / signature failure with version 2.549

### ISSUE THREAD

**Issue by miyasudokoro** [aws/aws-sdk-js#2906] opened 2019-10-15 17:50 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Inside a lambda that runs a Websocket API Gateway, I call another API Gateway of a separate microservice to gain some information. This was working fine up until we had a new deployment a few hours ago that caused this lambda to be rebuilt with no changes. Because there were no code changes, I quickly narrowed it down to version 2.549 of the aws-sdk versus 2.548, which worked.

I get the following logged in CloudWatch:

```
{ TypeError: Data must be a string or a buffer
at Hmac.update (crypto.js:99:16)
at Object.hmac (/var/task/node_modules/aws-sdk/lib/util.js:423:50)
at Object.getSigningKey (/var/task/node_modules/aws-sdk/lib/signers/v4_credentials.js:75:36)
at V4.signature (/var/task/node_modules/aws-sdk/lib/signers/v4.js:98:36)
at V4.authorization (/var/task/node_modules/aws-sdk/lib/signers/v4.js:93:36)
at V4.addAuthorization (/var/task/node_modules/aws-sdk/lib/signers/v4.js:35:12)
at /var/task/node_modules/aws-sdk/lib/event_listeners.js:236:18
at finish (/var/task/node_modules/aws-sdk/lib/config.js:357:7)
at /var/task/node_modules/aws-sdk/lib/config.js:375:9
at EnvironmentCredentials.get (/var/task/node_modules/aws-sdk/lib/credentials.js:127:7) retryDelay: 11.538540812526632 }
```
It only happens with version 2.549. Version 2.548 does not do this.

**Is the issue in the browser/Node.js?**
Node.js v8.10

**If on Node.js, are you running this on AWS Lambda?**
Lambda

**Details of the browser/Node.js version**
v8.10

**SDK version number**
v2.549 
NOT v2.548

**To Reproduce (observed behavior)**
Here is the function being executed that rejects with the error. Debugging is a bit difficult, so this is the best I can do.

```
    /** Gets an API service configured by an apiConfig JSON file.
     *
     * @param apiName {string} name of API
     * @param params {object} default parameters for API calls (e.g. headers, querystring, etc.) -- see JSON file input member names for keys
     * @returns {Promise} resolving with an AWS.Service instance
     */
    getAPIService: function( apiName, params ) {
        try {
            let info = require( './apiConfig/' + apiName + '.json' );
            info.service.params = params;

            let service = new AWS.Service( info.service );
            let fns = Object.keys( info.service.apiConfig.operations )
                .map( function( operation ) {
                    return operation.charAt( 0 ).toLowerCase() + operation.slice( 1 );
                } );
            toolbox.promisify( service, ...fns );

            // this is a wrapper getting the SSM param value out
            return this.getSSM( info.SSM, false ) 
                .then( function( origin ) {
                    service.setEndpoint( origin + constants.API_PATH + apiName + '/' );
                    return service;
                } );
        } catch ( e ) {
            return Promise.reject( e );
        }
    }

// the JSON file loaded in the "require" call, obfuscated
{
  "SSM": "SSM-param-containing-API-origin-info",
  "service": {
    "isGlobalEndpoint": true,
    "convertResponseTypes": false,
    "apiConfig": {
      "metadata": {
        "protocol": "rest-json"
      },
      "operations": {
        "OperationOne": {
          "http": {
            "method": "GET",
            "requestUri": "something"
          },
          "input": {
            "type": "structure",
            "required": [
              "a",
              "b",
              "c",
              "token"
            ],
            "members": {
              "a": {
                "location": "querystring",
                "locationName": "a_id"
              },
              "b": {
                "location": "querystring",
                "locationName": "b_group"
              },
              "c": {
                "location": "header",
                "locationName": "c-id"
              },
              "token": {
                "location": "header",
                "locationName": "Authorization"
              }
            }
          }
        },
        "OperationTwo": {
          "http": {
            "method": "GET",
            "requestUri": "somethingelse"
          },
          "input": {
            "type": "structure",
            "required": [
              "a",
              "b",
              "c",
              "d",
              "token"
            ],
            "members": {
              "a": {
                "location": "querystring",
                "locationName": "a_id"
              },
              "b": {
                "location": "querystring",
                "locationName": "b_id"
              },
              "c": {
                "location": "querystring",
                "locationName": "c_id"
              },
              "d": {
                "location": "header",
                "locationName": "d-id"
              },
              "token": {
                "location": "header",
                "locationName": "Authorization"
              }
            }
          }
        }
      }
    }
  }
}
);
```

**Expected behavior**
I continue to be able to call my API.

**Screenshots**
I'm guessing it was this commit here based on what is in the error message.

![image](https://user-images.githubusercontent.com/7283837/66855432-6f8d7e00-ef40-11e9-8458-001ee6a7dffa.png)

**Additional context**

**Comment by AllanFly120** [comment] 2019-10-22 21:23
Hi @miyasudokoro I think this results from the PR I merged: #2899. I'm investigating the root cause of it.

**Comment by AllanFly120** [comment] 2019-10-23 16:51
Hi @miyasudokoro Seems like you are using JS SDK to call your custom API. Does your API need authentication(e.g. [AWS Signature V4](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html))? 
I think before the above PR merged, the SDK doesn's sign a request if you don't specify a `signatureVersion` in the `info.service`, but now it does. The request failed because your service model lacks the keys needed for signing a request.

**Comment by miyasudokoro** [comment] 2019-10-24 23:44
The API being called is a normal API Gateway using the typical "Authorization" header in the normal manner. There is nothing sophisticated going on with it. 

I have literally posted 100% of the code required to make simple calls between API gateways using the JS SDK `Service` feature, so I think from this you can understand why I was using it rather than rolling my own. And not just me -- this wasn't my idea. I got it from a blogger somewhere. 

From my perspective, what you are describing is simply a lack of backwards compatibility. Previously, `signatureVersion` was not a required field, and using signatures was optional. If you are choosing to make it a required field from now on, and to make signatures required as well, I don't believe that is a minor update, at least as I understand semantic versioning. It's quite a breaking change for me. (FYI, in this case, it was a "complete bricking of the entire app" change, which at least made it easy to catch long before it went to production.)

**Comment by AllanFly120** [comment] 2019-10-25 18:00
@miyasudokoro 

Can you share the blog post you mentioned? As a workaround, instead of calling operations attached to `service` directly, you can try calling [`service.makeUnauthenticatedRequest()`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Service.html#makeUnauthenticatedRequest-property). This will remove the signing step in the request lifecycle.

**Comment by miyasudokoro** [comment] 2019-11-15 23:45
Are you planning to fix this or not?

**Comment by ajredniwja** [comment] 2019-11-20 22:48
@miyasudokoro, At this time, the team will not be reverting the change in #2899.  ```apiConfig``` was not intended to be part of the public API for use with ```AWS.Service```.  We’ve tagged this issue as a documentation task to help make that more clear. For your use case, we suggest setting the ```authType``` explicitly or using ```makeUnauthenticatedRequest```.

**Closed** 2019-11-20 22:49 UTC
Labels: documentation, guidance
