### ISSUE TITLE
TypeError: util.isNode is not a function

### ISSUE THREAD

**Issue by onhate** [aws/aws-sdk-js#3601] opened 2021-01-13 14:31 UTC
**Describe the bug**

I'm getting `TypeError: util.isNode is not a function` here https://github.com/aws/aws-sdk-js/blob/54f8555bd94d33a1754a44a35286f1d9e31c28a3/lib/dynamodb/types.js#L26 when

```
import DynamoDBSet from 'aws-sdk/lib/dynamodb/set';

new DynamoDBSet([1, 2]);
```

```
    at isBinary (.../node_modules/aws-sdk/lib/dynamodb/types.js:26:12)
    at typeOf (.../node_modules/aws-sdk/lib/dynamodb/types.js:6:36)
    at Set.detectType (.../node_modules/aws-sdk/lib/dynamodb/set.js:35:37)
    at Set.initialize (.../node_modules/aws-sdk/lib/dynamodb/set.js:28:10)
    at new Set (.../node_modules/aws-sdk/lib/dynamodb/set.js:22:10)
```

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
```
node -v
v12.18.4
```

**SDK version number**
v2.826.0

**To Reproduce (observed behavior)**

```
import DynamoDBSet from 'aws-sdk/lib/dynamodb/set';

new DynamoDBSet([1, 2]);
```

**Expected behavior**
No errors ¯\_(ツ)_/¯

**Additional context**
I cannot find the isNode method on https://github.com/aws/aws-sdk-js/blob/master/lib/util.js

https://github.com/aws/aws-sdk-js/blob/54f8555bd94d33a1754a44a35286f1d9e31c28a3/lib/dynamodb/types.js#L26

**Comment by onhate** [comment] 2021-01-13 14:36
this is the PR that removed it https://github.com/aws/aws-sdk-js/pull/2253 but it seems to still be refered if you search for util.isNode or util.isBrowser in the source code.

**Comment by onhate** [comment] 2021-01-13 15:02
I noticed it actually started happening after updating a dev dependency of jest-dynalite that introduced this new dependency `@aws/dynamodb-auto-marshaller@^0.7.1`

Downgrading jest-dynalite (consequently removes the dependency) it works as expected.

**Comment by freshollie** [comment] 2021-01-13 15:24
I'm not 100% sure why installing a newer version of `jest-dynalite` has caused issues for you. The issue is caused by your import path by passing `aws-sdk` `node-loader` which adds the `.isNode` to the util object. https://github.com/aws/aws-sdk-js/blob/54f8555bd94d33a1754a44a35286f1d9e31c28a3/lib/aws.js

**Comment by freshollie** [comment] 2021-01-13 15:35
I can reproduce without jest-dynalite. You can solve by fixing your import to import, but I think this is still a bug.

package.json
```
{
  "name": "issue-repro",
  "version": "1.0.0",
  "license": "MIT",
  "dependencies": {
    "aws-sdk": "2.826.0"
  }
}
```

test.js
```js
const DynamoDBSet = require('aws-sdk/lib/dynamodb/set');

new DynamoDBSet([1, 2]);
```

```
.../node_modules/aws-sdk/lib/dynamodb/types.js:26
  if (util.isNode()) {
           ^

TypeError: util.isNode is not a function
    at isBinary (.../node_modules/aws-sdk/lib/dynamodb/types.js:26:12)
    at typeOf (.../node_modules/aws-sdk/lib/dynamodb/types.js:6:36)
    at Set.detectType (.../node_modules/aws-sdk/lib/dynamodb/set.js:35:37)
    at Set.initialize (.../node_modules/aws-sdk/lib/dynamodb/set.js:28:10)
    at new Set (.../node_modules/aws-sdk/lib/dynamodb/set.js:22:10)
    at Object.<anonymous> (.../test.js:3:1)
```

**Comment by ajredniwja** [comment] 2021-01-14 23:51
Hi @onhate https://github.com/aws/aws-sdk-js/blob/acd59da2881dd69ea40499cd82c7a1264ef09524/lib/dynamodb/set.js#L14-L16

We recommend our users to not use this API since it is private, customers can workaround it if they are using it in their app, you can require `lib/nodeloader.js` to workaround it as well or 'aws-sdk` but again the API was not designed for customers use so we dont recommend using it. 

Closing this issue now, please reach out if you have any other questions.

**Closed by ajredniwja** 2021-01-14 23:51 UTC
Labels: bug, needs-triage
