### ISSUE TITLE
s3.upload is storing empty data when Body is a request module response stream.

### ISSUE THREAD

**Issue by aniltallam** [aws/aws-sdk-js#1277] opened 2016-12-20 14:35 UTC
s3.upload is storing empty data when Body is a request module response stream.

code:
```
request(getOptions).on('response', function (response) {
    var destinationParams = { Key: 'key1', Body: response}
    s3Client.upload(destinationParams, function (err, data) {
            //...
    })
})
```

**Comment by aniltallam** [comment] 2016-12-20 15:22
Investigation:
Actually request module is registering to 'data' event on response streams. Aws s3 upload is listening to readable event and trying to get data using response.read() which is returning null because data was already drained using 'data' event handler by request module. so it empty data is sent to aws server.

So currently we are using this workaround:

```
request(getOptions).on('response', function (response) {
    var readableStream = new PassThrough()
    response.pipe(readableStream)
    var destinationParams = { Key: 'key1', Body: readableStream}
    s3Client.upload(destinationParams, function (err, data) {
            //...
    })
})
```

It would be clean and idle if s3client handles this scenario like other modules like fs (writeFile), process.stdout which are able to fetch data from request->response stream.
eg: 
```
fs.writeFile(request_response)
```
(or)
```
request_response.pipe(process.stdout)
```

**Comment by jeskew** [comment] 2017-01-06 20:43
@aniltallam Have you tried using the [`createReadStream`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html#createReadStream-property) method on the request to create a readable stream rather than attaching a listener to the `'response'` event?

**Comment by aniltallam** [comment] 2017-01-09 09:55
@jeskew here request method is from request npm module (`var request = require('request')`)

**Comment by jeskew** [comment] 2017-01-09 20:53
Thanks for clarifying! There's some discussion in https://github.com/aws/aws-sdk-js/issues/686 about `request` binding to the 'data' event and thereby changing the underlying stream from paused mode to flowing mode, which means that there could be data lost between when the request data starts arriving and when the SDK begins uploading to S3. I'm closing this issue as a duplicate of the original one, but please feel free to renew the discussion on that issue.

In the meantime, have you tried using `request`'s `.pipe()` method instead? They have an example of how to do so [in their README](https://github.com/request/request#streaming).

**Closed by jeskew** 2017-01-09 20:53 UTC
Labels: Duplicate
