### ISSUE TITLE
ECS: deleteService() does not delete the service

### ISSUE THREAD

**Issue by chris-hinds** [aws/aws-sdk-js#4189] opened 2022-08-19 10:54 UTC
### Describe the bug

When deleting an ECS service with either the V2 SDK or the AWS CLI the service is just returned after a successful response.

I am trying to delete a service with a status of `INACTIVE`

Calling the deleteService endpoint returns a success response and doesn't error however instead of returning `null` as the documentation indicates it returns the service object instead of deleting it.

EDIT: Looking at the types it looks like it is expected for the service to be returned when deleting.

So does the service simply sit in an inactive state for a while? I am programmatically creating services and when deleting a service sometimes need to create. anew service with the same name

### Expected Behavior

The service should be deleted and the SDK should return `null` as described in the documentation for a successful response.

### Current Behavior

A successful response returns the service object instead of deleting it.

### Reproduction Steps

```
const params: AWS.ECS.DeleteServiceRequest = {
      service: 'service-name',
      cluster: 'cluster',
      force: true,
    };

 await Clients.ecs.deleteService(params).promise();
```

### SDK version used

2

### Environment details (OS name and version, etc.)

macOS Monterey - 12.4

**Comment by ajredniwja** [comment] 2022-08-22 11:30
Hey @chris-hinds thanks for opening this issue, 

[DeleteServiceResponse](https://github.com/aws/aws-sdk-js/blob/5c33aa0399396bf40a84c18300aa99549631cbbe/apis/ecs-2014-11-13.normal.json#L2848) shows it to return the service name. 

Example :
```js
{
  service: {
    serviceArn: 'arn:aws:ecs:us-west-2:xtt',
    serviceName: 'xyz',
    clusterArn: 'arn:aws:ecs:us-west-2:xtt',
    loadBalancers: [],
    serviceRegistries: [],
    status: 'INACTIVE',
    desiredCount: 0,
    runningCount: 0,
    pendingCount: 0,
    launchType: 'FARGATE',
    platformVersion: 'LATEST',
    taskDefinition: 'arn:aws:ecs:us-west-2:xtt',
    deploymentConfiguration: {
      deploymentCircuitBreaker: [Object],
      maximumPercent: 200,
      minimumHealthyPercent: 100
    },
    deployments: [ [Object] ],
    roleArn: 'arn:aws:iam::xtt',
    events: [],
    createdAt: 2022-08-22T11:00:17.449Z,
    placementConstraints: [],
    placementStrategy: [],
    networkConfiguration: { awsvpcConfiguration: [Object] },
    schedulingStrategy: 'REPLICA',
    createdBy: 'arn:aws:iam::aj',
    enableECSManagedTags: true,
    propagateTags: 'NONE',
    enableExecuteCommand: false
  }
}
```
I see that you cant see the service in the console but if you try to do a delete call using the SDK it returns the service with `status: inactive`. Its likely thats the desired behavior and in the background service is marked inactive when deleted. I dont think its the bug with the SDK but a feature request. 
Also some behavior on how deleteService works here: https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DeleteService.html

Which mentions "Services in the DRAINING or INACTIVE status can still be viewed with the [DescribeServices](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DescribeServices.html) API operation. However, in the future, INACTIVE services may be cleaned up and purged from Amazon ECS record keeping, and [DescribeServices](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DescribeServices.html) calls on those services return a ServiceNotFoundException error."

**Comment by ajredniwja** [comment] 2022-08-28 11:52
Hearing from the team this is done by design.  Services are still discoverable in the account for a little bit after they are deleted.

**Comment by ajredniwja** [comment] 2022-08-28 11:53
Closing this issue now, please reach out if you have any other questions.

**Closed by ajredniwja** 2022-08-28 11:53 UTC
Labels: feature-request, service-api
