### ISSUE TITLE
PutMetricData doesn't support Gzip?

### ISSUE THREAD

**Issue by erothmayer** [aws/aws-sdk-js#2297] opened 2018-10-10 22:56 UTC
The API docs state 'you can send a payload compressed by gzip', however the JS SDK doesn't seem happy with a GZip blob at any sensible location (I tried the entire 'params' map, as well as just gzip on MetricData)

https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutMetricData.html

I looked through the parameter shapes and it doesn't appear that it accepts gzip data anywhere: https://github.com/aws/aws-sdk-js/blob/55a97ad8726b14f228a9182768680c2051386593/apis/monitoring-2010-08-01.min.json#L553

Is this a feature gap, and if so, could it be addressed? Or am I just missing something that would make this work?

**Comment by srchase** [comment] 2018-10-10 23:05
Hello @erothmayer,

Thanks for submitting this request.   There's an open Feature Request to add that functionality to the SDK: https://github.com/aws/aws-sdk-js/issues/1435

As this is a duplicate of that issue, I'd like to close this issue.  If you have additional feedback, please join the discussion in the other issue.

**Comment by erothmayer** [comment] 2018-10-10 23:12
@srchase Could you please double check that this is really a duplicate? It's a completely different API (S3 as opposed to CloudWatch.Metrics.PutMetricData). And I'm not necessarily looking for the SDK to internally gzip for me -- I'm happy to gzip it myself, but right now the parameter validator doesn't allow a gzip blob, even though the API claims to support it.

Whatever gets it solved is fine at the end of the day, but these don't look like duplicates from my admittedly outside perspective...

**Comment by erothmayer** [comment] 2018-10-10 23:14
I also just noticed that the linked issue has been open for 1.5 years with no sign of a resolution in sight. I'd really like to avoid linking the two together if a minimal correction for PutMetricData could be done more quickly (which seems possible since it may just be a validator shape definition change)

**Comment by erothmayer** [comment] 2018-10-10 23:36
thanks @srchase !

**Comment by srchase** [comment] 2018-10-11 16:46
@erothmayer 

The SDK does support setting headers:

```
cloudWatch.putMetricData(params)
  .on('build', function(req) { req.httpRequest.headers['Content-Encoding'] = 'gzip'; })
  .send((err,data) => {
    console.log(err,data); 
  });
```

But as you pointed out, the validator won't accept a gzip blob.

I'm marking this as its own Feature Request so that the team can discuss further.

**Comment by srchase** [comment] 2018-10-12 17:44
@erothmayer 

Can you give this a try?  This uses onAsync to set the encoding header, and to replace the body with the gzipped after validation.

```
cloudWatch.putMetricData(params)
  .onAsync('build', function(req,done) {
    req.httpRequest.headers['Content-Encoding'] = 'GZIP';
    zlib.gzip(req.httpRequest.body, function(err, result) {
      req.httpRequest.body = result;
      done();
    })
  })
  .send()
```

onAsync is not currently public, but there is now an open PR to make that documented and add types for its use: https://github.com/aws/aws-sdk-js/pull/2299

You can pin to a current version of the SDK to avoid any issues for when that gets pulled in, or else wait until we've released it.

**Comment by srchase** [comment] 2018-10-16 17:19
This change was merged in.  Going to close out this issue now.

**Comment by erothmayer** [comment] 2018-10-16 21:04
@srchase tried it out, works perfectly! Thank you so much for the rapid turnaround!

**Closed** 2018-10-16 21:05 UTC
Labels: Documentation
