### ISSUE TITLE
The AppRunner Service Status lacks sufficient explanation.

### ISSUE THREAD

**Issue by koya1616** [aws/aws-sdk-js#4569] opened 2024-01-06 07:02 UTC
### Describe the issue

- DELETED
- DELETE_FAILED
- PAUSED
- CREATE_FAILED

Please add explanations for the above statuses in the code below
https://github.com/aws/aws-sdk-js/blob/66f02361c28ca440542c79780e1ea7dc9bb988be/clients/apprunner.d.ts#L1468

### Links

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/apprunner/describe-service.html#output
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/AppRunner.html#describeService-property

**Comment by aBurmeseDev** [comment] 2024-01-10 02:15
Hi @koya1616 - thanks for reaching out and sharing this feedback. 

Upon checking the `Status` output in the docs, I see that both `CREATE_FAILED` and `DELETE_FAILED` has descriptive explanation but missing for `DELETED` and `PAUSED`. Can you please confirm that's what you're referring to? 

Please note that these SDK docs are generated upstream by the [service docs](https://docs.aws.amazon.com/apprunner/latest/api/API_Service.html#API_Service_Contents) which I also checked and confirmed that it reflects our current SDK docs. With that said, I might have to reach out to service team to update the docs to add the explanation for the rest of the status values.


>Status
The current state of the App Runner service. These particular values mean the following.
>
>CREATE_FAILED – The service failed to create. The failed service isn't usable, and still counts towards your service quota. To troubleshoot this failure, read the failure events and logs, change any parameters that need to be fixed, and rebuild your service using UpdateService.
>
>DELETE_FAILED – The service failed to delete and can't be successfully recovered. Retry the service deletion call to ensure that all related resources are removed.
>
>Type: String
>
>Valid Values: CREATE_FAILED | RUNNING | DELETED | DELETE_FAILED | PAUSED | OPERATION_IN_PROGRESS

Thanks again for reaching out with the feedback on our docs!
John

**Comment by koya1616** [comment] 2024-01-14 10:40
@aBurmeseDev 
Oh, I'm sorry I didn't check [service docs](https://docs.aws.amazon.com/apprunner/latest/api/API_Service.html#API_Service_Contents)

```
aws apprunner describe-service help
```

I run above command. And I read following description.
I thought "There is Only two types of status?".

```
          Status -> (string)
             The current state of the App Runner service. These particular
             values mean the following.

             o CREATE_FAILED - The service failed to create. To troubleshoot
               this failure, read the failure events and logs, change any
               parameters that need to be fixed, and retry the call to create
               the service. The failed service isn't usable, and still counts
               towards your service quota. When you're done analyzing the
               failure, delete the service.

             o DELETE_FAILED - The service failed to delete and can't be
               successfully recovered. Retry the service deletion call to
               ensure that all related resources are removed.
```

Is this not relevant?

**Comment by aBurmeseDev** [comment] 2024-08-22 21:28
Apologies for the delay response. As stated in our docs, there are total of 6 valid status values you can use. Though only two of the status has descriptions. I reached out to service team with the feedback to add descriptions for all status.

`Valid Values: CREATE_FAILED | RUNNING | DELETED | DELETE_FAILED | PAUSED | OPERATION_IN_PROGRESS`

Since there are no actionable items for the SDK team, and this repository is dedicated solely to SDK-related issues, I will close this case. Feel free to reach out again.

**Closed by aBurmeseDev** 2024-08-22 21:28 UTC
Labels: documentation, p3
