### ISSUE TITLE
Using role arn from config instead of credentials

### ISSUE THREAD

**Issue by crystalin** [aws/aws-sdk-js#1347] opened 2017-02-06 23:18 UTC
In shared_ini_file_credentials.js (at least), the role is taken from the credentials file but should be taken from the config file

**Comment by jeskew** [comment] 2017-02-07 21:33
I spoke with a member of the CLI team and was told that if there is a `role_arn` present in both `~/.aws/credentials` and `~/.aws/config`, the ARN present in `~/.aws/credentials` will be used. To maintain consistency, this SDK would use the same preference order.

However, this SDK does not currently support reading configuration from the `~/.aws/config` file, though there is an open feature request (#1296) to add such support. I'm closing this as a duplicate of that request so that discussion of this feature can be kept in one place. Please feel free to comment there or +1 that issue.

**Closed by jeskew** 2017-02-07 21:33 UTC
Labels: Duplicate
