### ISSUE TITLE
aws-sdk missing autoscaling.js

### ISSUE THREAD

**Issue by greenboxent** [aws/aws-sdk-js#709] opened 2015-09-10 18:49 UTC
I tried npm install aws-sdk. it installed with no issues that I could see.
When I try require('aws-sdk') it says it is missing autoscaling.js and fails. version 2.1.50

**Comment by AdityaManohar** [comment] 2015-09-10 18:57
@greenboxent I am unable to reproduce this issue on a fresh npm install of the SDK.

```sh
$> npm install aws-sdk@2.1.50
```

```javascript
// code.js

var AWS = require('aws-sdk');
console.log(AWS.VERSION);
```

Perhaps you can try reinstalling using npm. Any other information that you can provide in helping reproduce this issue will be helpful.

**Comment by AdityaManohar** [comment] 2015-09-19 00:43
@greenboxent I'm marking this as closed since the issue cannot be reproduced and there hasn't been any recent activity on this issue. Feel free to reopen this issue or open another issue if you have other questions.

**Closed by AdityaManohar** 2015-09-19 00:43 UTC
