### ISSUE TITLE
release 2.6.4 breaks loading credentials from ~/.aws/credentials file

### ISSUE THREAD

**Issue by skysteve** [aws/aws-sdk-js#1151] opened 2016-09-21 15:09 UTC
Having updated to 2.6.4 our deployments to s3 started breaking this morning. We're getting the following error. If I downgrade to 2.6.3, that error goes away, upgrade to 2.6.4 it comes back. It's very repeatable both on my box and our continuous deployment box.

```
/Volumes/SourceCode/client-script-build/node_modules/aws-sdk/lib/node_loader.js:46
AWS.util.update(AWS.Config.prototype.keys, {
                          ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/Volumes/SourceCode/client-script-build/node_modules/aws-sdk/lib/node_loader.js:46:27)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/SourceCode/client-script-build/node_modules/aws-sdk/clients/sts.js:1:63)
    at Module._compile (module.js:556:32)
```

Our credentials are being loaded from a ~/.aws/credentials file (we're just doing ```const s3 = new AWS.S3();``` in code)

**Comment by chrisradek** [comment] 2016-09-21 16:11
@skysteve 
Can you share what version of Node.js you're using, and a sample script that shows this error?

Using multiple versions of Node.js and the latest version of the SDK, I tried this simple script:
```javascript
var AWS = require('aws-sdk');
var s3 = new AWS.S3();
s3.listBuckets(console.log);
```
I don't get any errors, and my credentials are also sourced from `~/.aws/credentials`

**Comment by skysteve** [comment] 2016-09-21 17:17
@chrisradek that happened on Node 6.2.2 and 6.6.0

Code wise it's something like

```
const AWS = require('aws-sdk');
const path = require('path');
const glob = require('glob');
const fs = require('fs');
const mime = require('mime');

const uploadToS3 = (bundleDir, file, config) => {
  const bucket = config.bucket;
  const s3 = new AWS.S3();

  const name = file.replace(`${bundleDir}${path.sep}`, '');

  return new Promise((resolve, reject) => {
    fs.readFile(file, (fileErr, data) => {
      if (fileErr) {
        return reject(fileErr);
      }

      const params = {
        ACL: 'public-read',
        Bucket: bucket,
        Key: name,
        Body: data,
        ContentType: mime.lookup(file)
      };

      s3.putObject(params, (err) => {
        if (err) {
          return reject(`Unable to upload ${params.Key} to ${params.Bucket}. Err: ${err.message}`);
        }

        console.log(`uploaded ${file} to ${params.Bucket}::${name}`);

        resolve(`/${name}`);// to invalidate cache, name must start with /
      });
    });
  });
};

uploadToS3('/example', 'example.js', {bucket : '1234'});

```

**Comment by chrisradek** [comment] 2016-09-21 17:27
@skysteve 
Your example with Node.js 6.6.0 runs perfectly on my system. What OS are you running on?

Also, do your credentials assume a role? Does my above example run on your machine?

**Comment by skysteve** [comment] 2016-09-21 17:57
That was on OSX El Capitan on my laptop and ubuntu 14.04 on our CI server.

I'm not at work anymore (UK timezone) so It'll have to wait for the morning, but as I said, downgrading to 2.6.3 everything worked as expected, upgrading to 2.6.4 it broke, and downgrading again it worked (consistently). Not sure what might be going on :S

**Comment by skysteve** [comment] 2016-09-22 08:52
Hey, so your example does run fine on my mac, I'll do a bit of playing around today and see if I can get something which recreates the problem

**Comment by chrisradek** [comment] 2016-10-18 17:42
Closing since we haven't been able to reproduce, and the example is working on your machine. Please let us know if you are still having issues.

**Closed by chrisradek** 2016-10-18 17:42 UTC
Labels: Feedback Requested, Question
