### ISSUE TITLE
I probably shouldn't be able to submit a spot instance request with a SpotBid of $NaN

### ISSUE THREAD

**Issue by jhford** [aws/aws-sdk-js#495] opened 2015-02-05 14:51 UTC
While developing an application which uses this sdk, I accidentally was generating spot bids that were not numbers (0.040.050.04 / 3).  The SDK didn't catch this error and the request succeeded, but the EC2 management console showed $Nan as the price.  Sadly there's a bug in Firefox which cased my screenshots to be all black, so I can't attach them.

There should probably be something in either the SDK or the API host that blocks Nan from being submitted.

**Comment by AdityaManohar** [comment] 2015-02-05 20:48
Which version of the SDK are you using? I tried the following and it doesn't go through (which is expected). I'm using SDK v2.1.8 and Node v0.10.35

```javascript
var AWS = require('aws-sdk');
var ec2 = new AWS.EC2();
var params = {
  SpotPrice: '0.040.050.04 / 3', 
  LaunchSpecification:{
    InstanceType:'m3.medium', 
    ImageId:'ami-ddfea7ed'
  }
}

ec2.requestSpotInstances(params, function (err,data){
  if (err) console.log(err);
  else console.log(data);
});
```
Here is the error:
```
InvalidParameterValue: Value (0.040.050.04 / 3) for parameter price is invalid. "0.040.050.04 / 3" is an invalid spot instance price
```

**Comment by AdityaManohar** [comment] 2015-02-09 18:01
@jhford 
I'm closing this out as the problem is not reproducible, and there hasn't been any recent activity. 

FWIW, the SDK does not perform any regular expression or value validation. This error is returned by EC2 itself. 

Please feel free to reopen this issue or open another issue if you have any other questions.

**Closed by AdityaManohar** 2015-02-09 18:01 UTC
