### ISSUE TITLE
DynamoDB.DocumentClient does not throw any error and fails to insert non stringified objects.

### ISSUE THREAD

**Issue by swarajgiri** [aws/aws-sdk-js#808] opened 2015-11-23 07:12 UTC
### Steps to reproduce

```js
'use strict'

class Item {
    constructor() {
        this.id = null;
        this.name = null;
    }
}

let item = new Item();
item.id = 1;
item.name = 'Item 1';

let item2 = new Item();
item2.id = 2;
item2.name = 'Item 2';

let payload = {
    'id': '231',
    'items': []
};

payload.items.push(item1);
payload.items.push(item2);

let aws = require('aws-sdk');

let dynamodb = new aws.DynamoDB.DocumentClient();

dynamodb.put({'TableName': 'valid-table-name', 'Item': payload}, function (err, data) {
    if (err) {
        console.log('Err => ', err);
    }
});
```
The above code inserts the payload without the contents of `payload.item` and does not throw any error.

However, the payload is inserted properly if i `stringify` the objects being pushed into payload.
```js
payload.items.push(JSON.stringify(item1));
payload.items.push(JSON.stringify(item2));
```

Can you please let me know if users are expected to only throw in stringified objects to the `DocumentClient`?

**Comment by chrisradek** [comment] 2015-11-24 01:34
@swarajgiri 
The `AWS.DynamoDB.DocumentClient` accepts JSON objects, but not instantiated objects. The root of this behavior is in how the client converts inputs into a format that DynamoDB understands.

Specifically, you can see what types of inputs are supported by the client by looking at the `convertInput` function: https://github.com/aws/aws-sdk-js/blob/master/lib/dynamodb/converter.js#L5

You'll notice that `typeOf` is called on inputs, and for objects instantiated from a function, `typeOf` returns the function name. Since the function name won't fulfill any of the conditionals, those inputs are ignored. If functions were also converted, you may see some unexpected fields, such as those on the prototype chain, being saved to DynamoDB as well.

I hope that clarifies things!  I'm going to close this issue, but feel free to comment or re-open if you want to discuss this further.

**Closed by chrisradek** 2015-11-24 01:34 UTC

**Comment by swarajgiri** [comment] 2015-11-25 04:47
`stringify` would remove the prototype chain. If that's not acceptable for some reason, the sdk should at least throw an error instead of ignoring some part of the item to be inserted.

**Comment by chrisradek** [comment] 2015-11-25 17:11
@swarajgiri 
Didn't you indicate stringify worked?  If so, I'm not sure what the issue is there. You could also create a function on the prototype to return a plain JSON object as well, in case you were using those classes elsewhere.

**Comment by swarajgiri** [comment] 2015-11-26 03:50
@chrisradek - The issue is, as the title suggests,  `DocumentClient` at least should throw an error instead of silently failing

**Comment by pkarl** [comment] 2016-04-03 21:31
:+1: for throwing an error when there's an error.
