### ISSUE TITLE
SDK not picking up credentials when running in ECS

### ISSUE THREAD

**Issue by cuipengfei** [aws/aws-sdk-js#1878] opened 2018-01-14 06:47 UTC
I have this code:

```js
const uploadAllToS3 = () => {
    console.log("upload useless file to s3, just to test access rights");
    new AWS.S3().putObject({
        Bucket: scheduledJobsConstants.s3BucketName(),
        Key: `test/${new Date()}.txt`, Body: "Hello!",
    }, (err) => {
        console.log(`env:${inspect(process.env)}
        provider:${AWS.CredentialProviderChain.defaultProviders}
        cred:${inspect(AWS.config.credentials)}
        err:${inspect(err)}`.replace(/(\r\n|\n|\r)/gm, ""));
    });
};
```

When this code runs in ecs(which assumes a role that has access to the S3 bucket), I will get this in the log:

The env part of the log:
```
env: {
    PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    HOSTNAME: '485bbd95f87d',
    AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: '/v2/credentials/be3d4d7c-28b6-47e6-8081-cd746d95cb28',
    ECS_CONTAINER_METADATA_FILE: '/opt/ecs/metadata/8c0b731d-49ce-4e19-bf79-64087b433876/ecs-container-metadata.json',
    NODE_VERSION: '8.9.4',
    YARN_VERSION: '1.3.2',
    NPM_CONFIG_PROGRESS: 'false',
    HOME: '/root'
  }
```
The "AWS_CONTAINER_CREDENTIALS_RELATIVE_URI" is present in env var, so I assume the sdk should be able to pick that up.

The provider part of the log is just 4 functions that's defined in the sdk code, the 4th of which would return "ECSCredentials" if it sees "AWS_CONTAINER_CREDENTIALS_RELATIVE_URI" in env var.

Strangely the cred part of the log is "null" in ECS.
When I run this locally(where I manually assume a role), the cred part of the log is "EnvironmentCredentials", and the file gets uploaded to S3.

The err part of the log is:
`{ Forbidden: null    at Request.extractError (/app/node_modules/aws-sdk/lib/services/s3.js:557:35)    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:105:20)    at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:77:10)    at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)    at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)    at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)    at /app/node_modules/aws-sdk/lib/state_machine.js:26:10    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)    at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:685:12)    at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:115:18)  message: null,  code: 'Forbidden',  region: null,  time: 2018-01-14T06:30:00.490Z,  requestId: '4E7121D88BA0FEF1',  extendedRequestId: 'D5uiXf5EI/OLHeaPhYX67C384ba3SF1I950N78hJWw8Vv4XGQ0opSLOQlXaxVFW31g252dx8YUc=',  cfId: undefined,  statusCode: 403,  retryable: false,  retryDelay: 118.50320949834776 }`

Is there anything wrong with my code or my env var?

Should I print more logs to help diagnose this problem?

Please advise, thanks.

**Comment by cuipengfei** [comment] 2018-01-14 08:20
Update:

I have ran this code in ECS
```
    const curlCommand = `curl http://169.254.170.2${process.env.AWS_CONTAINER_CREDENTIALS_RELATIVE_URI}`;
    exec(curlCommand, (error, stdout, stderr) => {
        console.log(`${curlCommand} err:${error} out:${stdout} stderr:${stderr}`);
    });
```

The result I got is:
```
  {
    "SecretAccessKey": "long string",
    "Token": "very long string",
    "Expiration": "2018-01-14T08:55:04+0000",
    "AccessKeyId": "shorted string"
  }
```

So if the sdk had called http://169.254.170.2${process.env.AWS_CONTAINER_CREDENTIALS_RELATIVE_URI}, it should have gotten a correct response.

**Comment by cuipengfei** [comment] 2018-01-14 13:36
ok, got it working.

```js
    AWS.config.credentials = new AWS.ECSCredentials({
        httpOptions: {timeout: 5000}, // 5 second timeout
        maxRetries: 10, // retry 10 times
    });
```

I set the credentials explicitly, then it started working.

Still don't know why AWS.config.credentials could be null when this code was not there.

**Comment by climberwoodi** [comment] 2018-01-15 15:16
I have a similar problem. I get the error "Missing credentials in config"when trying to access s3. However, the problem only occurs if I want to access from my Windows 7 machine. Everything works as usual from the ECS. A few days ago everything was working with the same configuration.

`  AWS.config.credentials = new AWS.EC2MetadataCredentials({
        httpOptions: {timeout: 10000}
    });
   AWS.config.region = 'eu-central-1';`

OS: Windows 7
NodeJs: 8.9.4

**Comment by chrisradek** [comment] 2018-01-15 17:38
@climberwoodi 
How are you sourcing your credentials when you run the SDK locally?

@cuipengfei 
You're right that the default provider chain should have used the ECS Credential provider. It's great that you've already found a solution for your issue, but if you want to keep going down the rabbit hole, could you also log what the credentials in your S3 client's config looks like?

```javascript
var s3 = new AWS.S3();
s3.putObject(/*params*/, (err, data) => {
  console.log(s3.config.credentials);
});
```

The AWS.config.credentials is resolved when the SDK is imported/require'd for the first time, unless the credentials are retrieved asynchronously (such as EC2/ECS Credential Providers). When you create a new service client (e.g. new AWS.S3()), the configuration that is passed to the service client is merged into a `clone` of the global (AWS.config) configuration. When you call an operation, the credentials will be resolved if they haven't already, but that resolution will only affect your local client. Since the AWS.config.credentials was undefined when the config was cloned, it still appears to be undefined after your service client resolves its configuration.

In your new example, you manually set the AWS.config.credentials object, so a reference to that object is included with the cloned global config that S3 service client uses.

Sorry for the long response, let me know if that's unclear. Regardless, you shouldn't have to resort to your work-around to use ECS credentials.

**Comment by climberwoodi** [comment] 2018-01-15 18:01
The problem is fixed. Sorry, that was a configuration error I caused.

**Comment by cuipengfei** [comment] 2018-01-18 09:56
@chrisradek 
I will remove the code that sets the credentials explicitly and log the value of s3.config.credentials in the callback.
I will post back later.

Thanks

**Comment by cuipengfei** [comment] 2018-01-25 14:14
Problem solved.

It was somehow related to node version.

My code was running in ECS, with a base docker image: node:8.9.4.

I switched to node:9.4, which is the latest version, that solved the problem.

Don't know why, but it's working now.

**Comment by srchase** [comment] 2018-08-27 23:53
Glad to see this was resolved.

**Closed by srchase** 2018-08-27 23:53 UTC
Labels: Question

**Comment by abirtley** [comment] 2019-07-24 02:43
I know this is old, and closed, but to provide further assistance to anyone who stumbles upon this: You need to be using an up-to-date version of the AWS SDK in order to get the permissions from the ECS instance. That may sound obvious, but one of your node_modules may be using an outdated version of the SDK, which can mask the problem.
