### ISSUE TITLE
cognitoIdentityServiceProvider signUp and initiateAuth

### ISSUE THREAD

**Issue by escar** [aws/aws-sdk-js#3419] opened 2020-08-27 15:17 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
First calls to `cognitoIdentityServiceProvider` `signUp` and `initiateAuth` take between 2 and 3 seconds.
Further calls take between 200-300 milliseconds. 

**Is the issue in the browser/Node.js?**
Node.js (Typescript)

**If on Node.js, are you running this on AWS Lambda?**
Yes

**Details of the browser/Node.js version**
Node.js 12.x

**SDK version number**
2.740.0 (updated today, the same result was happening with 2.606.0)

**To Reproduce (observed behavior)**
Just executed this:

```
import { CognitoIdentityServiceProvider } from 'aws-sdk';
import {
    AttributeListType,
    InitiateAuthRequest,
    InitiateAuthResponse,
    SignUpRequest,
    SignUpResponse,
} from 'aws-sdk/clients/cognitoidentityserviceprovider';
// ...
constructor() {
   this.cognitoIdentityServiceProvider = new CognitoIdentityServiceProvider();
}
```
for `signup`
```
const params: SignUpRequest = {
   UserAttributes: attributeList,
   ClientId: clientId,
   Username: username,
   Password: password,
};
const response: SignUpResponse = await this.cognitoIdentityServiceProvider.signUp(params).promise();
``` 
and this for `initiateAuth`:

```
const request: InitiateAuthRequest = {
   AuthFlow: 'CUSTOM_AUTH',
   ClientId: clientId,
   AuthParameters: {
      USERNAME: username,
   },
};
const response: InitiateAuthResponse = await this.cognitoIdentityServiceProvider.initiateAuth(request).promise();
```

**Expected behavior**
If I haven't executed this for a while, each one of these functions takes between 2 and 3 seconds. If I execute the code again, immediately after, each one takes around 200-300ms.
It's like a cold start...

**Screenshots**
none

**Additional context**
These functions are executed within a lambda. I measured the time `console.time`, but also wrapped x-ray around the functions, which helps to confirm this.

**Comment by ajredniwja** [comment] 2020-09-01 12:07
@escar Thanks for opening this up, I believe this is a limitation of the current SDK. I would like to point you to the [V3 of the SDK](https://github.com/aws/aws-sdk-js-v3) which provides much faster times. 

I believe this is not a bug but a feature request for the SDK which is implemented in the JS-SDK-V3. 

I would like to close this issue now, please let me know if you have any additional questions.

**Closed by ajredniwja** 2020-09-01 12:07 UTC
Labels: bug, needs-triage

**Comment by escar** [comment] 2020-09-01 12:48
Thank you @ajredniwja!
