### ISSUE TITLE
s3.createPresignedPost not working with ec2 role - The AWS Access Key Id you provided does not exist in our records.

### ISSUE THREAD

**Issue by lajpatshah** [aws/aws-sdk-js#3878] opened 2021-09-02 11:11 UTC
I created ec2 role and assigned it to the ec2. 

Using this role I am able to do s3 getobject and other actions without error.

To do POST upload I used s3.createPresignedPost, which generates the url without error using temporary aws key. Now when trying to upload using this url it gives below error.

`<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>ASIAXXXXXXXXXXX</AWSAccessKeyId><RequestId>EADQD0E6FAPZDYWW</RequestId><HostId>xJemQGRc9sfwefwefy6x3No4VlgSRg1/nWCasdfdsfdfYNX9anh/l/QkKS/Pl2sdvsdfsvD4uc=</HostId></Error> `

It seems S3 does not recognize the access key. It does not recognize even after inserting the role as principle in bucket policy.

Can someone help?

**Comment by lajpatshah** [comment] 2021-09-17 06:12
Is nobody else facing this issue?

**Comment by ajredniwja** [comment] 2021-09-21 02:40
@lajpatshah thanks for opening this issue, can you please follow the resolution steps mentioned [here](https://aws.amazon.com/premiumsupport/knowledge-center/access-key-does-not-exist/). 

Also see how to correctly use the temporary keys in this [doc](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html)

Feel free to reach out if you have any other questions.

**Comment by lajpatshah** [comment] 2021-09-21 05:46
@ajredniwja thank you for looking into the issue.

I followed every possible aws doc to solve the issue but have been unsuccessful. As mentioned above I am using EC2 instance role with required permissions to upload files to S3 using POST request.

The credentials are derived automatically by aws sdk and i am not using session token explicitly in my code. Hence using the credentials I am able to to s3 gets without issue. I am using same role for all other services like sqs, sns and they are all working. The issue is coming only for the s3 POST using presigned url created by createPresignedPost() function. 

So i created a new user with only s3 put permission and used this user's credential to create presigned post url. This worked without issue. So the issue is due to the ec2 instance role credentials which are automatically retrieved by aws sdk for this specific function only.

Steps to recreate the issue:
1. Create IAM EC2 role having S3 PUT permission
2. Use aws sdk and create presigned url using createPresignedPost(). instance role credentials are handled by aws sdk itself.
3. Try to upload using this presigned url and error occurs.
4. Create get signed url using getSignedUrl() 
5. Try to view the file using this url and it works.

**Comment by omarioffline** [comment] 2021-10-04 18:21
Error: Module not found: Error: Can't resolve 'util' in '/Users/hinddeeppurohit/Documents/battle-of-brands/node_modules/aws-sdk/lib' Did you mean './util'? Requests that should resolve in the current directory need to start with './'. Requests that start with a name are treated as module requests and resolve within module directories (/Users/hinddeeppurohit/Documents/********, node_modules). If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.
[README.md](https://github.com/aws/aws-sdk-js/files/7280398/README.md)

**Comment by lajpatshah** [comment] 2021-10-05 04:52
@omarioffline sorry but i think your reply is out of context.

**Comment by omarioffline** [comment] 2021-10-05 17:11
const AWS = require("aws-sdk");
const ecr = new AWS.ECRPUBLIC({
  region: process.env.AWS_REGION,
  apiVersion: '2020-10-30
[amazon-ecs-deploy-task-definition-21a2811486a0751fb3448592bee9b05346a837bc (1).zip](https://github.com/aws/aws-sdk-js/files/7287846/amazon-ecs-deploy-task-definition-21a2811486a0751fb3448592bee9b05346a837bc.1.zip)

**Comment by omarioffline** [comment] 2021-10-05 17:20
const AWS = require("aws-sdk");
const ecr = new AWS.ECRPUBLIC({
  region: process.env.AWS_REGION,
  apiVersion: '2020-10-30'
[amazon-ecs-deploy-task-definition-21a2811486a0751fb3448592bee9b05346a837bc (1).zip](https://github.com/aws/aws-sdk-js/files/7287917/amazon-ecs-deploy-task-definition-21a2811486a0751fb3448592bee9b05346a837bc.1.zip)

**Comment by lajpatshah** [comment] 2021-10-06 13:09
????
Seriously not getting what you are saying..
My code reference is of ec2 and you are speaking of ecs

**Comment by ajredniwja** [comment] 2022-04-25 18:03
@lajpatshah Apologies I lost track of this is it still a persisting issue with the latest version?

**Comment by lajpatshah** [comment] 2022-04-26 12:16
Hi @ajredniwja 

Thank you for bringing to my notice again. **Yes its working now.**

Cheers

**Comment by lajpatshah** [comment] 2022-04-27 04:58
Hi @ajredniwja

Thank you for bringing to my notice again. I checked on my production server it is still giving same error. 

It is working when I use security credentials of a aws user. But it doesnt work with ec2role.

**Comment by throttlehead-dev** [comment] 2022-09-08 19:04
I have the same issue in the php sdk. We have environmental options to conditionally give the sdk access keys. When I give the s3 client access keys with the exact same iam policy, it works, so this issue does not seem unique to the js sdk.

**Comment by throttlehead-dev** [comment] 2022-09-08 20:42
I had one other idea and that was to try using temporary credentials from the `StsClient::AssumeRole` response. This resulted in the same error.

This just leads me to more strongly believe that this is a limitation as to what's actually going on here. Instance and container roles are temporary sessions that get refreshed periodically. It's unique to that client. What signed requests are essentially doing is rolling up an identity that a client can use on behalf of. With user access keys, that entity is perminent and can be looked up again at the S3 service level. Since roles are unique, temporary sessions, they cannot, hence "The AWS Access Key Id you provided does not exist in our records".

**Comment by m-mueller678** [comment] 2022-11-19 19:08
Getting the same issue with manually signed post policies. User credentials work, those from AssumeRole don't.

**Comment by diode02** [comment] 2023-05-12 09:52
This is a bug and needs to be resolved. I'm also getting `Unable to create a POST object policy without a bucket, region, and credentials` error on trying to accomplish this using createPresignedPost

**Comment by YaKalmar0** [comment] 2023-05-16 17:08
Encountered the same issue using `createPresignedPost` with IAM Role, but not with user credentials.

**Comment by DarkIsDude** [comment] 2023-07-27 10:43
Exact same issue. Not sure it's related to the AWS SDK code but maybe to more ou how AWS is working on this point ?

An example code to reproduce

- Create a bucket
- Create an EC2 instance
- Create a new role that have full access to the bucket
- Assign the role to the EC2 instance
- Install the aws sdk and node js to the instance
- Run the script

```
const { S3 } = require('aws-sdk');

const s3 = new S3({
  region: 'eu-west-1',
  endpoint: 'https://s3.eu-west-1.amazonaws.com',
  s3ForcePathStyle: false,
});

const options = {
  Bucket: '<bucket name>',
  Fields: {
    key: 'test/test.json',
    acl: 'private',
  },
  Expires: 60,
  Conditions: [],
};

const response = s3.createPresignedPost(options);

console.log(response);
```

You have the error. Now if you update the code with:

- Create a new user with the policy associated to the role to have full acvess to the s3 bucket

```
const s3 = new S3({
  region: 'eu-west-1',
  endpoint: 'https://s3.eu-west-1.amazonaws.com',
  s3ForcePathStyle: false,
  accessKeyId: <access key>,
  secretAccessKey: <secret key>,
});
```

you don't have the error.

**Comment by vandermnt** [comment] 2023-12-06 15:18
@diode02 this bug has been resolved?

**Comment by aBurmeseDev** [comment] 2024-07-31 18:02
Hello! I wanted to follow up on this issue since I noticed there haven't been any recent updates. Before I investigate further, could you please confirm if this is still an ongoing concern or if the problem has been resolved? I'm happy to assist, but I want to ensure I'm addressing an active issue. Please let me know either way, and I appreciate your patience.

**Comment by DarkIsDude** [comment] 2024-07-31 19:28
@aBurmeseDev still active 🙏

**Comment by aBurmeseDev** [comment] 2024-08-27 22:50
Based on reviewing original post and comments, here are my thoughts:

The error `InvalidAccessKeyId` indicates that the AWS Access Key ID being used is not recognized by AWS. This is likely because the `createPresignedPost` method is generating a presigned URL that includes temporary credentials.

When you create a presigned URL using `createPresignedPost`, AWS generates temporary credentials (an access key ID, secret access key, and session token) that are valid for a limited time. These temporary credentials are different from the permanent credentials associated with your IAM user or role.

The temporary credentials are intended for use with the presigned URL and are not recognized by AWS outside of that context. When you try to upload directly to S3 using the temporary access key ID from the presigned URL, AWS will not recognize that access key ID because it's not a permanent credential.

To resolve this issue, you should upload the file using the presigned URL generated by `createPresignedPost`. This presigned URL includes all the necessary information (including the temporary credentials) to authorize the upload to S3.

Here's an example:
```js
const AWS = require('aws-sdk');
const s3 = new AWS.S3();

// Assuming you have the necessary permissions
const presignedPost = await s3.createPresignedPost({
  Bucket: 'your-bucket-name',
  Fields: {
    key: 'path/to/file.ext',
    // Add any other required fields
  },
  Expires: 300, // Presigned URL expiration time in seconds
  Conditions: [
    // Add any additional conditions
  ],
});

// Use the presigned URL in an HTML form or with a library like axios/fetch
const formData = new FormData();
formData.append('key', presignedPost.fields.key);
// Append other fields from presignedPost.fields
formData.append('file', fileToUpload);

const response = await axios.post(presignedPost.url, formData, {
  headers: {
    'Content-Type': 'multipart/form-data',
  },
});
```
By using the presigned URL, the temporary credentials are included in the request, and S3 will recognize and authorize the upload.

Hope that helps,
John

**Comment by lajpatshah** [comment] 2024-08-28 06:06
@aBurmeseDev thank you for looking into the issue.
the solution you mentioned is what we are doing from the beginning. 
the issue is not of the presignedurl per se but of the aws credentials. 
in s3.createPresignedPost() when we hard code the aws credentials then it works.
but it fails to work when it is using ec2 role credentials.
i hope the issue is clear now

**Comment by aBurmeseDev** [comment] 2024-09-03 07:26
Thanks for your response. Can you confirm if this's still an issue? If so, please share how you've figured credentials with EC2. If this isn't an issue anymore, please disregard this.

**Comment by xyanlucasx** [comment] 2024-09-04 15:06
> Thanks for your response. Can you confirm if this's still an issue? If so, please share how you've figured credentials with EC2. If this isn't an issue anymore, please disregard this.

Yes, the problem still occurs.

    "@aws-sdk/client-s3": "^3.637.0",
    "@aws-sdk/s3-presigned-post": "^3.637.0",

**Comment by aBurmeseDev** [comment] 2024-09-05 07:38
Can you share how you've configured credentials with EC2 roles? Anything that might be helpful for us to further investigate.

**Comment by DarkIsDude** [comment] 2024-09-05 09:10
> Can you share how you've configured credentials with EC2 roles? Anything that might be helpful for us to further investigate.

I use Fargate or Beanstalk, so I just configure my AWS service to inject the role. No more on my side.

**Comment by aBurmeseDev** [comment] 2024-09-06 05:44
Thanks for the update @DarkIsDude. 

Since we haven't received any further details on how credentials are configured in order to provide guidance, I'm going to close this now.

**Closed by aBurmeseDev** 2024-09-06 05:44 UTC
Labels: guidance, p3
