### ISSUE TITLE
release 2.1.0 caused a regression with uploadPart

### ISSUE THREAD

**Issue by andrewrk** [aws/aws-sdk-js#459] opened 2015-01-09 15:34 UTC
[node-s3-client](https://github.com/andrewrk/node-s3-client) calls aws sdk `uploadPart` with `Body` set to a `stream.Readable`. In version 2.0.31, this works fine. In 2.1.0 and later, this function never calls the callback.

**Comment by lsegal** [comment] 2015-01-09 20:30
Hey @andrewrk. Can you provide a minimal reproduction case for this? Also Node.js version? I'm not able to reproduce it here on Node.js 0.10.35 (or 0.10.28 for what it's worth):

```js
// test.js
var fs = require('fs');
var AWS = require('aws-sdk');
var s3 = new AWS.S3({params: {Bucket: process.env.BUCKET, Key: process.env.KEY}});
var body = fs.createReadStream('bigfile');

s3.createMultipartUpload(function(err, data) {
  if (err) throw err;
  console.log("Created MP upload", data.UploadId);
  s3.uploadPart({UploadId: data.UploadId, PartNumber: 1, Body: body}, function(err2, data2) {
    if (err2) throw err2;
    console.log("Uploaded a part.");
    s3.abortMultipartUpload({UploadId: data.UploadId}).send();
  });
});
```

Output from run:

```
$ BUCKET=MYBUCKET KEY=bigfile node test
Created MP upload g5k3kBtmRguJmd6tPBJhjtJEtjjUVYYV.9Dx45.SVK...
Uploaded a part.
```

**Comment by andrewrk** [comment] 2015-01-20 19:02
When I run this example code, I do not get to the "Created MP upload" console.log. It hangs forever on s3.createMultipartUpload.

```
$ uname -a
Linux andy-bx 3.16.0-25-generic #33-Ubuntu SMP Tue Nov 4 12:06:54 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
$ node -v
v0.10.29
```

**Comment by lsegal** [comment] 2015-01-20 19:19
Can't seem to reproduce this with 0.10.29 either:

```sh
$ nvm use 0.10.29
Now using node v0.10.29
$ BUCKET=MYBUCKET KEY=bigfile node test
Created MP upload MVLMDgkKJnhSGu1OFO6CzvioJe....
Uploaded a part.
```

Haven't tried this on Ubuntu, though... this is on Mac OS X 10.10. I'll give this a shot on a Ubuntu instance a little later today.

**Comment by andrewrk** [comment] 2015-01-21 16:32
Got the same behavior with node v0.10.35.

**Comment by AdityaManohar** [comment] 2015-03-10 21:08
@andrewrk 
I just ran this sample on an Ubuntu install and I'm still not able to reproduce the error (SDK `v2.1.16`).

```sh
$ BUCKET=aditm KEY=upload node s3_upload.js
Created MP upload mB_dz6EarM4gy63XZaWaD1W0Rk9h3j ...
Uploaded a part.

$ uname -a
Linux ip-255.255.255.255 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

$ node -v
v0.10.35

$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty
```
Is there any other information that you can provide that can help reproduce your issue?

**Comment by lsegal** [comment] 2015-05-04 21:36
Marking this as closed since we could not reproduce on Ubuntu with the latest version of the SDK. Note that we did find similar reports specific to the usage of custom mocks like fake-s3 (via #525). It's possible that if you were running into this with a mock like fake-s3 or similar, that this might be an issue specific to that library. One of the changes in the SDK is that we rely on Expect: 100-continue support for files >= 1MB, and this must be supported by your test endpoint as well, if you are using a mock.

Feel free to re-open if you have other info to help narrow down this issue.

**Closed by lsegal** 2015-05-04 21:36 UTC
Labels: Feedback Requested
