### ISSUE TITLE
ListIdentityProviders has a hidden required param

### ISSUE THREAD

**Issue by TDA** [aws/aws-sdk-js#2536] opened 2019-02-13 19:29 UTC
Filing this in addition to [this](https://github.com/aws/aws-cli/issues/3926).

The JS SDK does not mention that `MaxResults` is a required param, however, when its not passed in, it defaults to 0 and results in a validation error:

```
An error occurred (InvalidParameterException) when calling the ListIdentityProviders operation: 1 validation error detected: Value '0' at 'MaxResults' failed to satisfy constraint: Member must have value greater than or equal to 1
```

So there are two ways to fix this here:
1. We can make the `MaxResults` a required field, so users are forced to pass in the value (non-zero)
2. We can change the default value of MaxResults to 1 from 0, and keep it an optional field.

**Comment by klaytaybai** [comment] 2019-02-14 22:07
Hi @TDA, I'm going to close out this issue as a duplicate of your CLI issue https://github.com/aws/aws-cli/issues/3926 and https://github.com/aws/aws-cli/issues/3866.  When the service is fixed up, the JS SDK should be fine.

**Closed by klaytaybai** 2019-02-14 22:07 UTC
Labels: duplicate
