### ISSUE TITLE
Managed uploader keeps resetting back to lower number and failing to upload

### ISSUE THREAD

**Issue by dukedougal** [aws/aws-sdk-js#932] opened 2016-03-16 03:43 UTC
I am using the managed uploader from a browser.

I have a function that displays the progress.

I am trying to upload a 23.5 meg file.

The upload progress event shows that it transfers a certain amount of data and then keeps on dropping down the count of bytes sent and keeps counting back up again.

```
  doUploadFile = (bucketname, region, filepath, body, callbackUploadProgress, callbackUploadComplete) => {

    // uploads a file to a bucket
    var uri = new URI(filepath);
    let url = uri.toString()
    var params = {
      Bucket: 'staging.aws.example.org',
      Key: url,
      Body: body
    };
    let opts = {queueSize: 4, partSize: 1024 * 1024 * 10};
    var req = this.storageConnection.upload(params, opts);
    req.on('httpUploadProgress', (evt, req) => {callbackUploadProgress(evt, req)})
    this.app.store.dispatch(addKeyValue('request', req))
    req.send(function (err, data) {
      if (err) {
        callbackUploadComplete(err)
      }
        callbackUploadComplete(null, 'saved: ' + filepath)
    })
  }
```

It always fails to upload.

**NOTE the problem disappears when queueSize is set to 1**

**Comment by chrisradek** [comment] 2016-03-16 18:00
@dukedougal 
Can you share what browser (including version) you are using, and which SDK version?

**Comment by chrisradek** [comment] 2016-03-18 17:52
@dukedougal 
I tried reproducing your issue within some browsers but haven't been able to yet.

Here's a test function that will attempt to upload three 23 MB files at once. Because I'm uploading 3 files at once, the `loaded` field on `progress` will sometimes appear to go down, but looking at the `key`, it's obvious that the value increases for each file.

```javascript
function testFileUpload() {
    AWS.config.update({
        credentials: credentials
    });
    
    var s3 = new AWS.S3();
    
    var opts = {
        queueSize: 4,
        partSize: 1024*1024*10
    };
    
    for (var i = 0; i < 3; i++) {
        var params = {
            Bucket: 'BUCKET',
            Key: 'browser-upload-test-' + i + '.dat',
            Body: new Blob([new ArrayBuffer(1024*1024*23)])
        };
        var uploader = s3.upload(params, opts);
    
        uploader.on('httpUploadProgress', function(progress) {
            console.log(progress);
        });
        
        uploader.send(function(err, data) {
            if (err) {
                console.log(err);
            } else {
            console.log(data); 
            }
        });
    }
}
```

Could you try just the above example and see if the results you're seeing are along the same lines as with this example?

When your uploads fail, what error message do you get?

**Comment by dukedougal** [comment] 2016-03-18 19:48
Hi @chrisradek 
Thanks for checking it out.  The browser I am using is Github Electron for Windows.

The version numbers come from typing "process.versions" at the console.

>process.versions
Object {http_parser: "2.6.0", node: "5.1.1", v8: "4.7.80.27", uv: "1.7.5", zlib: "1.2.8"…}ares: "1.10.1-DEV"atom-shell: "0.36.7"chrome: "47.0.2526.110"electron: "0.36.7"http_parser: "2.6.0"modules: "47"node: "5.1.1"openssl: "1.0.2e"uv: "1.7.5"v8: "4.7.80.27"zlib: "1.2.8"__proto__: Object

I'll see if I can find time to try your code above. 

For now I have rewritten this part of my application to sequentially upload everything and it all works fine.

There wasn't any way I could get concurrent uploads to work however so maybe there's something you are doing differently - I'll check it out.

thanks

**Comment by bnussey** [comment] 2016-05-03 01:59
Just to add this I am having a similar issue only when I am trying to upload from Colombia which I can speculate is due to the poorer standard of internet here. From California, have absolutely no problems. Also reported that some users from Sweden have had a similar issue.. 

However can resolve this issue by setting `queueSize: 1`

**Comment by dukedougal** [comment] 2016-05-03 21:32
I've converted all my code to ensure it only ever uploads one file at a time and it works fine.  I gave up trying to get parallel to work.

**Comment by chrisradek** [comment] 2018-07-27 17:16
Closing this issue since it appears to be related to how much bandwidth the client has. Setting queueSize to 1, or the timeout to 0 should resolve this.

**Closed by chrisradek** 2018-07-27 17:16 UTC
Labels: Feedback Requested, Question
