### ISSUE TITLE
Implement ECMAScript native modules, remove circular references

### ISSUE THREAD

**Issue by haraldrudell** [aws/aws-sdk-js#1936] opened 2018-02-16 23:01 UTC
If aws-sdk is bundled using @rollup, this fails at runtime with an undefined variable type error

action: **remove circular references**
This is likely caused by the habit of using ciruclar references which has traditionally been a bad practice with @nodejs

action: **Implementing ECMAScript native modules for tree shaking**
Implementing **ECMAScript native modules**, ie. import and export statements in the source code, would allow tree shaking which is a benefit for a huge library like **aws-sdk**

action: **transpilation**
This would require transpilation for Node.js older than stable **Nodejs v8.5+**
-- or two separate branches

**symptom**
> code: 'CIRCULAR_DEPENDENCY',
>   importer: '../../node_modules/aws-sdk/lib/util.js',
>   'Circular dependency: ../../node_modules/aws-sdk/lib/util.js -> ../../node_modules/aws-sdk/lib/core.js ->
>  ../../node_modules/aws-sdk/lib/util.js'

**get-around**
Define **aws-sdk** as a **RollupJS external reference**. It works when node require loads it.

I am using **aws-sdk** with **es2049package**
https://github.com/haraldrudell/ECMAScript2049/tree/master/workspace/packages/es2049package

**Comment by jeskew** [comment] 2018-02-17 00:52
Closing as a duplicate of #1769 & #1766. There's a fair amount of discussion on those issues, so I'd like to keep the conversation centralized there.

**Closed by jeskew** 2018-02-17 00:52 UTC
Labels: Duplicate
