### ISSUE TITLE
Suggestions for a proxy agent that supports no_proxy?

### ISSUE THREAD

**Issue by e-gineer** [aws/aws-sdk-js#1842] opened 2017-12-20 22:44 UTC
Using the SDK behind a proxy is possible with a proxy agent like proxy-agent - https://aws.amazon.com/blogs/developer/using-the-aws-sdk-for-javascript-from-behind-a-proxy/

Unfortunately, proxy-agent does not support NO_PROXY settings or configuration. Unfortunately this means we cannot setup our proxy to be used for some services (e.g. IAM, etc) while other services (e.g. S3) use VPC Private Endpoints.

Does anyone have a suggestion for a proxy-agent alternative that supports NO_PROXY?

Thanks!

**Comment by AllanFly120** [comment] 2017-12-20 23:31
The blog gives us a good example of configuring the whole SDK level. Actually, this setting can also be done at the individual client level, so that you can selectively use the proxy-agent. For example:
```javascript
var AWS = require('aws-sdk');
var proxy = require('proxy-agent');

var s3 = new AWS.S3({
        region: 'us-west-2',
        httpOptions: {agent: 'http://user:password@internal.proxy.com'}
});
s3.getObject({Bucket: 'bucket', Key: 'key'}, function (err, data) {
  console.log(err, data);
});
```
Does this solve your concern?

**Comment by e-gineer** [comment] 2017-12-21 13:09
Thanks - I agree that the ability to set a proxy for each individual connection is helpful.

Unfortunately, our software uses 50+ AWS services in a range of enterprise scenarios, each of which may have a highly specific proxy configuration. Unfortunately the per-service approach would require us to add custom parsing of the proxy settings to cover all those cases. Not impossible, just hoping there is a better way!

We use the aws cli which supports no_proxy. We use the node request module which supports no_proxy settings.

Before we embark on a custom approach, I'd really appreciate it if anyone can suggest an alternative to `proxy-agent` - or even just confirm they are not aware of an alternative. Unfortunately, our searching has come up empty... Thanks!

**Comment by srchase** [comment] 2018-08-28 00:03
Hi @e-gineer,

As there is not an issue with the SDK here, I'm electing to close this thread.  If anyone has suggestions for alternatives, they'll still be able to post it here.

**Closed by srchase** 2018-08-28 00:03 UTC
Labels: Question

**Comment by mithun-daa** [comment] 2019-06-03 14:47
I am in the exact same boat as @e-gineer . Did you ever get this resolved? Does it work if you use API keys and not work only when the instance is using IAM roles?

**Comment by trivikr** [comment] 2019-06-05 21:20
Locking this thread as the issue is old, and resolved.
Please open a [new issue](https://github.com/aws/aws-sdk-js/issues/new/choose) for related bugs and link to relevant comments in this thread.
