### ISSUE TITLE
unable to Upload file  to s3 from local meteor app 

### ISSUE THREAD

**Issue by vyas07** [aws/aws-sdk-js#1359] opened 2017-02-13 06:16 UTC
unable to Upload to s3 from local meteor app 

**error**
TypeError: stream.setTimeout is not a function
    at features.constructor.handleRequest (node.js:52)
    at executeSend (event_listeners.js:261)
    at Request.SEND (event_listeners.js:276)
    at Request.callListeners (sequential_executor.js:101)
    at Request.emit (sequential_executor.js:77)
    at Request.emit (request.js:668)
    at Request.transition (request.js:22)
    at AcceptorStateMachine.runTo (state_machine.js:14)
    at state_machine.js:26
    at Request.<anonymous> (request.js:38)

**my code:**

s3.upload ({
                    Bucket: 'upload',
                    Key: scope.filename,
                    Body: 'file',
                    ACL: 'public-read'
                }, function(error, data) {
                    if (error) {
                    console.log(error)
                }else {
                    console.log(data)
                    alert('Successfully uploaded photo.');
                    }
               });

any idea?

thanks in advance

**Comment by jeskew** [comment] 2017-02-13 18:03
@vyas07 Is this code running in node.js or the browser? I see that the node-specific HTTP handler is being used, so the `stream` variable on line 52 is an instance of [http.ClientRequest](https://nodejs.org/api/http.html#http_class_http_clientrequest), which has a [`setTimeout` method](https://nodejs.org/api/http.html#http_request_settimeout_timeout_callback).

**Comment by jeskew** [comment] 2017-02-16 05:11
Closing as a duplicate of #1348

**Closed by jeskew** 2017-02-16 05:11 UTC
Labels: Duplicate
