### ISSUE TITLE
InvalidExpiryTime when signing S3 requests

### ISSUE THREAD

**Issue by kristjanmik** [aws/aws-sdk-js#698] opened 2015-08-31 13:32 UTC
When running node in the environment NODE_ENV=testing the S3 pre-signing is giving different response than without the env variable set. When I'm running the tests it throws InvalidExpiryTime when the time is more than a week since [`````javascript request.service.getSignerClass() === AWS.Signers.V4`````](https://github.com/aws/aws-sdk-js/blob/master/lib/signers/presign.js#L18) is returning true in that case. 

Running without test mode goes into the S3 signing and therefore allows expire > week like I expected.
![screen shot 2015-08-31 at 13 26 18](https://cloud.githubusercontent.com/assets/911107/9579758/783f7274-4fe4-11e5-8f06-816bef25f4de.png)

Running in the test mode gives different(wrong?) results. 
![screen shot 2015-08-31 at 13 26 30](https://cloud.githubusercontent.com/assets/911107/9579759/7840739a-4fe4-11e5-9e9f-d658aa2a954e.png)

**Comment by AdityaManohar** [comment] 2015-09-08 18:22
@kristjanmik Do you have any sample code that you can share that can reproduce the problem?

**Comment by AdityaManohar** [comment] 2015-09-19 00:57
@kristjanmik I'm marking this as closed because there hasn't been any recent activity on this thread. Feel free to reopen this issue or open another issue if you have any information that can help reproduce the issue.

**Closed by AdityaManohar** 2015-09-19 00:57 UTC
