### ISSUE TITLE
CloudSearch field values returns as arrays

### ISSUE THREAD

**Issue by enagorny** [aws/aws-sdk-js#791] opened 2015-11-12 14:03 UTC
When performing request using TestSearch UI in admin all works correctly.
And correct json returned:
```
[
  {
    "id": "011edf4e0ccd43679420d22e58f1bffcca2791ec",
    "fields": {
      "name": "test name",
      "locale": "en-gb",
      "colors": [
        "red",
        "green"
      ],
      "theme": [
        "collage",
        "photo"
      ]
    }
  }
]
```

But when I perform the same query using SDK all field values returned as arrays:
```
[
  {
    "id": "011edf4e0ccd43679420d22e58f1bffcca2791ec",
    "fields": {
      "name": [
        "test name"
      ],
      "locale": [
        "en-gb"
      ],
      "colors": [
        "red",
        "green"
      ],
      "theme": [
        "collage",
        "photo"
      ]
    }
  }
]
```

Am I doing something wrong or it's known behaviour?

versions:
node/0.10.40
aws-sdk@2.2.16
OS X 10.10

**Comment by MaxiSantos** [comment] 2015-11-12 16:42
Do you want values not to be returned as an array? Try removing the the format=sdk.

**Comment by enagorny** [comment] 2015-11-16 19:44
Hmm. `format=sdk` is hardcoded in api jsons https://github.com/aws/aws-sdk-js/blob/master/apis/cloudsearchdomain-2013-01-01.normal.json#L18
Why not make it configurable?
Is there a way to override this url?

**Comment by chrisradek** [comment] 2015-11-19 00:32
@enagorny 
Unfortunately, removing `format=sdk` can cause some adverse effects in the results you get back. In my testing, some results that came back with an array of one string when format is set to sdk, would instead return an array where each character in the string had its own element if I removed `format=sdk` or changed it to `format=json`.

The CloudSearch service team ultimately controls how the `format=sdk` affects the data that comes back in the response, but my assumption would be that everything comes back as an array so the user doesn't have to worry about checking the type of each returned field under certain conditions.  For example, if they had a field named `authors`, and in some cases `authors` contained 1 string and others it contained a list of 2 strings, the user would have to do an additional check to determine if a string or array was used. 

Let me know if that clarifies things. At this point I would suggest that the operation is working as intended in the SDK, which is different than in the console.

**Comment by enagorny** [comment] 2015-11-19 10:32
> some results that came back with an array of one string when format is set to sdk, would instead return an array where each character in the string had its own element 
Hmm expect json format strictly define such things.

**Comment by chrisradek** [comment] 2015-11-19 17:24
I'm going to close this issue since the SDK is accepting the data as the service provides it, and changing `format` to anything other than `sdk` currently exacerbates the behavior you're seeing.

If you want to discuss this further feel free to comment here.

**Closed by chrisradek** 2015-11-19 17:24 UTC
Labels: Question

**Comment by ttangww** [comment] 2018-01-05 03:22
Is it the problem resolved ?
Looks like it is still there.

**Comment by tbo** [comment] 2018-02-13 00:18
@chrisradek I was unable to reproduce your test results. If I request the cloudsearch endpoint directly via a REST-request, then I get a proper JSON output as specified in its index options (No "single character"-arrays!): 
```
$ curl "https://endpoint/2013-01-01/search?q=foo&cursor=initial&size=10&format=json"
```
Also a test search in the web dashboard yields the same result. I think it is much more likely, that the issue lies in the SDK. Iterating over a string without checking, that it isn't an array would explain your test result.

**Comment by vlamic** [comment] 2018-10-01 10:05
CloudSearch knows all the types of the fields - whether it's a text or text-array. I don't understand why they cannot return the data with a proper format. Now, every SDK user has to write data parsers to preserve the correct data types. This is ridiculous.
