### ISSUE TITLE
Paginated call hits rate limit of API, also with "adaptive" retry set.

### ISSUE THREAD

**Issue by aldegoeij** [aws/aws-sdk-js#3873] opened 2021-09-01 15:16 UTC
- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
Paginated API call hits the rate limit, even with "adaptive" retry mode set.

Retry mode does seem to back-off exponentially over 3 attempts, however, the `totalRetryDelay` is still too short not to trigger another `429`.

**Is the issue in the browser/Node.js?**
Node.js

**If on Node.js, are you running this on AWS Lambda?**
No

**Details of the browser/Node.js version**
node v14 lts

**SDK version number**
3

**To Reproduce (observed behavior)**

On an account with a lot of findings (1000+) the paginated api hits the 3 calls per minute API rate limit, even with retry policy set to adaptive.

```typescript
const client = new SecurityHubClient({
  region: "eu-west-1",
  retryMode: "adaptive",
});
const findings = [];
for await (const page of paginateGetFindings({ client }, {})) {
  // page contains a single paginated output.
  findings.push(...page.Findings);
}
```

**Expected behavior**
Some way to set a specific retry millisecond amount, or the paginated call should know this for the specific API.

Apparently there is a `DefaultRateLimiter` in the retry middleware: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/classes/_aws_sdk_middleware_retry.defaultratelimiter-1.html but no idea how and where this should be used?

**Screenshots**

```bash
TooManyRequestsException: Too Many Requests
    at deserializeAws_restJson1GetFindingsCommandError (/Users/alexander/Projects/projectX/node_modules/@aws-sdk/client-securityhub/dist/cjs/protocols/Aws_restJson1.js:3690:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/alexander/Projects/projectX/node_modules/@aws-sdk/middleware-serde/dist/cjs/deserializerMiddleware.js:6:20
    at async /Users/alexander/Projects/projectX/node_modules/@aws-sdk/middleware-signing/dist/cjs/middleware.js:11:20
    at async AdaptiveRetryStrategy.retry (/Users/alexander/Projects/projectX/node_modules/@aws-sdk/middleware-retry/dist/cjs/StandardRetryStrategy.js:51:46)
    at async /Users/alexander/Projects/projectX/node_modules/@aws-sdk/middleware-logger/dist/cjs/loggerMiddleware.js:6:22
    at async makePagedClientRequest (/Users/alexander/Projects/projectX/node_modules/@aws-sdk/client-securityhub/dist/cjs/pagination/GetFindingsPaginator.js:12:12)
    at async paginateGetFindings (/Users/alexander/Projects/projectX/node_modules/@aws-sdk/client-securityhub/dist/cjs/pagination/GetFindingsPaginator.js:33:20)
    at async getAWSSecurityHubFindings (webpack-internal:///./pages/api/findings/index.ts:67:22)
    at async handler (webpack-internal:///./pages/api/findings/index.ts:109:21) 
```

```typescript
{
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 429,
    requestId: '4eeafa49-1889-4206-9254-d9e43ce7230c',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 3,
    totalRetryDelay: 1568
  }
}
```

**Additional context**

**Comment by aldegoeij** [comment] 2021-09-02 09:44
Found rate limit changing referenced here: https://github.com/aws/aws-sdk-js-v3/pull/2463

**Comment by aldegoeij** [comment] 2021-09-02 09:47
Another similar issue (though unresolved) here: https://github.com/aws/aws-sdk-js-v3/issues/1899

**Comment by trivikr** [comment] 2021-09-28 17:31
Closing as the issue is in v3 being discussed at https://github.com/aws/aws-sdk-js-v3/issues/2741

**Closed by trivikr** 2021-09-28 17:31 UTC
Labels: bug, needs-triage
