### ISSUE TITLE
Request Timeout: Your socket connection to the server was not read from or written to with in the time out period.

### ISSUE THREAD

**Issue by Himanshu-Tamrakar** [aws/aws-sdk-js#1235] opened 2016-11-20 08:33 UTC
I am facing the issue while uploading image file to amazon s3.
Here is my code

Note: file parameter is base 64 incoded string through input tag.
```javascript
'uploadToS3': function(file) {
    var s3 = new AWS.S3({
        httpOptions: {
            timeout: 240000
        },
        apiVersion: '2006-03-01',
        accessKeyId: "MYKEY",
        secretAccessKey: "MYSECRETE KEY",
        endpoint: 'MY END POINT',
        signatureVersion: 'v4'
            //region: 'us-east-1'
    });
    var params = {
        Bucket: 'MY BUCKEY NAME',
            /* required */
        Key: 'FILE NAME',
        /* required */
        ACL: 'public-read',
        Body: file,
        ContentEncoding: 'base64',
        ContentType: 'image/*',
        ContentLength: 100 * 1024 * 1024,
    };
    s3.putObject(params, function(err, data) {
        if (err) console.log(err, err.stack); // an error occurred
        else console.log(data); // successful response
    });
}
```
Here log image:
https://cloud.githubusercontent.com/assets/20944242/20461629/a9174296-af29-11e6-871d-4cd0d143385c.png

**Comment by chrisradek** [comment] 2016-11-28 20:59
@Himanshu-Tamrakar 
In the object you instantiate the `S3` client with, can you remove `endpoint` and set `region` to the same region as the one your bucket is in? It looks like you are connecting, since you get a `requestId` back in the error. Can you also try using `s3.upload` instead of `s3.putObject`? You shouldn't need to specify the `ContentLength` either. The only time the SDK can't determine that is if you're uploading a non-file stream.

**Comment by jeskew** [comment] 2017-02-10 00:22
Closing as a duplicate of #281.

**Closed by jeskew** 2017-02-10 00:22 UTC
Labels: Duplicate, Question
