### ISSUE TITLE
how to create a new Bucket from local ??

### ISSUE THREAD

**Issue by vyas07** [aws/aws-sdk-js#1348] opened 2017-02-07 12:50 UTC
Iam trying to create a new bucket from my local meteor app ?

i have used s3.createBucket method.

getting this error in console when iam creating

TypeError: stream.setTimeout is not a function.

thanks a lot in advance

**Comment by chrisradek** [comment] 2017-02-07 16:29
@vyas07 
Can you share how you've configured your S3 client (specifically looking for region and if you've set an endpoint) and what parameters you passed into `s3.createBucket`?

Also, can you share your SDK version, and what environment it is running in?

**Comment by vyas07** [comment] 2017-02-08 09:49
var params = {
  Bucket: 'mybucket',
  ACL: 'public-read-write',
  CreateBucketConfiguration: {
    LocationConstraint: 'us-east-1'
  },
};
s3.createBucket(params, function(error, data) {
  if (error) {
     console.log(erorr); 
    }
  else  {   
    console.log(data);    
     }      
});

**Comment by chrisradek** [comment] 2017-02-08 16:57
@vyas07 
Is your meteor app running in a web browser? S3 doesn't currently support CORS for operations like `createBucket`, so that could be part of the problem.

Can you share how you've configured the S3 client? I.E., what options did you pass when instantiating: `new AWS.S3(/*options*/);`

On a related note, `us-east-1` isn't a valid `LocationConstraint`: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#createBucket-property
If a `LocationConstraint` isn't specified, the default is 'US Standard' which is the same as us-east-1.

**Comment by vedavyas772** [comment] 2017-02-08 17:03
Iam passing keys and location  I.e.  newAWS.S3 (access key ,secret key region )

**Comment by vyas07** [comment] 2017-02-20 12:37
hello  @chrisradek  ..

is there anything wrong in this code ?

const params = { Bucket : 'bucketname', Key: 'live.jpg', Body: "This is a test object"};

s3.putObject(params, function(error,data)  {
  if (error) {
    console.log('s3 error: ', error);
  } else {
  console.log('it worked: ', data);
  }
             })

y iam getting s3 error:  TypeError: stream.setTimeout is not a function.

please look into it .

thanks in advance

**Comment by jeskew** [comment] 2017-02-22 23:57
@vyas07 `stream.setTimeout` is part of Node's HTTP module and would only be available when running in a Node environment. Do you see this error in Node or in a browser environment?

**Comment by vyas07** [comment] 2017-02-23 05:54
browser environment @jeskew 
can you please explain the basic setup needed for using AWS-SDK API'S. i was stuck here .

my setup: 

import AWS from 'aws-sdk';

      const s3 = new AWS.S3({accessKeyId:'***************',secretAccessKey:'**************',region:'eu-west-1'});

scope.get = function (){
var params = {
  Bucket: mybucket',
  Key: 'live.jpg '  (how to give key name ? only file name or with the path to folder in bucket?)
}

s3.getObject(params, function(err, data) {
  if (err) console.log(err, err.stack); 
  else     console.log(data);           
});
}

**my error:**

s3 error: TypeError: stream.setTimeout is not a function.

thanks a lot in advance

**Comment by jeskew** [comment] 2017-02-23 06:58
Could you try using the browser version of the SDK? You can include it in a webpage with a script tag pointed at our hosted copy (`<script src="https://sdk.amazonaws.com/js/aws-sdk-2.16.0.min.js"></script>`) or download a copy [here](https://sdk.amazonaws.com/builder/js/).

**Comment by vyas07** [comment] 2017-02-23 09:52
the only aws API working in my meteor app is

 scope.getObj = function(){

              var params = {
                Bucket: bucketname, 
                Key: scope.name,
              }
           var url =  s3.getSignedUrl('getObject', params,function(error,url){
               if(error){
                   console.log(error)
              } else{
                    console.log(url)
                }
           });

 i dont know y iam getting stream.settimeout error for all other API'S . :(

**Comment by vyas07** [comment] 2017-02-23 12:02
now its working via CDN 

thankyou so much @jeskew 

but i want to know the reason for the stream.setTimeout error

**Comment by chrisradek** [comment] 2017-02-23 17:59
@vyas07 
Do you have versioning turned on for your bucket?
http://docs.aws.amazon.com/AmazonS3/latest/dev/manage-versioning-examples.html

The `VersionId` will only be returned if versioning is enabled.

**Comment by vedavyas772** [comment] 2017-02-23 18:10
Hey @chris I have enabled versioning in s3 console ....the issue is when I use s3.putobject API.... in data callback. .not only versiomversion id but it is not showing any other except Etag in console.

**Comment by chrisradek** [comment] 2017-02-23 18:23
This sounds like it may be an S3 issue then. I can confirm that the `VersionId` is returned on `data` in the callback when versioning is enabled in my tests.

Please feel free to reach out to S3 on the forums:
https://forums.aws.amazon.com/forum.jspa?forumID=24

Closing since there isn't anything actionable from the SDK here.

**Closed by chrisradek** 2017-02-23 18:23 UTC
Labels: Feedback Requested, Question

**Comment by vedavyas772** [comment] 2017-02-23 18:26
Ok thankyou @Chris 

Can you please test it once... I want to know whether  your also  getting the same issue or not

**Comment by chrisradek** [comment] 2017-02-23 18:28
@vedavyas772 
Yes, I am getting the `VersionId` returned when versioning is enabled for my bucket. I am not seeing the same issue as you are.

**Comment by vedavyas772** [comment] 2017-02-23 18:32
Is there anything we need to pass in params  apart from bucket and key in putObject API to get  version I'd?

**Comment by chrisradek** [comment] 2017-02-23 18:34
No, in my test all I passed was the `Bucket`, `Key`, and `Body`.

**Comment by vedavyas772** [comment] 2017-02-23 18:39
Ok thankyou :) I liked your package 
 do we need to do anything in s3 console  apart from enabling versioning  for bucket? ?

**Comment by vyas07** [comment] 2017-02-24 06:11
hey @chrisradek 

**here is my code** 

 var params = {
          Bucket: "test", 
          Key : 'test/example.docx',
          Body:"hello",
          ServerSideEncryption: 'AES256'
        };

          s3.putObject(params, function(err, data) {
             if(err){
                   console.log(err)
              } else{
                    console.log(data,"the data is")
        });

**my browser console:**
 Object {ETag: ""5d41402abc4b2a76b9719d911017c572""}

 I was getting only the Etag in response

i have used s3.getBucketVersioning API to check if versioning is enabled for bucket . i got **status :** **enabled** object in response.

is there anything iam missing ??

**Comment by jeskew** [comment] 2017-02-24 06:48
@vyas07 It's possible that the bucket you're accessing does not have the correct [CORS](http://docs.aws.amazon.com/AmazonS3/latest/dev/ManageCorsUsing.html "Cross Origin Resource Sharing") configuration. The object's version ID is returned as a header, so it must be explicitly exposed in the bucket CORS policy in order to be visible in a browser. Please take a look at [the section on CORS](http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html) in the S3 developer guide.

Just FYI: [StackOverflow](http://stackoverflow.com/) is a better venue for usage questions, as you can get quick answers from a large community of developers. If you have a question you would like to get in front of S3 engineers, [the S3 developer forum](https://forums.aws.amazon.com/forum.jspa?forumID=24) is the best way to do so. As [mentioned in the readme](https://github.com/aws/aws-sdk-js#getting-help), we like to reserve the GitHub issues on this repository for bug reports and feature requests.

**Comment by vyas07** [comment] 2017-02-24 06:59
solved !!! 
thanks a ton @jeskew  and @chrisradek .
i need to allow it in cors config . :)
