### ISSUE TITLE
AWS.Iot service API does not have CORS

### ISSUE THREAD

**Issue by jadbox** [aws/aws-sdk-js#2258] opened 2018-09-14 21:59 UTC
For browser use of the IOT commands in aws-sdk, any operation fails due to no CORS headers on the IOT service endpoints.

```
Access to XMLHttpRequest at 'https://iot.us-east-1.amazonaws.com/target-policies/amplify-iot-policy' from origin 'https://mydomain.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Usage in reference to:
https://github.com/aws-amplify/amplify-js/issues/684#issuecomment-421487638

**Comment by srchase** [comment] 2018-09-18 18:45
@jadbox 

Which specific commands are you calling that return this error?  Which version of the SDK are you using?

**Comment by jadbox** [comment] 2018-09-20 23:59
SDK version was 2.316 I think. The commands I was using are listed here (with the permissions set the same as also prescribed in the gist):
https://gist.github.com/pveller/fc7660bdfaf19eed4b29b2e9415c3917

**Comment by srchase** [comment] 2018-09-25 00:19
Thanks for following up.  We've reached out to the IoT Service team to understand why this CORS error is being returned.

**Comment by xlamz** [comment] 2018-10-25 02:32
Hello, I can see `Access-Control-Allow-Origin` is present on the server side
```
% http OPTIONS https://iot.us-east-1.amazonaws.com/target-policies/amplify-iot-policy
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Authorization, X-Amz-Date, X-Amz-Security-Token, x-amzn-iot-principal, X-Amz-Content-Sha256, X-Amz-User-Agent, Content-Type
Access-Control-Allow-Methods: OPTIONS, GET, HEAD, POST, PUT, PATCH, DELETE
Access-Control-Allow-Origin: *
....
```
Maybe something missing on the origin side?
You may find this helpful: https://aws.amazon.com/premiumsupport/knowledge-center/no-access-control-allow-origin-error/ for further debugging

**Comment by srchase** [comment] 2018-11-01 15:39
@jadbox 

Can you confirm credentials are being set properly?  

There was a recent related issue being caused by a missing sessionToken: https://github.com/aws/aws-sdk-js/issues/2329

**Comment by jadbox** [comment] 2018-11-01 20:18
@srchase I'm not able to test this anymore as I've had to opt for an alternative solution, but may be able to circle back to this in a few weeks. You're free to close this if you feel strongly that #2329 should fix the issue. As I mentioned on that ticket, I would highly recommend making the CORS header work without OPTION negotiation as it makes debugging non-transparent, and it's rather unorthodox to how CORs typically works in my experience (decoupled from authorization).

**Comment by srchase** [comment] 2018-11-02 18:45
@jadbox 

I'm going to close this issue for now.  If you have time to re-engage, let us know and we'll be happy to re-open.  We appreciate your feedback regarding the difficulty in debugging and will evaluate the best way we can improve that experience in the SDK.

**Closed by srchase** 2018-11-02 18:45 UTC
Labels: guidance, service-api
