### ISSUE TITLE
Not able to send email from NodeJS Lambda to SES from within a VPC

### ISSUE THREAD

**Issue by ricardoribas** [aws/aws-sdk-js#3441] opened 2020-09-09 10:18 UTC
**Describe the bug**
I am using a lambda function with a VPC which is using two endpoints: (1) one for dynamoDB (which works perfectly) and **(2) one for SES**. This latter is always giving timeout errors. In order to dismiss any potential errors regarding the network access, for development purposes, my security group is allowing all kind of traffic. The error seems to persist. If i don't use a VPC, the **nodeJS** sdk works perfectly. As i need to use an EFS to work with large files, i need to add this VPC layer. 

I followed the docs [here](https://aws.amazon.com/blogs/aws/new-amazon-simple-email-service-ses-for-vpc-endpoints/). Another thing i've noticed is that whenever i create a VPC with a VPC::RouteTable, when i go to the VPC configurations on the aws console, the same VPC seems to have a different RouteTable. Seems that the VPC is creating one from scratch. 

Additionally, i've checked also issues on the github about this topic. I've found [this](https://github.com/aws/aws-sdk-js/issues/1451), but i am not sure if this problem was solved or not.

For the sake of simplicity, on the comment below, i've removed parts of the yaml file that were not needed to report this issue.

**To Reproduce (observed behavior)**
1 - Add a VPC to the lambda function
2 - Add two subnets
3 - Create VPC endpoint for **email-smtp** service.
4 - Deploy the lambda
5 - Test the lambda with a default event

**Comment by ricardoribas** [comment] 2020-09-09 10:19
```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-function

  Sample SAM Template for lambda-function

Globals:
  Function:
    Timeout: 120
    AutoPublishAlias: live

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    DependsOn:
      - MountTargetOne
      - MountTargetTwo
      - MountTargetThree
    Properties:
      Policies:
        [
          ...List of all permissions
        ]
      CodeUri: src/
      MemorySize: 2048
      Layers:
        - !Ref DependenciesLayer
      Handler: dist/app.lambdaHandler
      Runtime: nodejs12.x
      FileSystemConfigs:
        - Arn: !GetAtt AccessPointResource.Arn
          LocalMountPath: !Ref MountPath
      VpcConfig:
        SecurityGroupIds:
          - !Ref MySecurityGroup
        SubnetIds:
          - !Ref SubnetOne
          - !Ref SubnetTwo
          - !Ref SubnetThree
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment

  ...Other resources

  MyEFS:
    Type: AWS::EFS::FileSystem
    Properties:
      BackupPolicy:
        Status: DISABLED

  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName

  SubnetOne:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.3.0/24
      MapPublicIpOnLaunch: false
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs:
              Ref: AWS::Region
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref "AWS::StackName", "subnet-a"]]

  SubnetTwo:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.4.0/24
      MapPublicIpOnLaunch: false
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs:
              Ref: AWS::Region
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref "AWS::StackName", "subnet-b"]]

  SubnetThree:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.5.0/24
      MapPublicIpOnLaunch: false
      AvailabilityZone:
        Fn::Select:
          - 2
          - Fn::GetAZs:
              Ref: AWS::Region
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref "AWS::StackName", "subnet-c"]]

  MyVPCRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName

  VPCSubnetOneRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetOne
      RouteTableId: !Ref MyVPCRouteTable

  VPCSubnetTwoRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetTwo
      RouteTableId: !Ref MyVPCRouteTable

  VPCSubnetThreeRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetThree
      RouteTableId: !Ref MyVPCRouteTable

  VPCEndpointDynamoDB:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - "dynamodb:*"
            Resource:
              - "*"
      RouteTableIds:
        - !Ref MyVPCRouteTable
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.dynamodb"
      VpcId: !Ref MyVPC

  VPCEndpointSES:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SecurityGroupIds:
        - !Ref EFSSecurityGroup
      SubnetIds:
        - !Ref SubnetOne
        - !Ref SubnetTwo
        - !Ref SubnetThree
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.email-smtp"
      VpcId: !Ref MyVPC

  EFSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: ExportResourceVPC
      GroupDescription: "Mount target security group"
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: "0.0.0.0/0"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 2049
          ToPort: 2049
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 25
          ToPort: 25
          CidrIp: "0.0.0.0/0"
        - IpProtocol: tcp
          FromPort: 465
          ToPort: 465
          CidrIp: "0.0.0.0/0"

  MountTargetOne:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref MyEFS
      SecurityGroups:
        - !Ref EFSSecurityGroup
      SubnetId: !Ref SubnetOne

  MountTargetTwo:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref MyEFS
      SecurityGroups:
        - !Ref EFSSecurityGroup
      SubnetId: !Ref SubnetTwo

  MountTargetThree:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref MyEFS
      SecurityGroups:
        - !Ref EFSSecurityGroup
      SubnetId: !Ref SubnetThree

  AccessPointResource:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: !Ref MyEFS
      PosixUser:
        Uid: 1000
        Gid: 1000
      RootDirectory:
        CreationInfo:
          OwnerUid: 1000
          OwnerGid: 1000
          Permissions: 777
        Path: "/efs"

  DependenciesLayer:
    ...Properties

Parameters:
  Environment:
    Type: String

Outputs:
  ...
```

**Comment by philipwigg** [comment] 2020-09-09 12:55
I'm not sure this issue relates to the aws-sdk but I have a couple of suggestions.

1. Is this right VPC for this security group? The rest have ```VpcId: !Ref MyVPC```.

``` 
EFSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: ExportResourceVPC
```
2. Why not create a dedicated SG for the SES VPC Endpoint so it's not shared with the EFS mount?

3. Does connectivity to the SES VPC Endpoint work if you try from inside the VPC without AWS Lambda? Test this by creating an EC2 instance in the VPC and testing connectivity manually using `openssl` as described [here](https://aws.amazon.com/blogs/aws/new-amazon-simple-email-service-ses-for-vpc-endpoints/).

**Comment by ricardoribas** [comment] 2020-09-09 13:18
@philipwigg There are two ways of adding references. I made it consistent already in my current configuration. A dedicated SG is actually a very nice idea. Props for that! However, as i am using it in a context of a lambda, how i am going to retrieve that private IP as they state on the docs? I tried the approach that they are referring to and it works just fine.

**Comment by philipwigg** [comment] 2020-09-09 13:38
Actually the issue [could be that](https://stackoverflow.com/questions/63276192/why-does-my-lambda-function-timeout-connecting-to-ses-vpc-endpoint) VPC SES VPC Endpoints are SMTP endpoints and not AWS SES API endpoints.

**Comment by ricardoribas** [comment] 2020-09-09 13:41
@philipwigg thanks a lot for your availability. I will take a look at it. 👍

**Comment by ricardoribas** [comment] 2020-09-09 14:03
Everything seems to work outside the scope of a lambda function. With an EC2 instance everything seems to work just fine. A connection to the private DNS name seems to be reachable.

**Comment by philipwigg** [comment] 2020-09-09 14:40
Sure, did you understand my point above about the SES VPC Endpoint being an SMTP endpoint?

The aws-sdk is expecting the normal AWS SES API over the HTTP protocol. But the SES VPC Endpoint is essentially an SMTP server.

So instead of the aws-sdk to send the email, you'd instead using something like [Nodemailer](https://nodemailer.com/about/) to send the email using SMTP.

**Comment by ricardoribas** [comment] 2020-09-09 15:16
I've checked that approach. However, this solution seems to be a bit expensive. I am trying right now a NAT gateway to allow the requests to be done over the internet. 🙏  It has some pricing attached, but on the long term seems a better solution. I will popup some comments here if that works.

**Comment by ricardoribas** [comment] 2020-09-10 09:55
@philipwigg i tried the new approach with a email-smtp endpoint and a internet gateway. I created this one with a route table which contains a public route. This route is attached to the internet gateway. It seems to work. However, as stated in the docs, that should be avoid by just using a VPC and connect with aws resources on a private network? To be honest, i am not sure if this is supposed to be like that or is a bug. In any of the cases, thanks for all the help.

**Comment by ajredniwja** [comment] 2020-09-17 20:05
@ricardoribas I hope this is not an issue anymore, I would say this is not a bug with the SDK itself but depends on how you are using it and implementing it in your application. 
I would like to close the issue, please reach out if you have additional questions.

**Closed by ajredniwja** 2020-09-17 20:05 UTC
Labels: guidance

**Comment by nguyenthetoan** [comment] 2020-11-04 11:23
I also faced this issue today and found a solution for me. I followed instruction [here](https://aws.amazon.com/blogs/aws/new-amazon-simple-email-service-ses-for-vpc-endpoints/) to create an Endpoint in your VPC and then implementation:

```javascript
const endpoint = new Endpoint(process.env.AWS_SES_ENDPOINT) // your Private DNS name in your created Endpoint above;
const ses = new SES({ region: process.env.AWS_BUCKET_REGION, endpoint });
```

then you can execute `ses.sendEmail` normally

**Comment by IRCraziestTaxi** [comment] 2021-08-09 00:47
I had high hopes for @nguyenthetoan's solution above, but despite the address in the error message changing to one within my VPC and the URL changing to the private DNS given by the VPC Endpoint, so I know it is trying to hit the right one, I'm still getting a timeout... I've been spinning my wheels on this issue for days. :(
