### ISSUE TITLE
'JavaScript heap out of memory' when adding a dependency on the SDK to a small react-native app

### ISSUE THREAD

**Issue by non-standard** [aws/aws-sdk-js#1877] opened 2018-01-12 20:32 UTC
Adding a dependency on the aws-sdk-js to a small react-native app causes react-native bundler to crash with 'JavaScript heap out of memory':

Added this line (per the README.MD) to my app.js (no other code changed):

`var AWS = require('aws-sdk/dist/aws-sdk-react-native');`

Results in the following when launching my app:
 ┌────────────────────────────────────────────────────────────────────────────┐
 │  Running Metro Bundler on port 8081.                                       │
 │                                                                            │
 │  Keep Metro Bundler running while developing on any JS projects. Feel      │
 │  free to close this tab and run your own Metro Bundler  instance if you    │
 │  prefer.                                                                   │
 │                                                                            │
 │  https://github.com/facebook/react-native                                  │
 │                                                                            │
 └────────────────────────────────────────────────────────────────────────────┘
Looking for JS files in
   D:\Proj

Metro Bundler ready.

Loading dependency graph, done.
transform[stderr]: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
transform[stderr]: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
transform[stderr]: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
Bundling `index.js`  [development, non-minified]  99.6% (556/557), failed.
error: bundling failed: Error: Uncaught error in the transformer worker: D:\Proj\node_modules\metro-bundler\src\transformer.js
    at _transform.then.catch.error (D:\Proj\node_modules\metro-bundler\src\JSTransformer\index.js:191:31)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by AllanFly120** [comment] 2018-01-15 05:39
Hi @non-standard 
I don't think this issue is related to our SDK. I find some other people also meet this problem, some of them solve this problem by setting a larger node memory size, maybe you can refer to [these issues](https://github.com/facebook/react-native/issues/12686). 
I will just close this issue. But feel free to reopen it if you have found a reproducible config or code that has something to do with aws-sdk.

**Closed by AllanFly120** 2018-01-15 05:39 UTC

**Comment by ER1011** [comment] 2018-02-14 04:01
same problem here. Added that line of code and can't build for release on Android anymore

**Comment by ER1011** [comment] 2018-02-19 23:20
@non-standard and @AllanFly120, we were able to solve this issue. Although the symptom was a memory issue, that does not seem to be the actual root cause. It appears that the AWS file we are importing is already transpiled and can be left out when doing the babel transformation. This can be achieved by adding the following to the package.json of our react native project:

  "babel": {
    "ignore": ["node_modules/aws-sdk/dist/aws-sdk-react-native.js"]
  },

Without the above, it seems that the packager goes into a loop and no matter how much memory you give node, it's never enough. We got a hint that this could be the issue looking at [this post](https://github.com/facebook/metro/issues/111). There are other ways to ignore said file (including adding the above code to the package.json of the aws-sdk itself. @AllanFly120 feel free to address it the way you deem more appropriate. At a minimum it'd be great if a note could be added to the readme for those that use the aws-sdk in a react-native project.

**Comment by truongluong1314520** [comment] 2018-12-04 14:58
Hi @ER1011 , I have the same issue like you. When I see your code, I feel like my life is saved. However, I add your code to my package.json in react native app but it is not working. It looks like the babel do not ignore is. Do you have any way to ignore a file in babel.

I try this but fail too: 

    npx babel node_modules --out-dir lib --ignore "node_modules/aws-sdk/dist/aws-sdk-react-native.js"

If you have any suggestion, please let me know. I am willing to hear from you

**Comment by truongluong1314520** [comment] 2018-12-05 05:01
Hi everyone , I am able to run debug by changing the `package.json` to:

    "scripts": {
        ...
      "start-max": "node --max-old-space-size=8192 node_modules/react-native/local-cli/cli.js start",
        ...
    },

In terminal run: "npm run start-max" to start the node server with 8,192 MB.
Then run your project as normal: "react-native run-android".

Enjoy!

**Comment by Blutude** [comment] 2019-02-26 23:23
I am able to run my simulator when running that "start-max" script, but when I try to upload my app to testflight, I keep getting the out of memory error. --max-old-space-size=8192 does not help.
I put the babel "ignore" command on both my app's package.json and the aws-sdk package.json but that does not help. Did anyone of you figure it out?

**Comment by truongluong1314520** [comment] 2019-03-02 02:32
Hi @Blutude , run "start-max" is only for debug mode. If you want to release, we have to config more. I write a post on Medium about it. Hope it can help you.

[React native max-old-space-size](https://medium.com/@ttqluong93/react-native-max-old-space-size-2af6754b5926)

Sorry for replying you late

**Comment by Blutude** [comment] 2019-03-02 20:43
I had actually seen that post and did try that. But the Xcode build still fails with JavaScript heap out of memory.
I can't use this package because of this. Instead I am using react-native-aws3 which works well, but it does not implement deleteObject (I can't delete files from s3), which I could do with aws-sdk

**Comment by truongluong1314520** [comment] 2019-03-04 02:18
Hi @Blutude , I guess it is because of the version. I fix the issue with: <br/>
1/ React native: "0.57.4"
2/ Xcode version: "10.1"

Can you please let me know your version?

**Comment by truongluong1314520** [comment] 2019-03-06 01:50
hey @Blutude , how is everything?

**Comment by Blutude** [comment] 2019-03-19 23:27
Hi @truongluong1314520, sorry for the late reply. I still have errors. My Xcode version is 10.1, React native is 0.58.6.

In build phases --> Bundle React Native code and images when I replace node by 'node  --max_old_space_size=8192', it gives me the following error: "Can't find 'node --max_old_space_size=8192' binary to build React Native bundle"

Instead, I try it without the quotes and archive the project but I get "FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory".

**Comment by truongluong1314520** [comment] 2019-03-20 01:54
Hi @Blutude , you can try this one:

    export NODE_ARGS="--max-old-space-size=8192"
    export NODE_BINARY="node"
../node_modules/react-native/scripts/react-native-xcode.sh

Maybe my previous solution is out of date 😞

**Comment by mikeRChambers610** [comment] 2019-06-20 03:42
I have been dealing with this issue for about 20 hours after reading about one hundred different posts. Seeing so many suggestions without examples or any guidance on where to insert scripts (cli / package.json / babel folders / node_module). PLEASE BE MORE SPECIFIC. :)))......>=//

**Comment by iampeterbanjo** [comment] 2019-08-06 09:37
I'm trying to use this SDK in a create-react-app but the build fails with an out of memory error (see below). The root cause is because I want to authenticate my app I'm using an Amazon profile. The API to perform an Amazon profile authentication is [SharedIniFileCredentials](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SharedIniFileCredentials.html) which is **ONLY** available on the root AWS class imported by `import AWS from 'aws-sdk`. I would rather import only the SDK I need e.g. `import AWS from 'aws-sdk/clients/ses';` but that's not possible because the API design means I won't have access to `SharedIniFileCredentials` method.

Could you please consider extending the API of the client classes so that they can be used without a dependency on the root class?

``` 
Security context: 0x35f19bba5891 <JSObject>
                      2: /* anonymous */(aka /* anonymous */) [/**/node_modules/webpack-sources/lib/applySourceMap.js:42] [bytecode=0x7f04049bd41 offset=26](this=0x27362d482201 <null>,mapping=0x2b6cdef70909 <Object map = 0x145050ebe741>)
                      3: arguments adaptor frame: 3->1
                      4: forEach(this=0x2377a1802249 <JSArray[211317]>)
                      5: eachMapping(aka SourceMapConsumer_eachMapping) [/dat...
                  
                  FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```
