### ISSUE TITLE
Snyk reports an issue on version 2.176.0

### ISSUE THREAD

**Issue by TangiX-DIY** [aws/aws-sdk-js#1856] opened 2018-01-05 08:05 UTC
There is an issue with crypto-browserify dependency

https://snyk.io/test/npm/aws-sdk?severity=high&severity=medium&severity=low

**Comment by jeskew** [comment] 2018-01-05 17:31
Hi @TangiX-DIY,

As discussed in #1853, the reported result is a false positive. The SDK does not use that part of `crypto-browserify` in any environment, and `crypto-browserify` is not used at all in Node.

Closing as a duplicate of #1853 and #1602

**Closed by jeskew** 2018-01-05 17:31 UTC
Labels: Duplicate
