### ISSUE TITLE
Can't upload file to Beijing S3

### ISSUE THREAD

**Issue by clues** [aws/aws-sdk-js#550] opened 2015-03-28 06:09 UTC
When i use sdk upload file to Beijing region,it's always return signature not match,etc.
Your code may be support secret auth version from V2 to V4.

Nb: I use java sdk to upload file to Beijing,it's work fine.

**Comment by lsegal** [comment] 2015-03-28 23:16
@clues can you provide your SDK version and code that reproduces the issue? Thanks!

**Comment by clues** [comment] 2015-03-30 10:44
@lsegal I have fixed it,it's my fault,i not update AWS config property 'signatureVersion' in my code.When i config follow,it's work (sdk #v2.1.5).

//If s3 in Beijing,it's special config follow
if ("CN_Beijing".toLowerCase() == global.awsConfig.region){
	    	global.awsConfig.region ="cn-north-1";
	    	global.awsConfig.signatureVersion ="v4";
}
AWS.config.update(global.awsConfig);

**Comment by AdityaManohar** [comment] 2015-04-01 19:32
@clues 
I'm marking this as closed since you seem to have it working. Feel free to reopen this issue or another issue if you have any questions.

**Closed by AdityaManohar** 2015-04-01 19:32 UTC
Labels: Feedback Requested
