### ISSUE TITLE
Unable to require using browserify

### ISSUE THREAD

**Issue by jasonvasquez** [aws/aws-sdk-js#504] opened 2015-02-10 21:50 UTC
I'm having an issue any time I attempt to require in aws-sdk with browserify.  Whenever I require aws-sdk in any source file, I receive the following error when I attempt to build with browserify:

    $ NODE_ENV=production browserify . > bundle.js
    Error: ENOTDIR, stat '<....>/aws-sdk-browserify/node_modules/aws-sdk/lib/browser.js/dist-tools/transform.js'
    at Error (native)

I've created an isolated sample application to demonstrate the behavior: https://github.com/jasonvasquez/aws-sdk-browserify

Thoughts?

**Comment by AdityaManohar** [comment] 2015-02-11 01:49
@jasonvasquez 
Browserify introduced a breaking change in v4.0 which included a module-deps overhaul. This changed the way transformation modules were fetched. 

For now you can use  Browserify v3.x, and it should work as expected. I will keep this open to track it when we do consider updating our dependencies.

Thanks for reporting!

**Comment by blocka** [comment] 2015-02-15 07:12
Isn't browserify up to v8? I also started having this randomly happen to me. I installed 6tofify, and then I started getting it. Now I can't stop it.

**Comment by blocka** [comment] 2015-02-15 08:14
The issue seems to be from a minor update to browser-resolve (1.7.0). I made a fork which uses 1.6.0 and doesn't have the issue (https://github.com/blocka/node-browserify). This is possibly also a bug in node-resolve https://github.com/defunctzombie/node-browser-resolve/pull/54

**Comment by AdityaManohar** [comment] 2015-02-15 10:56
@blocka 
Thanks for tracking this down to the breaking change in `browser-resolve v1.7.0`. I can confirm that I can get the builder to work with browser-resolve 1.6.0. I was also able to get it to work by locking in 
`node-resolve to 1.0.0`.

Referencing substack/node-resolve/issues/69.

**Comment by AdityaManohar** [comment] 2015-02-23 20:24
@jasonvasquez @blocka 
This is resolved in [node-resolve v1.1.3](https://github.com/substack/node-resolve/tree/1.1.3). I am able to build the SDK as a dependency  with `browserify 8.x`.

Closing this issue since the problem seems to be resolved. Feel free to re-open this issue or open another issue if you continue to have problems building the SDK as a dependency.

**Closed by AdityaManohar** 2015-02-23 20:24 UTC
Labels: Bug, Third Party

**Comment by blocka** [comment] 2015-02-24 07:39
Confirmed as well
