### ISSUE TITLE
Cannot assign filter policy to SQS subscription to SNS topic

### ISSUE THREAD

**Issue by brian-maloney** [aws/aws-sdk-js#3446] opened 2020-09-13 23:31 UTC
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/welcome.html) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js) for answers
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js/issues) and didn't find any solution
  
**Describe the bug**
When creating a SQS queue subscription to an SNS topic using the Javascript SDK, I get the error message `InvalidParameter: Invalid parameter: Attributes Reason: Delivery protocol SQS does not support message filtering.
`.  However I can create the filter in the AWS console and it works.  Someone else had this issue in 2018 but they didn't receive any feedback: https://forum.serverless.com/t/creating-subscription-with-filter-policy/6770

This feels like an issue with the actual AWS API but I wanted to report it here in case it's an issue with the SDK.

**Is the issue in the browser/Node.js?**
Browser

**If on Node.js, are you running this on AWS Lambda?**

**Details of the browser/Node.js version**
```  Browsers:
    Brave Browser: 85.1.13.82
    Edge: 85.0.564.51
    Firefox: 80.0.1
    Safari: 13.1.2
```
**SDK version number**
v2.751.0

**To Reproduce (observed behavior)**
```
sns.subscribe({
      TopicArn: topicArn,
      Protocol: "SQS",
      Endpoint: queueArn,
      Attributes: {
        RawMessageDelivery: "true",
        FilterPolicy: JSON.stringify({
          "Sender": [{"anything-but": [((AWS.config.credentials as AWS.CognitoIdentityCredentials).identityId)]}]
        })
      }
    })
```

**Expected behavior**
I expect the subscription to be created with the filter as defined.

**Comment by ajredniwja** [comment] 2020-09-17 20:01
@brian-maloney thanks for reaching out to us with your issue, I was not able to reproduce this issue, I was able to successfully create a subscription with SQS protocol using the SDK. Can you check your `FilterPolicy` and see if it is validated in the console? 

The code I used:
```JavaScript
var filterPolicy = {
    "type": [ "type1" ],
    "id": [ "1", "2" ]
};

var params = {
    TopicArn: "arn:aws:sns:us-west-2:xyz",
    Protocol: "sqs",
    Endpoint: "arn:aws:sqs:us-west-2xyz",
    Attributes: {
        RawMessageDelivery: "true",
        FilterPolicy: JSON.stringify(filterPolicy)
    }
};

sns.subscribe(params, function (err, data) {
    if (err) console.log(err);
    console.log(data);
}); 

```

Response: 

```
{
  ResponseMetadata: { RequestId: '8e9872e' },
  SubscriptionArn: 'arn:aws:sns:us-west-2xyz'
}
```

**Comment by brian-maloney** [comment] 2020-09-19 22:01
Thanks for the example code @ajredniwja!  I found my problem with your example.  It turns out that the case of the protocol is important.  While `SQS` works in that it successfully creates the subscription, filters only work when it is lower-case as in your example.  It's true the documentation correctly identifies that it should be lowercase, so this is my fault for not reading more carefully.  It's possible that the SDK could support this better by lowercasing any protocol input but I am also okay with closing this as-is.  If nothing else maybe someone else will see this someday.  I will leave the choice of whether to close up to you.

Thanks so much for the assistance!

**Comment by ajredniwja** [comment] 2020-11-02 23:31
@brian-maloney I like that idea but since its already been documented I would like to close this issue, this issue can also serve as a problem resolver for people ending up with similar problem. 


Will close this issue now, please reach out if you have any questions.

**Closed by ajredniwja** 2020-11-02 23:31 UTC
Labels: guidance

**Comment by alexspence** [comment] 2020-11-13 00:19
Had this same issue with terraform.  TLDR use "sqs" instead of "SQS"
