### ISSUE TITLE
Request timeout on putObject when using stream

### ISSUE THREAD

**Issue by ademartini** [aws/aws-sdk-js#673] opened 2015-08-01 15:17 UTC
I am sending a file from disk to S3 by opening  a stream (createReadStream) and calling putObject.  Body is set to the stream and ContentLength is set to the file size.  After a while I get a RequestTimeout:

```
    { [RequestTimeout: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.]
  message: 'Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.',
  code: 'RequestTimeout',
  time: Sat Aug 01 2015 15:09:57 GMT+0000 (UTC),
  statusCode: 400,
  retryable: true }
```

This doesn't happen with all files.  It may actually happen more with larger files.

**Comment by ademartini** [comment] 2015-08-03 13:43
The stream is definitely consumed because I added a handler for the end event, and it gets called:

https://nodejs.org/api/stream.html#stream_event_end

**Comment by ademartini** [comment] 2015-08-03 14:20
Also, I don't get any progress events from the request.

**Comment by AdityaManohar** [comment] 2015-08-03 20:10
The SDK does retry `RequestTimeout` errors. I'm not able to reproduce this issue with `v2.1.42` of the SDK. Which version of the SDK are you using?

> Also, I don't get any progress events from the request.

Here is a code snippet that demonstrates hooking into progress events. Does this look similar to something you are using? 

```javascript
var s3 = new AWS.S3();
var request = s3.putObject(params);

request.on('httpUploadProgress', function(progress) {
  console.log(progress);
});

request.send();
```
Any other information that you can provide to help reproduce the issue is welcome.

**Comment by AdityaManohar** [comment] 2015-08-05 04:58
@ademartini Adding to my previous comment, I would recommend using [`AWS.S3.ManagedUpload`](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3/ManagedUpload.html) to upload large objects to Amazon S3.

Here is a brief code snippet:

```javascript
var AWS = require('aws-sdk');
var fs = require('fs');

var file = fs.createReadStream('/path/to/file');
var s3 = new AWS.S3({region: 'us-west-2'});
var params = {
  Bucket: 'bucket',
  Key: 'key',
  Body: file
}

s3.upload(params, function(err, data){
  if (err) console.log(err);
  else console.log(data);
});
```
Hope this helps, and do let us know if you are continuing to have issues.

**Comment by AdityaManohar** [comment] 2015-08-18 01:17
@ademartini I'm marking this as closed as there hasn't been any activity on it for a while. Feel free to reopen this issue or open another issue if you continue to have problems.

**Closed by AdityaManohar** 2015-08-18 01:17 UTC
Labels: Question

**Comment by moshest** [comment] 2017-11-14 09:53
I have this problem also.

It's happens only for small files (25KB).
Larger files (1.5MB) works OK.

**Comment by alexanderbanks** [comment] 2017-12-05 23:47
I am having identical issues as @moshest . Only small files, switching to upload solved this problem.
