### ISSUE TITLE
getSignedUrl putObject issue on upload via URL to S3 with Postman on Mac 

### ISSUE THREAD

**Issue by stevenelson74708** [aws/aws-sdk-js#1237] opened 2016-11-23 06:19 UTC
When using Postman with the Content-Type of image/jpeg in the Header running on Ubuntu 16.04 to upload a file to the S3 with a PUT to a pre-signed url generated by the below node.js code running on Ubuntu 16.04 the file is properly uploaded to the S3. 

However, when using Postman with the same settings and Headers running on a Mac to upload a file to the S3 with a PUT to a pre-signed url generated by the same node.js code, the following S3 error is encountered:

    `<?xml version="1.0" encoding="UTF-8"?>
     <Error>
         <Code>NotImplemented</Code>
         <Message>A header you provided implies functionality that is not implemented</Message>
         <Header>Transfer-Encoding</Header>
         <RequestId>F3C03731682C4D04</RequestId> 
         <HostId>W9e+aiwwPolbpM6wZ3/hhCDUE1iRgJujPJD34NCQcwlobUvPNLGmLuUKbXpm611LR0TVbZ6tPJs=</HostId>
     </Error>`

Node.js code running on Ubuntu 16.04 to generate pre-signed putObject URL:

    `var params = {
        "Bucket": bucketName,
        "Key": s3Key,
        "ACL": 'authenticated-read',
        "ContentType": image/jpeg,
        "Metadata": {
            "object_id": item_doc_id.toString(),
            "os_filename": orgOsFilename,
            "s3key": s3Key,
            "read_only": itemDocObj.readOnly
        }
    };

    aws.config.loadFromPath('aws-config.json');
    var s3 = new aws.S3();

    s3.getSignedUrl('putObject', params, function (err1, url)
    {
           if (err1 == null)
           {
                callback({
                    "response": true, 
                    "res": "URL generated for File " + orgOsFilename + " for upload to S3",
                    "url": url
                });
           }
           else
           {
                callback( {
                    "response": false, 
                    "res": "Unable to generate URL for file " + orgOsFilename,
                    "url": null
                 } );
           }
    });`

Is there a reason why the S3 would generate an error from the PUT generated by Postman running on the Mac, but successfully upload the file from the PUT generated by Postman running on Ubuntu 16.04 with a url generated from the same node.js code in both cases?  

It appears as if the S3 is seeing Transfer-Encoding set in the Header from the Postman running on the Mac, whereas, the S3 is not seeing Transfer-Encoding (or not seeing it as a problem) set in the Header from the Postman running on Ubuntu 16.04.

Is there a way to get the upload via the pre-signed putObject url to succeed via the Postman running on the Mac?

**Comment by chrisradek** [comment] 2016-11-25 20:45
@stevenelson74708 
I'm not too familiar with Postman, can you share how the presigned URL is being used?

Does the URL look the same between mac and ubuntu? Is it possible to share them?

**Comment by stevenelson74708** [comment] 2016-11-25 22:55
The pre-signed URL is generated by common node.js code. The identical pre-signed URL works fine with Postman on Ubuntu 16.04, but fails with Postman on the Mac.

Here is a an example of a pre-signed URL that works with Postman on Ubuntu 16.04 but gets the NotImplemented error with Postman on the Mac:

    `https://nuubissnelsontestbucket.s3-us-west-2.amazonaws.com/5838bae502d21e140ab892d3/5838bb7a02d21e140ab892ec/e0092910-7f15-4ca0-a261-090fb759aeb1_t.jpg?AWSAccessKeyId=AWSACESSKEYID&Content-Type=image%2Fjpeg&Expires=1480113918&Signature=kZk6NBqVck%2Bg9290Powu%2F3ZUegg%3D&x-amz-acl=authenticated-read&x-amz-meta-object_id=5838bb7a02d21e140ab892ec&x-amz-meta-os_filename=NuubisTestImage.jpg&x-amz-meta-read_only=false&x-amz-meta-s3key=5838bae502d21e140ab892d3%2F5838bb7a02d21e140ab892ec%2Fe0092910-7f15-4ca0-a261-090fb759aeb1_t.jpg`

Below are screen shots of the Postman PUT with the above pre-signed URL (one showing the Headers and the other showing the Body): 

![postmanputtos3withpresignedurlheaders1](https://cloud.githubusercontent.com/assets/7818035/20636279/e04828ea-b31e-11e6-9f60-7e7829c11e19.png)

![postmanputtos3withpresignedurlbody1](https://cloud.githubusercontent.com/assets/7818035/20636281/e5fa2c20-b31e-11e6-96ee-9d2988ae13bb.png)

**Comment by jeskew** [comment] 2016-12-09 00:37
Since the same URL works on Postman on Ubuntu but not Postman on OS X, I don't believe the issue is related to how the pre-signed URL is being built. The original error reported would appear when S3 received a `Transfer-Encoding: chunked` header, which Postman may be setting behind the scenes. Does Postman let you see the response exactly as it was sent over the wire?

**Comment by stevenelson74708** [comment] 2016-12-09 02:38
Viewing the exact HTTP request and response with Postman is not [straightforward](http://blog.getpostman.com/2015/06/13/debugging-postman-requests/).

So, we've come up with a work around where we've removed the pre-signed URL file uploads to the S3 from Postman and instead use a script with curl commands for the pre-signed URL files uploads to the S3 and the curl uploads don't appear to exhibit the problem.

**Comment by jeskew** [comment] 2017-01-06 20:41
@stevenelson74708 It sounds like the problem is not with the presigned URLs themselves, but rather with Postman. I'm going to go ahead and close this out, as it's not an SDK issue, but please feel free to reopen if you discover that this is not the case.

**Closed by jeskew** 2017-01-06 20:41 UTC
Labels: Third Party

**Comment by mharis99** [comment] 2018-02-06 11:30
add one more header 
x-amz-acl:public-read

**Comment by dhananjayrspl** [comment] 2018-06-04 11:27
Did any worked with below scenario.

1 : Generate pre-signed url with Content-length and Content-MD5 with PUT method
2 : Use post man to upload file to s3 bucket using generated URL

Question : what header we need to pass and how to pass

**Comment by mharis99** [comment] 2018-06-04 11:39
Following are the headers:

          KEY           :       VALUE
1 -  Content-Type : image/jpeg
2 - x-amz-acl : public-read or private
3 - Content-Encoding : UTF-8
4 - Content-MD5 : Values of MD5 string

**Comment by dexterleng** [comment] 2019-03-29 08:30
Any updates on this?
